# **IV. Análisis de variables categóricas (Oncológicos vs Control)**

## Objetivo
Este notebook tiene el fin de analizar la distribución de frecuencias de las variables categóricas presentes en el dataset clasificado del GRD (2019-2024). Para evitar sesgos y permitir comparabilidad, se generarán matrices de frecuencias separadas para la población oncológica, el grupo de control (sin cáncer) y el total del hospital.

## Proceso
1. **Carga Optimizada y Estandarización**: Carga de forma selectiva las columnas de los archivos CSV anuales masivos, estandarizando nombres y filtrando por `CATEGORIA_CANCER`.
2. **Análisis de distribución tripartito**: Genera matrices de frecuencias absolutas y relativas (%) por año, separadas en tres subcarpetas: `Frecuencias (oncológicos)`, `Frecuencias (control)` y `Frecuencias (total)`.
3. **Evaluación de cardinalidad**: Permite justificar el uso, agrupación o descarte de las variables categóricas (como procedencias, previsiones o diagnósticos) para las posteriores etapas de modelado y selección de características.

In [1]:
# ============================================================================
# CONFIGURACIÓN INICIAL: Imports y Rutas
# ============================================================================

import pandas as pd
import os
import warnings 
import unicodedata
import re

# Suprimir advertencias sobre cambios de tipo de dato (dtype)
warnings.simplefilter(action='ignore', category=pd.errors.DtypeWarning)

# Ruta de datos clasificados (que contienen TODA la población y la columna CATEGORIA_CANCER)
carpeta = "../../Datos/Datos clasificados"

# Lista de archivos a procesar (años 2019-2024)
archivos = [
    "GRD_CLASIFICADO_2019.csv",
    "GRD_CLASIFICADO_2020.csv",
    "GRD_CLASIFICADO_2021.csv",
    "GRD_CLASIFICADO_2022.csv",
    "GRD_CLASIFICADO_2023.csv",
    "GRD_CLASIFICADO_2024.csv"
]

# Mapeo de equivalencias para estandarizar nombres de columnas inconsistentes
mapa_columnas = {
    "ï»¿COD_HOSPITAL": "COD_HOSPITAL",   # Corrige corrupción de encoding (BOM UTF-8)
    "ID_BENEFICIARIO": "CIP_ENCRIPTADO"  # Renombra a estándar de proyecto
}

In [2]:
# ============================================================================
# UTILIDADES: Funciones de Limpieza y Normalización
# ============================================================================

def normalizar_texto(texto):
    if texto is None:
        return None
    try:
        texto = texto.encode("latin1").decode("utf-8")
    except:
        pass
    texto = unicodedata.normalize("NFKD", texto)
    texto = "".join(c for c in texto if not unicodedata.combining(c))
    return texto

def obtener_subcarpeta(columna):
    if re.match(r"^SERVICIOTRASLADO\d+$", columna):
        return "servicios_traslado"
    if re.match(r"^(CONDICIONDEALTANEONATO\d+|PESORN\d+|SEXORN\d+|RN\d+ESTADO)$", columna):
        return "neonatal"
    if re.match(r"^DIAGNOSTICO\d+$", columna):
        return "diagnosticos"
    if re.match(r"^PROCEDIMIENTO\d+$", columna):
        return "procedimientos"
    return ""

def homologar_categorias(col, nombre_columna):
    if nombre_columna == "ETNIA":
        mapa = {
            "NINGUNA": "NINGUNO",
            "NINGUN": "NINGUNO",
            "SIN INFORMACION": "NINGUNO",
            "NO APLICA": "NINGUNO"
        }
        col = col.replace(mapa)
    return col

# ============================================================================
# FUNCIÓN PRINCIPAL: Cálculo de Distribución Simultánea (Ultra-optimizada)
# ============================================================================

def distribucion_categorica_matriz(carpeta, archivos, mapa_columnas, columna):
    """
    - Descripción: Lee los archivos una sola vez, separa las cohortes en RAM y 
                   genera simultáneamente las matrices de frecuencias para: 
                   Total, Oncológicos y Control.
    - Entradas:
        - columna (str): Nombre de la variable categórica a analizar.
    - Salidas:
        - tuple: (matriz_total, matriz_onco, matriz_control)
    """
    print(f"\n[{columna}] Extrayendo y procesando datos masivos (Una sola pasada)...")
    
    # Listas para acumular los conteos de todos los años
    resultados_total = []
    resultados_onco = []
    resultados_control = []
    
    categorias_globales = set()

    for archivo in archivos:
        ruta = os.path.join(carpeta, archivo)
        año_archivo = int(archivo[-8:-4])

        # 1. Verificar si la columna existe antes de cargar datos
        encabezados = pd.read_csv(ruta, nrows=0).rename(columns=mapa_columnas).columns
        if columna not in encabezados:
            continue

        # 2. Leer SOLO las columnas necesarias
        columnas_a_leer = [col for col in pd.read_csv(ruta, nrows=0).columns 
                           if col == columna or col == 'CATEGORIA_CANCER' or mapa_columnas.get(col) == columna]
        
        df = pd.read_csv(ruta, usecols=columnas_a_leer, low_memory=False).rename(columns=mapa_columnas)

        if df.empty:
            continue

        # 3. Limpieza y estandarización global (para no repetir el trabajo)
        col_original = df[columna]
        mask_null_real = col_original.isna()
        col = col_original.copy().astype("object")

        col[~mask_null_real] = (
            col[~mask_null_real]
            .astype(str)
            .str.strip()
            .apply(normalizar_texto)
            .str.upper()
        )

        col = homologar_categorias(col, columna)
        col = col.astype("object")
        col = col.mask(col.isin(["", "NAN", "NONE", "NULL"]), "NULOS")
        col = col.astype("string")
        col[mask_null_real] = "NULOS"
        
        # Asignar la columna limpia de vuelta al DataFrame
        df[columna] = col

        # 4. Separación de cohortes en memoria RAM (Operación Vectorizada)
        mask_control = df['CATEGORIA_CANCER'] == 'SIN_CANCER'
        
        df_control = df[mask_control]
        df_onco = df[~mask_control]
        
        # 5. Conteos Simultáneos
        conteo_total = df[columna].value_counts()
        conteo_onco = df_onco[columna].value_counts()
        conteo_control = df_control[columna].value_counts()

        # Actualizar conjunto global de categorías
        categorias_globales.update(conteo_total.index.tolist())

        # 6. Almacenar resultados para cada grupo
        for cat, freq in conteo_total.items():
            resultados_total.append({"Categoría": cat, "Año": año_archivo, "Frecuencia": freq})
            
        for cat, freq in conteo_onco.items():
            resultados_onco.append({"Categoría": cat, "Año": año_archivo, "Frecuencia": freq})
            
        for cat, freq in conteo_control.items():
            resultados_control.append({"Categoría": cat, "Año": año_archivo, "Frecuencia": freq})

    if not resultados_total:
        print(f"  -> No se encontraron datos para {columna}.")
        return None, None, None

    # =====================================================================
    # FUNCIÓN AUXILIAR INTERNA: Construir Matriz Pivote
    # =====================================================================
    def construir_matriz(lista_resultados):
        if not lista_resultados:
            return None
        df_res = pd.DataFrame(lista_resultados)
        matriz = df_res.pivot_table(index="Categoría", columns="Año", values="Frecuencia", fill_value=0)
        matriz = matriz.sort_index(axis=1)
        matriz["TOTAL"] = matriz.sum(axis=1)
        matriz = matriz.sort_values("TOTAL", ascending=False).drop(columns="TOTAL")
        matriz = matriz.fillna(0).astype(int)

        matriz_pct = matriz.div(matriz.sum(axis=0), axis=1) * 100
        matriz_final = matriz.copy().astype(str)
        for col_año in matriz.columns:
            matriz_final[col_año] = (
                matriz[col_año].astype(int).astype(str)
                + " (" + matriz_pct[col_año].round(1).astype(str) + "%)"
            )
        matriz_final.columns.name = None
        matriz_final.index.name = None
        return matriz_final

    # 7. Construir las tres matrices simultáneamente
    matriz_total = construir_matriz(resultados_total)
    matriz_onco = construir_matriz(resultados_onco)
    matriz_control = construir_matriz(resultados_control)

    # 8. Reporte de Cardinalidad
    categorias_limpias = sorted([c for c in categorias_globales if c not in ["NULOS", "DESCONOCIDO"]])
    print(f"✓ Cardinalidad {columna}: {len(categorias_limpias)} categorías únicas")

    # 9. Guardar en disco (Creación de subcarpetas automáticas)
    subcarpeta = obtener_subcarpeta(columna)
    nombres_y_matrices = [
        ("total", matriz_total),
        ("oncológicos", matriz_onco),
        ("control", matriz_control)
    ]
    
    for nombre_pob, matriz in nombres_y_matrices:
        if matriz is not None:
            carpeta_salida = os.path.join(f"../../Resultados/Resultados (etapa 1 y 2)/Frecuencias (categóricas)/Frecuencias ({nombre_pob})", subcarpeta)
            os.makedirs(carpeta_salida, exist_ok=True)
            ruta_salida = os.path.join(carpeta_salida, f"{columna.lower()}_frecuencia.csv")
            matriz.to_csv(ruta_salida, encoding="utf-8-sig")

    print(f"✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.")
    
    # 10. Retornar la tupla con las 3 tablas para visualización
    return matriz_total, matriz_onco, matriz_control

In [3]:
def mostrar_resultados(matriz_total, matriz_onco, matriz_control, variable):
    mensaje_total = f"1. Frecuencia para cohorte total ({variable}):"
    mensaje_oncologico = f"2. Frecuencia para cohorte oncológica ({variable}):"
    mensaje_control = f"3. Frecuencia para cohorte control ({variable}):"
    display(mensaje_total)
    display(matriz_total)
    display(mensaje_oncologico)
    display(matriz_onco)
    display(mensaje_control)
    display(matriz_control)

## **1. Variables categóricas objetivo:**

### **1. Mortalidad (TIPOALTA)**
- **Tipo de variable**: Objetivo (*Target*).
- **Descripción**: Condición de egreso o destino del paciente al finalizar su hospitalización.
- **Veredicto**: **Retener y Binarizar**. Esta variable representa la Verdad Fundamental (*Ground Truth*) del desenlace clínico. Al cruzar los datos, se observa un contraste estadístico crítico: la cohorte oncológica presenta una tasa de mortalidad de entre 5.4% y 6.9%, casi el triple que la del grupo control (~2.3%). Para habilitar los algoritmos de selección de características, las 11 categorías originales se binarizarán en una variable dicotómica: `FALLECIDO` (Clase Positiva) vs. `VIVO` (agrupando Alta voluntaria, Domicilio, Derivaciones, etc.). Las categorías marginales sin información (`NO IDENTIFICADA`, `DESCONOCIDO`) serán imputadas a la moda o descartadas.

In [4]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"TIPOALTA")
mostrar_resultados(total, oncologico, control, "TIPOALTA")

[TIPOALTA] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad TIPOALTA: 11 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (TIPOALTA):'

,2019,2020,2021,2022,2023,2024
DOMICILIO,1052020 (91.4%),694899 (88.9%),716270 (87.7%),838234 (89.9%),936205 (90.1%),967852 (89.1%)
FALLECIDO,29584 (2.6%),29942 (3.8%),31965 (3.9%),27379 (2.9%),25136 (2.4%),26682 (2.5%)
HOSPITALIZACION DOMICILIARIA,12987 (1.1%),14071 (1.8%),22403 (2.7%),23408 (2.5%),29298 (2.8%),36732 (3.4%)
DERIVACION OTRO HOSPITAL DEL SERVICIO,25206 (2.2%),17839 (2.3%),18321 (2.2%),16488 (1.8%),20505 (2.0%),24923 (2.3%)
ALTA VOLUNTARIA,9963 (0.9%),7569 (1.0%),9059 (1.1%),10721 (1.1%),10317 (1.0%),10651 (1.0%)
DERIVACION OTRO HOSPITAL DE LA RED NACIONAL,8415 (0.7%),6871 (0.9%),7194 (0.9%),6539 (0.7%),7472 (0.7%),7938 (0.7%)
"DERIVACION A OTROS CENTROS (CARCEL, HOGAR DE",2980 (0.3%),4396 (0.6%),4038 (0.5%),3385 (0.4%),3497 (0.3%),3745 (0.3%)
FUGA DEL PACIENTE,4141 (0.4%),2719 (0.3%),2593 (0.3%),3184 (0.3%),3224 (0.3%),3299 (0.3%)
DERIVACION INST. PRIVADA (COMPRA DE SERVICIOS,4411 (0.4%),2430 (0.3%),3688 (0.5%),2373 (0.3%),2886 (0.3%),2865 (0.3%)
DERIVACION INST. PRIVADA (VOLUNTARIO),1614 (0.1%),1152 (0.1%),1378 (0.2%),1126 (0.1%),1047 (0.1%),1126 (0.1%)
NO IDENTIFICADA,58 (0.0%),22 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,19 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (TIPOALTA):'

,2019,2020,2021,2022,2023,2024
DOMICILIO,88008 (90.0%),56334 (86.8%),58867 (86.7%),67703 (86.7%),78385 (86.4%),84680 (85.4%)
FALLECIDO,5321 (5.4%),4462 (6.9%),4423 (6.5%),4850 (6.2%),5314 (5.9%),6009 (6.1%)
HOSPITALIZACION DOMICILIARIA,1319 (1.3%),1471 (2.3%),2110 (3.1%),2741 (3.5%),3531 (3.9%),4473 (4.5%)
DERIVACION OTRO HOSPITAL DEL SERVICIO,1631 (1.7%),1198 (1.8%),1069 (1.6%),1242 (1.6%),1671 (1.8%),2147 (2.2%)
DERIVACION OTRO HOSPITAL DE LA RED NACIONAL,659 (0.7%),584 (0.9%),541 (0.8%),560 (0.7%),688 (0.8%),755 (0.8%)
ALTA VOLUNTARIA,526 (0.5%),498 (0.8%),569 (0.8%),646 (0.8%),710 (0.8%),652 (0.7%)
"DERIVACION A OTROS CENTROS (CARCEL, HOGAR DE",76 (0.1%),171 (0.3%),135 (0.2%),116 (0.1%),143 (0.2%),139 (0.1%)
DERIVACION INST. PRIVADA (COMPRA DE SERVICIOS,144 (0.1%),97 (0.1%),112 (0.2%),91 (0.1%),142 (0.2%),167 (0.2%)
FUGA DEL PACIENTE,75 (0.1%),60 (0.1%),49 (0.1%),69 (0.1%),77 (0.1%),79 (0.1%)
DERIVACION INST. PRIVADA (VOLUNTARIO),65 (0.1%),50 (0.1%),51 (0.1%),51 (0.1%),54 (0.1%),52 (0.1%)
NO IDENTIFICADA,4 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (TIPOALTA):'

,2019,2020,2021,2022,2023,2024
DOMICILIO,964012 (91.5%),638565 (89.1%),657403 (87.8%),770531 (90.1%),857820 (90.4%),883172 (89.5%)
FALLECIDO,24263 (2.3%),25480 (3.6%),27542 (3.7%),22529 (2.6%),19822 (2.1%),20673 (2.1%)
HOSPITALIZACION DOMICILIARIA,11668 (1.1%),12600 (1.8%),20293 (2.7%),20667 (2.4%),25767 (2.7%),32259 (3.3%)
DERIVACION OTRO HOSPITAL DEL SERVICIO,23575 (2.2%),16641 (2.3%),17252 (2.3%),15246 (1.8%),18834 (2.0%),22776 (2.3%)
ALTA VOLUNTARIA,9437 (0.9%),7071 (1.0%),8490 (1.1%),10075 (1.2%),9607 (1.0%),9999 (1.0%)
DERIVACION OTRO HOSPITAL DE LA RED NACIONAL,7756 (0.7%),6287 (0.9%),6653 (0.9%),5979 (0.7%),6784 (0.7%),7183 (0.7%)
"DERIVACION A OTROS CENTROS (CARCEL, HOGAR DE",2904 (0.3%),4225 (0.6%),3903 (0.5%),3269 (0.4%),3354 (0.4%),3606 (0.4%)
FUGA DEL PACIENTE,4066 (0.4%),2659 (0.4%),2544 (0.3%),3115 (0.4%),3147 (0.3%),3220 (0.3%)
DERIVACION INST. PRIVADA (COMPRA DE SERVICIOS,4267 (0.4%),2333 (0.3%),3576 (0.5%),2282 (0.3%),2744 (0.3%),2698 (0.3%)
DERIVACION INST. PRIVADA (VOLUNTARIO),1549 (0.1%),1102 (0.2%),1327 (0.2%),1075 (0.1%),993 (0.1%),1074 (0.1%)
NO IDENTIFICADA,54 (0.0%),21 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,18 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **2. Severidad (SEVERIDAD)**
- **Tipo de variable**: Objetivo (*Target*).
- **Descripción**: Métrica oficial del agrupador GRD que clasifica la extensión de la descompensación fisiológica y pérdida de función de órganos.
- **Veredicto**: **Retener como variable ordinal**. Es el segundo objetivo de caracterización del estudio. La matriz de frecuencias justifica plenamente su estudio: más del 29% de los pacientes oncológicos alcanzan la categoría de Gravedad Mayor (Nivel 3), en contraste con el ~19% del grupo control. Se mantendrá su escala discreta (0 a 3) nativa.

| ID | Gravedad     |
|----|--------------|
| 0  | Sin gravedad |
| 1  | Menor        |
| 2  | Moderada     |
| 3  | Mayor        |

In [5]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"IR_29301_SEVERIDAD")
mostrar_resultados(total, oncologico, control, "IR_29301_SEVERIDAD")

[IR_29301_SEVERIDAD] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad IR_29301_SEVERIDAD: 4 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (IR_29301_SEVERIDAD):'

,2019,2020,2021,2022,2023,2024
1,558571 (48.5%),366293 (46.8%),340136 (41.6%),373440 (40.0%),388694 (37.4%),387258 (35.7%)
2,242291 (21.0%),176554 (22.6%),183822 (22.5%),213260 (22.9%),253086 (24.3%),268865 (24.8%)
3,147998 (12.9%),159400 (20.4%),190013 (23.3%),191342 (20.5%),204227 (19.6%),217624 (20.0%)
0,202517 (17.6%),79664 (10.2%),102938 (12.6%),154772 (16.6%),193550 (18.6%),212051 (19.5%)
DESCONOCIDO,21 (0.0%),0 (0.0%),0 (0.0%),23 (0.0%),30 (0.0%),15 (0.0%)

'2. Frecuencia para cohorte oncológica (IR_29301_SEVERIDAD):'

,2019,2020,2021,2022,2023,2024
2,30680 (31.4%),23807 (36.7%),23718 (34.9%),26710 (34.2%),31917 (35.2%),34607 (34.9%)
3,19771 (20.2%),18413 (28.4%),19393 (28.6%),22960 (29.4%),26813 (29.6%),30265 (30.5%)
1,26703 (27.3%),19058 (29.4%),19126 (28.2%),20488 (26.2%),21770 (24.0%),23198 (23.4%)
0,20675 (21.1%),3648 (5.6%),5689 (8.4%),7909 (10.1%),10215 (11.3%),11081 (11.2%)
DESCONOCIDO,0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%),2 (0.0%)

'3. Frecuencia para cohorte control (IR_29301_SEVERIDAD):'

,2019,2020,2021,2022,2023,2024
1,531868 (50.5%),347235 (48.4%),321010 (42.9%),352952 (41.3%),366924 (38.7%),364060 (36.9%)
2,211611 (20.1%),152747 (21.3%),160104 (21.4%),186550 (21.8%),221169 (23.3%),234258 (23.7%)
3,128227 (12.2%),140987 (19.7%),170620 (22.8%),168382 (19.7%),177414 (18.7%),187359 (19.0%)
0,181842 (17.3%),76016 (10.6%),97249 (13.0%),146863 (17.2%),183335 (19.3%),200970 (20.4%)
DESCONOCIDO,21 (0.0%),0 (0.0%),0 (0.0%),21 (0.0%),30 (0.0%),13 (0.0%)

## **2. Resto de variables categóricas:**

### **3. Sexo (SEXO)**
- **Tipo de variable**: Demográfica.
- **Descripción**: Sexo biológico del paciente.
- **Cardinalidad**: Tiene 2 categorías y la etiqueta "DESCONOCIDO" es marginal (0.0%).
- **Veredicto**: **Retener**. Presenta una cardinalidad perfecta (2 categorías útiles) y una distribución equilibrada y constante a lo largo de los 6 años (~59% mujeres, ~41% hombres en la población general; y ~53% mujeres, ~46% hombres en oncología). Es un factor demográfico fundamental en la literatura médica para explicar la prevalencia y severidad de perfiles clínicos.

In [6]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"SEXO")
mostrar_resultados(total, oncologico, control, "SEXO")

[SEXO] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SEXO: 2 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SEXO):'

,2019,2020,2021,2022,2023,2024
MUJER,681573 (59.2%),461635 (59.0%),475306 (58.2%),553565 (59.3%),612203 (58.9%),632623 (58.3%)
HOMBRE,469670 (40.8%),320142 (40.9%),341540 (41.8%),379220 (40.7%),427345 (41.1%),453074 (41.7%)
DESCONOCIDO,155 (0.0%),134 (0.0%),63 (0.0%),52 (0.0%),39 (0.0%),116 (0.0%)

'2. Frecuencia para cohorte oncológica (SEXO):'

,2019,2020,2021,2022,2023,2024
MUJER,53312 (54.5%),34474 (53.1%),36044 (53.1%),41965 (53.8%),48594 (53.6%),53224 (53.7%)
HOMBRE,44513 (45.5%),30448 (46.9%),31882 (46.9%),36101 (46.2%),42120 (46.4%),45910 (46.3%)
DESCONOCIDO,4 (0.0%),4 (0.0%),0 (0.0%),3 (0.0%),1 (0.0%),19 (0.0%)

'3. Frecuencia para cohorte control (SEXO):'

,2019,2020,2021,2022,2023,2024
MUJER,628261 (59.6%),427161 (59.6%),439262 (58.6%),511600 (59.9%),563609 (59.4%),579399 (58.7%)
HOMBRE,425157 (40.4%),289694 (40.4%),309658 (41.3%),343119 (40.1%),385225 (40.6%),407164 (41.3%)
DESCONOCIDO,151 (0.0%),130 (0.0%),63 (0.0%),49 (0.0%),38 (0.0%),97 (0.0%)

### **4. Etnia (ETNIA)**
- **Tipo de variable**: Demográfica.
- **Descripción**: Pertenencia declarada a algún pueblo originario.
- **Cardinalidad**: Tiene 12 categorías. 
- **Veredicto**: Transformar y Binarizar (ES_PUEBLO_ORIGINARIO). El análisis revela una varianza nativa casi nula y un quiebre en las políticas de registro del MINSAL/FONASA (en 2022 y 2023 la categoría NINGUNO desaparece y es reemplazada íntegramente por OTRO). Para rescatar el valor epidemiológico de esta variable como determinante social de la salud, se aplicará ingeniería de características creando una variable dicotómica. Todas las categorías específicas (Mapuche, Aymara, Rapa Nui, etc.) conformarán la clase positiva (1), mientras que NINGUNO y OTRO conformarán la clase de control (0). Esta transformación neutraliza el error de codificación interanual y previene la alta dimensionalidad, permitiendo que las técnicas de Bootstrapping evalúen su impacto real en los perfiles de severidad y consumo.

In [7]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"ETNIA")
mostrar_resultados(total, oncologico, control, "ETNIA")

[ETNIA] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad ETNIA: 12 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (ETNIA):'

,2019,2020,2021,2022,2023,2024
NINGUNO,816886 (70.9%),668294 (85.5%),769595 (94.2%),0 (0.0%),0 (0.0%),1058981 (97.5%)
OTRO,313517 (27.2%),96019 (12.3%),28492 (3.5%),912573 (97.8%),1016554 (97.8%),0 (0.0%)
MAPUCHE,19224 (1.7%),14976 (1.9%),14867 (1.8%),15336 (1.6%),17334 (1.7%),20494 (1.9%)
AYMARA,659 (0.1%),1249 (0.2%),1968 (0.2%),2247 (0.2%),2355 (0.2%),2637 (0.2%)
RAPA NUI (PASCUENSE),41 (0.0%),24 (0.0%),124 (0.0%),1162 (0.1%),1389 (0.1%),1339 (0.1%)
DIAGUITA,94 (0.0%),98 (0.0%),392 (0.0%),682 (0.1%),837 (0.1%),1106 (0.1%)
KAWESQAR,689 (0.1%),820 (0.1%),835 (0.1%),77 (0.0%),201 (0.0%),250 (0.0%)
QUECHUA,180 (0.0%),217 (0.0%),289 (0.0%),399 (0.0%),407 (0.0%),403 (0.0%)
YAGAN (YAMANA),25 (0.0%),114 (0.0%),215 (0.0%),211 (0.0%),247 (0.0%),276 (0.0%)
COLLA,45 (0.0%),64 (0.0%),84 (0.0%),75 (0.0%),81 (0.0%),169 (0.0%)
LICAN ANTAI (ATACAMENO),18 (0.0%),36 (0.0%),48 (0.0%),75 (0.0%),182 (0.0%),158 (0.0%)
DESCONOCIDO,19 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NO RESPONDE,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (ETNIA):'

,2019,2020,2021,2022,2023,2024
NINGUNO,73566 (75.2%),56185 (86.5%),64882 (95.5%),0 (0.0%),0 (0.0%),96967 (97.8%)
OTRO,22863 (23.4%),7361 (11.3%),1766 (2.6%),76762 (98.3%),88964 (98.1%),0 (0.0%)
MAPUCHE,1332 (1.4%),1224 (1.9%),1095 (1.6%),1007 (1.3%),1355 (1.5%),1771 (1.8%)
AYMARA,9 (0.0%),51 (0.1%),66 (0.1%),91 (0.1%),143 (0.2%),139 (0.1%)
RAPA NUI (PASCUENSE),4 (0.0%),0 (0.0%),17 (0.0%),123 (0.2%),115 (0.1%),141 (0.1%)
KAWESQAR,42 (0.0%),63 (0.1%),50 (0.1%),6 (0.0%),6 (0.0%),15 (0.0%)
DIAGUITA,2 (0.0%),4 (0.0%),16 (0.0%),30 (0.0%),58 (0.1%),69 (0.1%)
YAGAN (YAMANA),0 (0.0%),25 (0.0%),28 (0.0%),17 (0.0%),30 (0.0%),21 (0.0%)
QUECHUA,10 (0.0%),7 (0.0%),3 (0.0%),18 (0.0%),9 (0.0%),11 (0.0%)
LICAN ANTAI (ATACAMENO),0 (0.0%),6 (0.0%),0 (0.0%),8 (0.0%),25 (0.0%),8 (0.0%)
COLLA,1 (0.0%),0 (0.0%),3 (0.0%),7 (0.0%),10 (0.0%),11 (0.0%)

'3. Frecuencia para cohorte control (ETNIA):'

,2019,2020,2021,2022,2023,2024
NINGUNO,743320 (70.6%),612109 (85.4%),704713 (94.1%),0 (0.0%),0 (0.0%),962014 (97.5%)
OTRO,290654 (27.6%),88658 (12.4%),26726 (3.6%),835811 (97.8%),927590 (97.8%),0 (0.0%)
MAPUCHE,17892 (1.7%),13752 (1.9%),13772 (1.8%),14329 (1.7%),15979 (1.7%),18723 (1.9%)
AYMARA,650 (0.1%),1198 (0.2%),1902 (0.3%),2156 (0.3%),2212 (0.2%),2498 (0.3%)
RAPA NUI (PASCUENSE),37 (0.0%),24 (0.0%),107 (0.0%),1039 (0.1%),1274 (0.1%),1198 (0.1%)
DIAGUITA,92 (0.0%),94 (0.0%),376 (0.1%),652 (0.1%),779 (0.1%),1037 (0.1%)
KAWESQAR,647 (0.1%),757 (0.1%),785 (0.1%),71 (0.0%),195 (0.0%),235 (0.0%)
QUECHUA,170 (0.0%),210 (0.0%),286 (0.0%),381 (0.0%),398 (0.0%),392 (0.0%)
YAGAN (YAMANA),25 (0.0%),89 (0.0%),187 (0.0%),194 (0.0%),217 (0.0%),255 (0.0%)
COLLA,44 (0.0%),64 (0.0%),81 (0.0%),68 (0.0%),71 (0.0%),158 (0.0%)
LICAN ANTAI (ATACAMENO),18 (0.0%),30 (0.0%),48 (0.0%),67 (0.0%),157 (0.0%),150 (0.0%)
DESCONOCIDO,19 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NO RESPONDE,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **5. Provincia de Residencia (PROVINCIA)**
- **Tipo de variable**: Geográfica / Demográfica.
- **Descripción**: Provincia registrada como domicilio del paciente.
- **Cardinalidad**: Tiene 57 categorías (una cantidad grande)
- **Veredicto**: **Retener y Transformar (Agrupar a Nivel Regional)**. Mantener las 57 categorías provinciales generaría una matriz excesivamente dispersa. Sin embargo, el dato geográfico es valioso. La estrategia metodológica será mapear y agrupar las 57 provincias en sus respectivas 16 Regiones de Chile. Esto reduce drásticamente la cardinalidad, mantiene la explicabilidad territorial y facilita la convergencia de los algoritmos de aprendizaje automático al evaluar el traslado y centralización de los pacientes.

In [8]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"PROVINCIA")
mostrar_resultados(total, oncologico, control, "PROVINCIA")

[PROVINCIA] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROVINCIA: 57 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROVINCIA):'

,2019,2020,2021,2022,2023,2024
SANTIAGO,290205 (25.2%),204076 (26.1%),205803 (25.2%),232534 (24.9%),248038 (23.9%),248393 (22.9%)
CONCEPCION,66585 (5.8%),43516 (5.6%),47713 (5.8%),55095 (5.9%),69925 (6.7%),77672 (7.2%)
CAUTIN,57863 (5.0%),40466 (5.2%),38557 (4.7%),41622 (4.5%),47168 (4.5%),59183 (5.5%)
CORDILLERA,48166 (4.2%),32440 (4.1%),37480 (4.6%),40271 (4.3%),41957 (4.0%),42239 (3.9%)
VALPARAISO,63552 (5.5%),28405 (3.6%),28632 (3.5%),33483 (3.6%),42867 (4.1%),44310 (4.1%)
ELQUI,34870 (3.0%),24793 (3.2%),27168 (3.3%),29738 (3.2%),36556 (3.5%),37796 (3.5%)
BIO-BIO,33956 (2.9%),22459 (2.9%),23155 (2.8%),29483 (3.2%),31693 (3.0%),31095 (2.9%)
CACHAPOAL,31129 (2.7%),21896 (2.8%),22167 (2.7%),24949 (2.7%),25681 (2.5%),26974 (2.5%)
TALCA,27068 (2.4%),20942 (2.7%),21016 (2.6%),24653 (2.6%),26197 (2.5%),30924 (2.8%)
LLANQUIHUE,28862 (2.5%),20452 (2.6%),21484 (2.6%),23364 (2.5%),27543 (2.6%),28922 (2.7%)
MAIPO,24845 (2.2%),17089 (2.2%),19825 (2.4%),23633 (2.5%),24122 (2.3%),24745 (2.3%)
LINARES,25106 (2.2%),17812 (2.3%),18757 (2.3%),21869 (2.3%),23422 (2.3%),23234 (2.1%)
DIGUILLIN,22306 (1.9%),14908 (1.9%),16749 (2.1%),19844 (2.1%),21362 (2.1%),22057 (2.0%)
ANTOFAGASTA,21304 (1.9%),16705 (2.1%),18252 (2.2%),18854 (2.0%),18960 (1.8%),20785 (1.9%)
IQUIQUE,21617 (1.9%),16456 (2.1%),17308 (2.1%),18913 (2.0%),20029 (1.9%),19794 (1.8%)
ARICA,20480 (1.8%),15553 (2.0%),17100 (2.1%),18505 (2.0%),19969 (1.9%),20361 (1.9%)
MALLECO,20044 (1.7%),13669 (1.7%),16340 (2.0%),19519 (2.1%),20813 (2.0%),21331 (2.0%)
CURICO,22230 (1.9%),14635 (1.9%),13972 (1.7%),17843 (1.9%),19649 (1.9%),22356 (2.1%)
OSORNO,22240 (1.9%),14814 (1.9%),14921 (1.8%),17355 (1.9%),19470 (1.9%),20288 (1.9%)
VALDIVIA,20572 (1.8%),13778 (1.8%),14127 (1.7%),16700 (1.8%),20431 (2.0%),19935 (1.8%)
COLCHAGUA,17724 (1.5%),11413 (1.5%),12171 (1.5%),15344 (1.6%),15584 (1.5%),15508 (1.4%)
TALAGANTE,14454 (1.3%),9898 (1.3%),10671 (1.3%),12462 (1.3%),14915 (1.4%),14848 (1.4%)
MARGA MARGA,19059 (1.7%),9795 (1.3%),9709 (1.2%),11244 (1.2%),13302 (1.3%),14100 (1.3%)
COPIAPO,13699 (1.2%),10418 (1.3%),11253 (1.4%),11573 (1.2%),12808 (1.2%),13831 (1.3%)
SAN FELIPE,14223 (1.2%),9970 (1.3%),9619 (1.2%),11348 (1.2%),12910 (1.2%),13451 (1.2%)
MELIPILLA,11866 (1.0%),8968 (1.1%),9624 (1.2%),11854 (1.3%),13634 (1.3%),15007 (1.4%)
LIMARI,14520 (1.3%),8675 (1.1%),9166 (1.1%),11926 (1.3%),13281 (1.3%),12294 (1.1%)
EL LOA,10842 (0.9%),9523 (1.2%),9966 (1.2%),11410 (1.2%),12556 (1.2%),12106 (1.1%)
MAGALLANES,12400 (1.1%),8261 (1.1%),9669 (1.2%),10659 (1.1%),12346 (1.2%),12608 (1.2%)
SAN ANTONIO,12458 (1.1%),7432 (1.0%),8865 (1.1%),10016 (1.1%),11864 (1.1%),12347 (1.1%)
QUILLOTA,12378 (1.1%),7944 (1.0%),8023 (1.0%),8819 (0.9%),12468 (1.2%),12750 (1.2%)
ARAUCO,10492 (0.9%),7520 (1.0%),7448 (0.9%),8971 (1.0%),10076 (1.0%),9890 (0.9%)
CHILOE,11618 (1.0%),7028 (0.9%),7475 (0.9%),8977 (1.0%),9391 (0.9%),9453 (0.9%)
CHACABUCO,9204 (0.8%),6148 (0.8%),7726 (0.9%),9178 (1.0%),10031 (1.0%),9934 (0.9%)
LOS ANDES,9896 (0.9%),6991 (0.9%),7085 (0.9%),7799 (0.8%),8781 (0.8%),9308 (0.9%)
PUNILLA,3089 (0.3%),5101 (0.7%),7552 (0.9%),8837 (0.9%),9784 (0.9%),10667 (1.0%)
COIHAIQUE,7506 (0.7%),5532 (0.7%),5405 (0.7%),6172 (0.7%),7358 (0.7%),7570 (0.7%)
HUASCO,6313 (0.5%),4786 (0.6%),4985 (0.6%),6040 (0.6%),6801 (0.7%),6910 (0.6%)
RANCO,4557 (0.4%),2974 (0.4%),3039 (0.4%),3191 (0.3%),4084 (0.4%),3921 (0.4%)
PETORCA,3767 (0.3%),2354 (0.3%),2321 (0.3%),2397 (0.3%),3385 (0.3%),3578 (0.3%)
ITATA,2237 (0.2%),1951 (0.2%),2443 (0.3%),2705 (0.3%),3048 (0.3%),3194 (0.3%)
CARDENAL CARO,2865 (0.2%),1805 (0.2%),2125 (0.3%),2576 (0.3%),2658 (0.3%),2740 (0.3%)
CAUQUENES,1842 (0.2%),1228 (0.2%),1242 (0.2%),1560 (0.2%),1702 (0.2%),6388 (0.6%)
NUBLE,8808 (0.8%),2432 (0.3%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
AISEN,2021 (0.2%),1657 (0.2%),1670 (0.2%),1771 (0.2%),1978 (0.2%),2057 (0.2%)
CHOAPA,2406 (0.2%),1108 (0.1%),1390 (0.2%),1667 (0.2%),1903 (0.2%),1971 (0.2%)
TAMARUGAL,1505 (0.1%),1286 (0.2%),1219 (0.1%),1153 (0.1%),1303 (0.1%),1306 (0.1%)
TOCOPILLA,1336 (0.1%),887 (0.1%),949 (0.1%),980 (0.1%),1060 (0.1%),1185 (0.1%)
CHANARAL,1069 (0.1%),1005 (0.1%),1020 (0.1%),1076 (0.1%),1187 (0.1%),921 (0.1%)
PALENA,933 (0.1%),729 (0.1%),725 (0.1%),857 (0.1%),977 (0.1%),1019 (0.1%)
ULTIMA ESPERANZA,994 (0.1%),563 (0.1%),687 (0.1%),728 (0.1%),830 (0.1%),731 (0.1%)
GENERAL CARRERA,511 (0.0%),350 (0.0%),392 (0.0%),486 (0.1%),546 (0.1%),566 (0.1%)
DESCONOCIDO,825 (0.1%),627 (0.1%),40 (0.0%),43 (0.0%),280 (0.0%),393 (0.0%)
TIERRA DEL FUEGO,397 (0.0%),282 (0.0%),322 (0.0%),285 (0.0%),278 (0.0%),264 (0.0%)
CAPITAN PRAT,279 (0.0%),215 (0.0%),208 (0.0%),279 (0.0%),346 (0.0%),348 (0.0%)
ISLA DE PASCUA,226 (0.0%),119 (0.0%),129 (0.0%),189 (0.0%),215 (0.0%),190 (0.0%)
ANTARTICA CHILENA,75 (0.0%),49 (0.0%),41 (0.0%),35 (0.0%),54 (0.0%),59 (0.0%)
PARINACOTA,4 (0.0%),23 (0.0%),9 (0.0%),3 (0.0%),11 (0.0%),6 (0.0%)

'2. Frecuencia para cohorte oncológica (PROVINCIA):'

,2019,2020,2021,2022,2023,2024
SANTIAGO,24391 (24.9%),16424 (25.3%),17256 (25.4%),19849 (25.4%),22671 (25.0%),23842 (24.0%)
CONCEPCION,6208 (6.3%),4570 (7.0%),5221 (7.7%),6136 (7.9%),7384 (8.1%),8217 (8.3%)
CORDILLERA,6913 (7.1%),3429 (5.3%),4048 (6.0%),4528 (5.8%),4741 (5.2%),5031 (5.1%)
VALPARAISO,8147 (8.3%),3175 (4.9%),2695 (4.0%),3543 (4.5%),4945 (5.5%),5115 (5.2%)
CAUTIN,4480 (4.6%),3484 (5.4%),3243 (4.8%),3356 (4.3%),4148 (4.6%),5341 (5.4%)
ELQUI,2316 (2.4%),1892 (2.9%),2087 (3.1%),2352 (3.0%),2998 (3.3%),3301 (3.3%)
TALCA,2079 (2.1%),1743 (2.7%),1928 (2.8%),2047 (2.6%),2282 (2.5%),2564 (2.6%)
BIO-BIO,2125 (2.2%),1518 (2.3%),1661 (2.4%),2280 (2.9%),2367 (2.6%),2610 (2.6%)
CACHAPOAL,2041 (2.1%),1834 (2.8%),1880 (2.8%),2086 (2.7%),2214 (2.4%),2332 (2.4%)
LLANQUIHUE,2360 (2.4%),1802 (2.8%),1750 (2.6%),1679 (2.2%),2182 (2.4%),2346 (2.4%)
ANTOFAGASTA,2323 (2.4%),1654 (2.5%),1580 (2.3%),1731 (2.2%),2017 (2.2%),2302 (2.3%)
VALDIVIA,1902 (1.9%),1687 (2.6%),1608 (2.4%),1909 (2.4%),2205 (2.4%),2256 (2.3%)
OSORNO,2392 (2.4%),1366 (2.1%),1432 (2.1%),1454 (1.9%),1771 (2.0%),1932 (1.9%)
LINARES,2089 (2.1%),1391 (2.1%),1387 (2.0%),1640 (2.1%),1766 (1.9%),1812 (1.8%)
ARICA,1766 (1.8%),1453 (2.2%),1375 (2.0%),1459 (1.9%),1761 (1.9%),1898 (1.9%)
DIGUILLIN,1405 (1.4%),1105 (1.7%),1402 (2.1%),1643 (2.1%),1620 (1.8%),2082 (2.1%)
IQUIQUE,1401 (1.4%),1164 (1.8%),1250 (1.8%),1397 (1.8%),1563 (1.7%),1909 (1.9%)
MAIPO,1421 (1.5%),923 (1.4%),1102 (1.6%),1408 (1.8%),1553 (1.7%),1670 (1.7%)
MALLECO,1222 (1.2%),1038 (1.6%),1126 (1.7%),1247 (1.6%),1556 (1.7%),1463 (1.5%)
CURICO,1309 (1.3%),1016 (1.6%),980 (1.4%),1201 (1.5%),1363 (1.5%),1672 (1.7%)
MARGA MARGA,2562 (2.6%),824 (1.3%),638 (0.9%),897 (1.1%),1179 (1.3%),1280 (1.3%)
TALAGANTE,1116 (1.1%),778 (1.2%),1068 (1.6%),1326 (1.7%),1464 (1.6%),1502 (1.5%)
SAN FELIPE,1142 (1.2%),736 (1.1%),667 (1.0%),851 (1.1%),1012 (1.1%),1127 (1.1%)
SAN ANTONIO,1469 (1.5%),579 (0.9%),672 (1.0%),755 (1.0%),899 (1.0%),972 (1.0%)
MELIPILLA,839 (0.9%),634 (1.0%),753 (1.1%),875 (1.1%),1081 (1.2%),1108 (1.1%)
QUILLOTA,1336 (1.4%),571 (0.9%),600 (0.9%),700 (0.9%),881 (1.0%),1097 (1.1%)
COPIAPO,922 (0.9%),849 (1.3%),757 (1.1%),734 (0.9%),863 (1.0%),967 (1.0%)
MAGALLANES,945 (1.0%),587 (0.9%),675 (1.0%),813 (1.0%),962 (1.1%),1039 (1.0%)
COLCHAGUA,867 (0.9%),656 (1.0%),663 (1.0%),886 (1.1%),906 (1.0%),954 (1.0%)
ARAUCO,790 (0.8%),668 (1.0%),762 (1.1%),801 (1.0%),936 (1.0%),888 (0.9%)
LIMARI,845 (0.9%),568 (0.9%),708 (1.0%),820 (1.1%),869 (1.0%),876 (0.9%)
EL LOA,799 (0.8%),563 (0.9%),496 (0.7%),645 (0.8%),900 (1.0%),1019 (1.0%)
LOS ANDES,853 (0.9%),510 (0.8%),601 (0.9%),625 (0.8%),663 (0.7%),807 (0.8%)
PUNILLA,297 (0.3%),429 (0.7%),598 (0.9%),679 (0.9%),769 (0.8%),886 (0.9%)
CHILOE,692 (0.7%),526 (0.8%),516 (0.8%),529 (0.7%),588 (0.6%),663 (0.7%)
RANCO,490 (0.5%),324 (0.5%),350 (0.5%),326 (0.4%),425 (0.5%),415 (0.4%)
HUASCO,371 (0.4%),315 (0.5%),302 (0.4%),393 (0.5%),428 (0.5%),512 (0.5%)
COIHAIQUE,337 (0.3%),349 (0.5%),346 (0.5%),348 (0.4%),371 (0.4%),407 (0.4%)
CHACABUCO,279 (0.3%),228 (0.4%),283 (0.4%),359 (0.5%),390 (0.4%),435 (0.4%)
PETORCA,488 (0.5%),220 (0.3%),206 (0.3%),244 (0.3%),332 (0.4%),313 (0.3%)
CAUQUENES,330 (0.3%),192 (0.3%),173 (0.3%),200 (0.3%),225 (0.2%),501 (0.5%)
CHOAPA,318 (0.3%),133 (0.2%),192 (0.3%),244 (0.3%),292 (0.3%),279 (0.3%)
ITATA,194 (0.2%),172 (0.3%),203 (0.3%),210 (0.3%),280 (0.3%),337 (0.3%)
CARDENAL CARO,164 (0.2%),92 (0.1%),131 (0.2%),166 (0.2%),165 (0.2%),210 (0.2%)
TOCOPILLA,196 (0.2%),135 (0.2%),105 (0.2%),136 (0.2%),146 (0.2%),176 (0.2%)
AISEN,139 (0.1%),106 (0.2%),100 (0.1%),133 (0.2%),126 (0.1%),153 (0.2%)
PALENA,86 (0.1%),76 (0.1%),54 (0.1%),95 (0.1%),92 (0.1%),105 (0.1%)
CHANARAL,105 (0.1%),82 (0.1%),85 (0.1%),86 (0.1%),76 (0.1%),73 (0.1%)
ULTIMA ESPERANZA,91 (0.1%),53 (0.1%),69 (0.1%),76 (0.1%),86 (0.1%),83 (0.1%)
TAMARUGAL,41 (0.0%),94 (0.1%),39 (0.1%),52 (0.1%),79 (0.1%),109 (0.1%)
NUBLE,314 (0.3%),99 (0.2%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
GENERAL CARRERA,25 (0.0%),42 (0.1%),34 (0.1%),48 (0.1%),34 (0.0%),38 (0.0%)
ISLA DE PASCUA,27 (0.0%),15 (0.0%),31 (0.0%),19 (0.0%),36 (0.0%),33 (0.0%)
TIERRA DEL FUEGO,22 (0.0%),19 (0.0%),27 (0.0%),29 (0.0%),21 (0.0%),13 (0.0%)
CAPITAN PRAT,21 (0.0%),15 (0.0%),6 (0.0%),21 (0.0%),11 (0.0%),36 (0.0%)
DESCONOCIDO,21 (0.0%),17 (0.0%),0 (0.0%),3 (0.0%),20 (0.0%),42 (0.0%)
ANTARTICA CHILENA,5 (0.0%),1 (0.0%),4 (0.0%),0 (0.0%),1 (0.0%),3 (0.0%)
PARINACOTA,1 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROVINCIA):'

,2019,2020,2021,2022,2023,2024
SANTIAGO,265814 (25.2%),187652 (26.2%),188547 (25.2%),212685 (24.9%),225367 (23.8%),224551 (22.8%)
CONCEPCION,60377 (5.7%),38946 (5.4%),42492 (5.7%),48959 (5.7%),62541 (6.6%),69455 (7.0%)
CAUTIN,53383 (5.1%),36982 (5.2%),35314 (4.7%),38266 (4.5%),43020 (4.5%),53842 (5.5%)
CORDILLERA,41253 (3.9%),29011 (4.0%),33432 (4.5%),35743 (4.2%),37216 (3.9%),37208 (3.8%)
VALPARAISO,55405 (5.3%),25230 (3.5%),25937 (3.5%),29940 (3.5%),37922 (4.0%),39195 (4.0%)
ELQUI,32554 (3.1%),22901 (3.2%),25081 (3.3%),27386 (3.2%),33558 (3.5%),34495 (3.5%)
BIO-BIO,31831 (3.0%),20941 (2.9%),21494 (2.9%),27203 (3.2%),29326 (3.1%),28485 (2.9%)
CACHAPOAL,29088 (2.8%),20062 (2.8%),20287 (2.7%),22863 (2.7%),23467 (2.5%),24642 (2.5%)
LLANQUIHUE,26502 (2.5%),18650 (2.6%),19734 (2.6%),21685 (2.5%),25361 (2.7%),26576 (2.7%)
TALCA,24989 (2.4%),19199 (2.7%),19088 (2.5%),22606 (2.6%),23915 (2.5%),28360 (2.9%)
MAIPO,23424 (2.2%),16166 (2.3%),18723 (2.5%),22225 (2.6%),22569 (2.4%),23075 (2.3%)
LINARES,23017 (2.2%),16421 (2.3%),17370 (2.3%),20229 (2.4%),21656 (2.3%),21422 (2.2%)
DIGUILLIN,20901 (2.0%),13803 (1.9%),15347 (2.0%),18201 (2.1%),19742 (2.1%),19975 (2.0%)
IQUIQUE,20216 (1.9%),15292 (2.1%),16058 (2.1%),17516 (2.0%),18466 (1.9%),17885 (1.8%)
MALLECO,18822 (1.8%),12631 (1.8%),15214 (2.0%),18272 (2.1%),19257 (2.0%),19868 (2.0%)
ANTOFAGASTA,18981 (1.8%),15051 (2.1%),16672 (2.2%),17123 (2.0%),16943 (1.8%),18483 (1.9%)
CURICO,20921 (2.0%),13619 (1.9%),12992 (1.7%),16642 (1.9%),18286 (1.9%),20684 (2.1%)
ARICA,18714 (1.8%),14100 (2.0%),15725 (2.1%),17046 (2.0%),18208 (1.9%),18463 (1.9%)
OSORNO,19848 (1.9%),13448 (1.9%),13489 (1.8%),15901 (1.9%),17699 (1.9%),18356 (1.9%)
VALDIVIA,18670 (1.8%),12091 (1.7%),12519 (1.7%),14791 (1.7%),18226 (1.9%),17679 (1.8%)
COLCHAGUA,16857 (1.6%),10757 (1.5%),11508 (1.5%),14458 (1.7%),14678 (1.5%),14554 (1.5%)
TALAGANTE,13338 (1.3%),9120 (1.3%),9603 (1.3%),11136 (1.3%),13451 (1.4%),13346 (1.4%)
MARGA MARGA,16497 (1.6%),8971 (1.3%),9071 (1.2%),10347 (1.2%),12123 (1.3%),12820 (1.3%)
COPIAPO,12777 (1.2%),9569 (1.3%),10496 (1.4%),10839 (1.3%),11945 (1.3%),12864 (1.3%)
SAN FELIPE,13081 (1.2%),9234 (1.3%),8952 (1.2%),10497 (1.2%),11898 (1.3%),12324 (1.2%)
MELIPILLA,11027 (1.0%),8334 (1.2%),8871 (1.2%),10979 (1.3%),12553 (1.3%),13899 (1.4%)
LIMARI,13675 (1.3%),8107 (1.1%),8458 (1.1%),11106 (1.3%),12412 (1.3%),11418 (1.2%)
EL LOA,10043 (1.0%),8960 (1.2%),9470 (1.3%),10765 (1.3%),11656 (1.2%),11087 (1.1%)
MAGALLANES,11455 (1.1%),7674 (1.1%),8994 (1.2%),9846 (1.2%),11384 (1.2%),11569 (1.2%)
SAN ANTONIO,10989 (1.0%),6853 (1.0%),8193 (1.1%),9261 (1.1%),10965 (1.2%),11375 (1.2%)
QUILLOTA,11042 (1.0%),7373 (1.0%),7423 (1.0%),8119 (0.9%),11587 (1.2%),11653 (1.2%)
CHILOE,10926 (1.0%),6502 (0.9%),6959 (0.9%),8448 (1.0%),8803 (0.9%),8790 (0.9%)
CHACABUCO,8925 (0.8%),5920 (0.8%),7443 (1.0%),8819 (1.0%),9641 (1.0%),9499 (1.0%)
ARAUCO,9702 (0.9%),6852 (1.0%),6686 (0.9%),8170 (1.0%),9140 (1.0%),9002 (0.9%)
LOS ANDES,9043 (0.9%),6481 (0.9%),6484 (0.9%),7174 (0.8%),8118 (0.9%),8501 (0.9%)
PUNILLA,2792 (0.3%),4672 (0.7%),6954 (0.9%),8158 (1.0%),9015 (1.0%),9781 (1.0%)
COIHAIQUE,7169 (0.7%),5183 (0.7%),5059 (0.7%),5824 (0.7%),6987 (0.7%),7163 (0.7%)
HUASCO,5942 (0.6%),4471 (0.6%),4683 (0.6%),5647 (0.7%),6373 (0.7%),6398 (0.6%)
RANCO,4067 (0.4%),2650 (0.4%),2689 (0.4%),2865 (0.3%),3659 (0.4%),3506 (0.4%)
PETORCA,3279 (0.3%),2134 (0.3%),2115 (0.3%),2153 (0.3%),3053 (0.3%),3265 (0.3%)
ITATA,2043 (0.2%),1779 (0.2%),2240 (0.3%),2495 (0.3%),2768 (0.3%),2857 (0.3%)
CARDENAL CARO,2701 (0.3%),1713 (0.2%),1994 (0.3%),2410 (0.3%),2493 (0.3%),2530 (0.3%)
CAUQUENES,1512 (0.1%),1036 (0.1%),1069 (0.1%),1360 (0.2%),1477 (0.2%),5887 (0.6%)
NUBLE,8494 (0.8%),2333 (0.3%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
AISEN,1882 (0.2%),1551 (0.2%),1570 (0.2%),1638 (0.2%),1852 (0.2%),1904 (0.2%)
CHOAPA,2088 (0.2%),975 (0.1%),1198 (0.2%),1423 (0.2%),1611 (0.2%),1692 (0.2%)
TAMARUGAL,1464 (0.1%),1192 (0.2%),1180 (0.2%),1101 (0.1%),1224 (0.1%),1197 (0.1%)
CHANARAL,964 (0.1%),923 (0.1%),935 (0.1%),990 (0.1%),1111 (0.1%),848 (0.1%)
TOCOPILLA,1140 (0.1%),752 (0.1%),844 (0.1%),844 (0.1%),914 (0.1%),1009 (0.1%)
PALENA,847 (0.1%),653 (0.1%),671 (0.1%),762 (0.1%),885 (0.1%),914 (0.1%)
ULTIMA ESPERANZA,903 (0.1%),510 (0.1%),618 (0.1%),652 (0.1%),744 (0.1%),648 (0.1%)
GENERAL CARRERA,486 (0.0%),308 (0.0%),358 (0.0%),438 (0.1%),512 (0.1%),528 (0.1%)
DESCONOCIDO,804 (0.1%),610 (0.1%),40 (0.0%),40 (0.0%),260 (0.0%),351 (0.0%)
TIERRA DEL FUEGO,375 (0.0%),263 (0.0%),295 (0.0%),256 (0.0%),257 (0.0%),251 (0.0%)
CAPITAN PRAT,258 (0.0%),200 (0.0%),202 (0.0%),258 (0.0%),335 (0.0%),312 (0.0%)
ISLA DE PASCUA,199 (0.0%),104 (0.0%),98 (0.0%),170 (0.0%),179 (0.0%),157 (0.0%)
ANTARTICA CHILENA,70 (0.0%),48 (0.0%),37 (0.0%),35 (0.0%),53 (0.0%),56 (0.0%)
PARINACOTA,3 (0.0%),22 (0.0%),8 (0.0%),3 (0.0%),11 (0.0%),6 (0.0%)

### **6. Comuna de Residencia (COMUNA)**
- **Tipo de variable**: Demográfica / Geográfica.
- **Descripción**: Comuna específica donde el paciente tiene registrado su domicilio.
- **Cardinalidad**: Muy Alta (346 categorías únicas).
- **Veredicto**: **Descartar**. La alta fragmentación de la variable genera una matriz excesivamente dispersa (la comuna más frecuente, Puente Alto, apenas representa el ~4% del volumen total, dejando cientos de categorías con frecuencias cercanas a cero). Aplicar *One-Hot Encoding* inyectaría 346 nuevas columnas al modelo, diluyendo el peso de variables clínicas críticas e incrementando el riesgo de sobreajuste. Dado que la distribución territorial y el impacto del traslado ya están contenidos en variables más robustas y agrupadas como `PROVINCIA` y `SERVICIO_SALUD`, la eliminación de la comuna no sacrifica información espacial relevante a nivel macro.

In [9]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"COMUNA")
mostrar_resultados(total, oncologico, control, "COMUNA")

[COMUNA] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad COMUNA: 346 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (COMUNA):'

,2019,2020,2021,2022,2023,2024
PUENTE ALTO,45411 (3.9%),30473 (3.9%),35432 (4.3%),38233 (4.1%),39464 (3.8%),39492 (3.6%)
LA FLORIDA,23608 (2.1%),17332 (2.2%),19817 (2.4%),22517 (2.4%),23926 (2.3%),21818 (2.0%)
MAIPU,27907 (2.4%),18201 (2.3%),18156 (2.2%),19694 (2.1%),21427 (2.1%),21493 (2.0%)
VALPARAISO,36422 (3.2%),13957 (1.8%),15093 (1.8%),17299 (1.9%),20424 (2.0%),20756 (1.9%)
ARICA,20451 (1.8%),15556 (2.0%),17103 (2.1%),18508 (2.0%),19968 (1.9%),20352 (1.9%)
...,...,...,...,...,...,...
GENERAL LAGOS,1 (0.0%),3 (0.0%),1 (0.0%),0 (0.0%),8 (0.0%),4 (0.0%)
PUTRE,3 (0.0%),0 (0.0%),2 (0.0%),2 (0.0%),5 (0.0%),4 (0.0%)
TORRES DEL PAINE,7 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),5 (0.0%),0 (0.0%)
CAMARONES,0 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%),2 (0.0%),9 (0.0%)
TIMAUKEL,1 (0.0%),2 (0.0%),2 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (COMUNA):'

,2019,2020,2021,2022,2023,2024
PUENTE ALTO,6491 (6.6%),3095 (4.8%),3738 (5.5%),4277 (5.5%),4447 (4.9%),4715 (4.8%)
VALPARAISO,4828 (4.9%),1810 (2.8%),1582 (2.3%),1969 (2.5%),2471 (2.7%),2569 (2.6%)
LA FLORIDA,3056 (3.1%),1657 (2.6%),2029 (3.0%),2008 (2.6%),2253 (2.5%),2154 (2.2%)
MAIPU,2597 (2.7%),1859 (2.9%),1491 (2.2%),1960 (2.5%),2350 (2.6%),2445 (2.5%)
ANTOFAGASTA,2210 (2.3%),1612 (2.5%),1491 (2.2%),1648 (2.1%),1910 (2.1%),2179 (2.2%)
...,...,...,...,...,...,...
LAGUNA BLANCA,0 (0.0%),1 (0.0%),3 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
GENERAL LAGOS,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
RIO VERDE,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OLLAGUE,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
TIMAUKEL,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (COMUNA):'

,2019,2020,2021,2022,2023,2024
PUENTE ALTO,38920 (3.7%),27378 (3.8%),31694 (4.2%),33956 (4.0%),35017 (3.7%),34777 (3.5%)
LA FLORIDA,20552 (2.0%),15675 (2.2%),17788 (2.4%),20509 (2.4%),21673 (2.3%),19664 (2.0%)
MAIPU,25310 (2.4%),16342 (2.3%),16665 (2.2%),17734 (2.1%),19077 (2.0%),19048 (1.9%)
VALPARAISO,31594 (3.0%),12147 (1.7%),13511 (1.8%),15330 (1.8%),17953 (1.9%),18187 (1.8%)
ARICA,18693 (1.8%),14102 (2.0%),15728 (2.1%),17048 (2.0%),18207 (1.9%),18453 (1.9%)
...,...,...,...,...,...,...
PUTRE,3 (0.0%),0 (0.0%),2 (0.0%),2 (0.0%),5 (0.0%),4 (0.0%)
TORRES DEL PAINE,7 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),5 (0.0%),0 (0.0%)
GENERAL LAGOS,0 (0.0%),3 (0.0%),1 (0.0%),0 (0.0%),7 (0.0%),3 (0.0%)
CAMARONES,0 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%),2 (0.0%),9 (0.0%)
TIMAUKEL,1 (0.0%),2 (0.0%),1 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%)

### **7. Nacionalidad (NACIONALIDAD)**
- **Tipo de variable**: Demográfica.
- **Descripción**: País de origen o nacionalidad del paciente.
- **Cardinalidad**: Alta (214 categorías únicas reportadas, con errores de registro continental).
- **Veredicto**: **Transformar y Binarizar (`ES_CHILENO`)**. El análisis de frecuencias demuestra una varianza mínima extendida a lo largo de más de 200 categorías, donde la categoría "CHILE" acapara entre el 94% y 97% de los episodios hospitalarios. Para evitar la dispersión de datos y rescatar el valor sociológico de esta variable (la condición de migrante suele estar asociada a barreras de acceso, diagnósticos tardíos o diferencias en el consumo de recursos), se transformará en una variable dicotómica: `1` (Chileno) y `0` (Extranjero). Esta binarización condensa el impacto epidemiológico de la migración sin castigar a los selectores de características.

In [10]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"NACIONALIDAD")
mostrar_resultados(total, oncologico, control, "NACIONALIDAD")

[NACIONALIDAD] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad NACIONALIDAD: 214 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (NACIONALIDAD):'

,2019,2020,2021,2022,2023,2024
CHILE,1086008 (94.3%),739048 (94.5%),769125 (94.2%),872642 (93.5%),975501 (93.8%),1019656 (93.9%)
VENEZUELA (REPUBLICA BOLIVARIANA DE),11625 (1.0%),10556 (1.4%),15055 (1.8%),22130 (2.4%),24510 (2.4%),24788 (2.3%)
PERU,7390 (0.6%),6916 (0.9%),8092 (1.0%),9297 (1.0%),9891 (1.0%),10428 (1.0%)
BOLIVIA (ESTADO PLURINACIONAL DE),5548 (0.5%),5689 (0.7%),7174 (0.9%),9497 (1.0%),10636 (1.0%),11680 (1.1%)
HAITI,11380 (1.0%),8804 (1.1%),8366 (1.0%),7589 (0.8%),5444 (0.5%),4383 (0.4%)
...,...,...,...,...,...,...
SEYCHELLES,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
TANZANIA (REPUBLICA UNIDA DE),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
SINGAPUR,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
TURKMENISTAN,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
TUNEZ,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (NACIONALIDAD):'

,2019,2020,2021,2022,2023,2024
CHILE,95325 (97.4%),63311 (97.5%),66099 (97.3%),75702 (97.0%),87576 (96.5%),95468 (96.3%)
VENEZUELA (REPUBLICA BOLIVARIANA DE),548 (0.6%),537 (0.8%),765 (1.1%),1027 (1.3%),1278 (1.4%),1651 (1.7%)
PERU,273 (0.3%),301 (0.5%),324 (0.5%),429 (0.5%),612 (0.7%),649 (0.7%)
COLOMBIA,168 (0.2%),187 (0.3%),198 (0.3%),273 (0.3%),440 (0.5%),426 (0.4%)
BOLIVIA (ESTADO PLURINACIONAL DE),217 (0.2%),155 (0.2%),219 (0.3%),232 (0.3%),311 (0.3%),427 (0.4%)
...,...,...,...,...,...,...
SANTA SEDE,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
TERRITORIO BRITANICO DEL OCEANO INDICO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
TURQUIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
VIETNAM,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
YUGOSLAVIA,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (NACIONALIDAD):'

,2019,2020,2021,2022,2023,2024
CHILE,990683 (94.0%),675737 (94.2%),703026 (93.9%),796940 (93.2%),887925 (93.6%),924188 (93.7%)
VENEZUELA (REPUBLICA BOLIVARIANA DE),11077 (1.1%),10019 (1.4%),14290 (1.9%),21103 (2.5%),23232 (2.4%),23137 (2.3%)
PERU,7117 (0.7%),6615 (0.9%),7768 (1.0%),8868 (1.0%),9279 (1.0%),9779 (1.0%)
BOLIVIA (ESTADO PLURINACIONAL DE),5331 (0.5%),5534 (0.8%),6955 (0.9%),9265 (1.1%),10325 (1.1%),11253 (1.1%)
HAITI,11267 (1.1%),8734 (1.2%),8301 (1.1%),7486 (0.9%),5360 (0.6%),4256 (0.4%)
...,...,...,...,...,...,...
SEYCHELLES,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
TANZANIA (REPUBLICA UNIDA DE),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
SINGAPUR,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
TURKMENISTAN,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
TUNEZ,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **8. Previsión de Salud (PREVISION)**
- **Tipo de variable**: Demográfica / Socioeconómica.
- **Descripción**: Sistema de aseguramiento de salud al que está adscrito el paciente al momento del egreso.
- **Cardinalidad**: Moderada (14 categorías, con redundancias semánticas).
- **Veredicto**: **Retener y Agrupar**. Esta variable es el *proxy* (indicador indirecto) más robusto del nivel socioeconómico del paciente en el sistema chileno. Sin embargo, requiere una agrupación para reducir el ruido. Se consolidará en **7 macrocategorías funcionales**: los 4 tramos institucionales de riesgo socioeconómico (`FONASA A` [indigencia], `FONASA B`, `FONASA C`, `FONASA D` [mayor ingreso]), consolidando dentro de ellas sus respectivas modalidades de Libre Elección (FMLE); un grupo privado (`ISAPRE` y `PARTICULAR`, agrupados por representar pacientes fuera de la red pública habitual); un grupo de Fuerzas Armadas (`DIPRECA`, `CAPREDENA`, `SISA` -> `FFAA_Y_ORDEN`); y finalmente una categoría `DESCONOCIDO` (que absorberá nulos y "NO IDENTIFICADA").

In [11]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"PREVISION")
mostrar_resultados(total, oncologico, control, "PREVISION")

[PREVISION] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PREVISION: 14 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PREVISION):'

,2019,2020,2021,2022,2023,2024
FONASA INSTITUCIONAL - (MAI) B,489103 (42.5%),347393 (44.4%),376291 (46.1%),439654 (47.1%),496115 (47.7%),529210 (48.7%)
FONASA INSTITUCIONAL - (MAI) A,308865 (26.8%),199295 (25.5%),195516 (23.9%),217676 (23.3%),229289 (22.1%),225893 (20.8%)
FONASA INSTITUCIONAL - (MAI) D,157463 (13.7%),110474 (14.1%),118309 (14.5%),129793 (13.9%),150708 (14.5%),159612 (14.7%)
FONASA INSTITUCIONAL - (MAI) C,127890 (11.1%),93205 (11.9%),98673 (12.1%),109294 (11.7%),130039 (12.5%),139120 (12.8%)
FONASA LIBRE ELECCION (FMLE_B),16092 (1.4%),6197 (0.8%),5566 (0.7%),9304 (1.0%),9741 (0.9%),9728 (0.9%)
ISAPRE,11364 (1.0%),7862 (1.0%),7500 (0.9%),7471 (0.8%),6482 (0.6%),5816 (0.5%)
PARTICULAR,15088 (1.3%),6500 (0.8%),6180 (0.8%),7553 (0.8%),5141 (0.5%),3533 (0.3%)
FONASA LIBRE ELECCION (FMLE_D),11219 (1.0%),4523 (0.6%),3651 (0.4%),5781 (0.6%),5496 (0.5%),5968 (0.5%)
FONASA LIBRE ELECCION (FMLE_C),6279 (0.5%),2128 (0.3%),1816 (0.2%),2782 (0.3%),2892 (0.3%),2963 (0.3%)
DIPRECA,1749 (0.2%),1823 (0.2%),1957 (0.2%),2228 (0.2%),2436 (0.2%),2595 (0.2%)
CAPREDENA,1318 (0.1%),937 (0.1%),882 (0.1%),704 (0.1%),765 (0.1%),826 (0.1%)
NO IDENTIFICADA,3525 (0.3%),876 (0.1%),4 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
CAJA DE PREVISION FFAA (SISA),934 (0.1%),571 (0.1%),559 (0.1%),538 (0.1%),459 (0.0%),510 (0.0%)
NO CONSIGNADO,489 (0.0%),127 (0.0%),5 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,20 (0.0%),0 (0.0%),0 (0.0%),59 (0.0%),24 (0.0%),39 (0.0%)

'2. Frecuencia para cohorte oncológica (PREVISION):'

,2019,2020,2021,2022,2023,2024
FONASA INSTITUCIONAL - (MAI) B,51366 (52.5%),35791 (55.1%),38243 (56.3%),45631 (58.4%),53563 (59.0%),59177 (59.7%)
FONASA INSTITUCIONAL - (MAI) A,18228 (18.6%),11893 (18.3%),11329 (16.7%),12460 (16.0%),13060 (14.4%),12598 (12.7%)
FONASA INSTITUCIONAL - (MAI) D,15527 (15.9%),9436 (14.5%),9812 (14.4%),10734 (13.7%),12734 (14.0%),14243 (14.4%)
FONASA INSTITUCIONAL - (MAI) C,10801 (11.0%),6916 (10.7%),7878 (11.6%),8405 (10.8%),10509 (11.6%),12259 (12.4%)
ISAPRE,330 (0.3%),205 (0.3%),213 (0.3%),222 (0.3%),254 (0.3%),202 (0.2%)
FONASA LIBRE ELECCION (FMLE_B),459 (0.5%),128 (0.2%),80 (0.1%),139 (0.2%),161 (0.2%),196 (0.2%)
PARTICULAR,248 (0.3%),176 (0.3%),126 (0.2%),168 (0.2%),93 (0.1%),115 (0.1%)
DIPRECA,104 (0.1%),148 (0.2%),111 (0.2%),129 (0.2%),153 (0.2%),161 (0.2%)
FONASA LIBRE ELECCION (FMLE_D),218 (0.2%),66 (0.1%),35 (0.1%),58 (0.1%),76 (0.1%),63 (0.1%)
NO IDENTIFICADA,297 (0.3%),34 (0.1%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
CAPREDENA,71 (0.1%),44 (0.1%),47 (0.1%),48 (0.1%),56 (0.1%),61 (0.1%)
FONASA LIBRE ELECCION (FMLE_C),144 (0.1%),35 (0.1%),10 (0.0%),38 (0.0%),32 (0.0%),42 (0.0%)
CAJA DE PREVISION FFAA (SISA),36 (0.0%),45 (0.1%),38 (0.1%),31 (0.0%),24 (0.0%),33 (0.0%)
NO CONSIGNADO,0 (0.0%),9 (0.0%),3 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,0 (0.0%),0 (0.0%),0 (0.0%),6 (0.0%),0 (0.0%),3 (0.0%)

'3. Frecuencia para cohorte control (PREVISION):'

,2019,2020,2021,2022,2023,2024
FONASA INSTITUCIONAL - (MAI) B,437737 (41.5%),311602 (43.5%),338048 (45.1%),394023 (46.1%),442552 (46.6%),470033 (47.6%)
FONASA INSTITUCIONAL - (MAI) A,290637 (27.6%),187402 (26.1%),184187 (24.6%),205216 (24.0%),216229 (22.8%),213295 (21.6%)
FONASA INSTITUCIONAL - (MAI) D,141936 (13.5%),101038 (14.1%),108497 (14.5%),119059 (13.9%),137974 (14.5%),145369 (14.7%)
FONASA INSTITUCIONAL - (MAI) C,117089 (11.1%),86289 (12.0%),90795 (12.1%),100889 (11.8%),119530 (12.6%),126861 (12.9%)
FONASA LIBRE ELECCION (FMLE_B),15633 (1.5%),6069 (0.8%),5486 (0.7%),9165 (1.1%),9580 (1.0%),9532 (1.0%)
ISAPRE,11034 (1.0%),7657 (1.1%),7287 (1.0%),7249 (0.8%),6228 (0.7%),5614 (0.6%)
PARTICULAR,14840 (1.4%),6324 (0.9%),6054 (0.8%),7385 (0.9%),5048 (0.5%),3418 (0.3%)
FONASA LIBRE ELECCION (FMLE_D),11001 (1.0%),4457 (0.6%),3616 (0.5%),5723 (0.7%),5420 (0.6%),5905 (0.6%)
FONASA LIBRE ELECCION (FMLE_C),6135 (0.6%),2093 (0.3%),1806 (0.2%),2744 (0.3%),2860 (0.3%),2921 (0.3%)
DIPRECA,1645 (0.2%),1675 (0.2%),1846 (0.2%),2099 (0.2%),2283 (0.2%),2434 (0.2%)
CAPREDENA,1247 (0.1%),893 (0.1%),835 (0.1%),656 (0.1%),709 (0.1%),765 (0.1%)
NO IDENTIFICADA,3228 (0.3%),842 (0.1%),3 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
CAJA DE PREVISION FFAA (SISA),898 (0.1%),526 (0.1%),521 (0.1%),507 (0.1%),435 (0.0%),477 (0.0%)
NO CONSIGNADO,489 (0.0%),118 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,20 (0.0%),0 (0.0%),0 (0.0%),53 (0.0%),24 (0.0%),36 (0.0%)

### **9. Servicio de Salud (SERVICIO_SALUD)**
- **Tipo de variable**: Hospitalaria / Administrativa.
- **Descripción**: Red macro-zonal del sistema de salud público a la que pertenece o fue derivado el paciente.
- **Cardinalidad**: Manejable (31 categorías válidas).
- **Veredicto**: **Retener y Limpiar**. A diferencia de la comuna, 31 categorías representan una cardinalidad perfectamente asimilable por los selectores de características y los algoritmos basados en árboles. Esta variable es de suma importancia estratégica, ya que captura las asimetrías institucionales del país: diferencias de infraestructura, disponibilidad de centros oncológicos de referencia, presupuestos zonales y tiempos en listas de espera. Solo se aplicará una limpieza básica unificando las etiquetas anómalas (`NO APLICA`, `IGNORADO`) dentro de la categoría `DESCONOCIDO`.

In [12]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"SERVICIO_SALUD")
mostrar_resultados(total, oncologico, control, "SERVICIO_SALUD")

[SERVICIO_SALUD] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIO_SALUD: 31 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIO_SALUD):'

,2019,2020,2021,2022,2023,2024
METROPOLITANO SURORIENTE,100291 (8.7%),70122 (9.0%),79850 (9.8%),89304 (9.6%),93199 (9.0%),90733 (8.4%)
DEL MAULE,76222 (6.6%),54441 (7.0%),54716 (6.7%),65501 (7.0%),70645 (6.8%),82844 (7.6%)
METROPOLITANO OCCIDENTE,70647 (6.1%),48504 (6.2%),51165 (6.3%),61458 (6.6%),70997 (6.8%),73247 (6.7%)
METROPOLITANO SUR,66311 (5.8%),51253 (6.6%),51210 (6.3%),54863 (5.9%),55839 (5.4%),59892 (5.5%)
METROPOLITANO CENTRAL,65480 (5.7%),45189 (5.8%),43943 (5.4%),50325 (5.4%),54484 (5.2%),54335 (5.0%)
ARAUCANIA SUR,57754 (5.0%),40467 (5.2%),38203 (4.7%),41344 (4.4%),46871 (4.5%),58777 (5.4%)
COQUIMBO,51921 (4.5%),34611 (4.4%),37929 (4.6%),43628 (4.7%),52101 (5.0%),52366 (4.8%)
VINA DEL MAR QUILLOTA,59593 (5.2%),33626 (4.3%),32698 (4.0%),37432 (4.0%),50370 (4.8%),51940 (4.8%)
LIBERTADOR B. O HIGGINS,51731 (4.5%),35614 (4.6%),37340 (4.6%),43614 (4.7%),44749 (4.3%),45492 (4.2%)
METROPOLITANO ORIENTE,48966 (4.3%),32609 (4.2%),33731 (4.1%),37664 (4.0%),40669 (3.9%),40694 (3.7%)
CONCEPCION,41272 (3.6%),26433 (3.4%),29497 (3.6%),33103 (3.5%),42028 (4.0%),44824 (4.1%)
METROPOLITANO NORTE,47697 (4.1%),30657 (3.9%),30293 (3.7%),35553 (3.8%),36735 (3.5%),35811 (3.3%)
VALPARAISO SAN ANTONIO,51615 (4.5%),22339 (2.9%),24877 (3.0%),28519 (3.1%),33528 (3.2%),35056 (3.2%)
NUBLE,36594 (3.2%),24685 (3.2%),27063 (3.3%),31800 (3.4%),34588 (3.3%),36160 (3.3%)
ANTOFAGASTA,33457 (2.9%),27806 (3.6%),29552 (3.6%),31568 (3.4%),33026 (3.2%),34468 (3.2%)
BIOBIO,33944 (2.9%),22555 (2.9%),23385 (2.9%),29438 (3.2%),31634 (3.0%),30998 (2.9%)
DEL RELONCAVI,29584 (2.6%),21478 (2.7%),23034 (2.8%),25426 (2.7%),29449 (2.8%),30528 (2.8%)
TALCAHUANO,25248 (2.2%),16963 (2.2%),18149 (2.2%),21988 (2.4%),27850 (2.7%),33070 (3.0%)
VALDIVIA,25557 (2.2%),17039 (2.2%),17718 (2.2%),20148 (2.2%),24843 (2.4%),24390 (2.2%)
ACONCAGUA,24172 (2.1%),16876 (2.2%),16641 (2.0%),19146 (2.1%),21727 (2.1%),22867 (2.1%)
IQUIQUE,23152 (2.0%),17638 (2.3%),18334 (2.2%),19915 (2.1%),21127 (2.0%),20963 (1.9%)
ATACAMA,21070 (1.8%),15973 (2.0%),16931 (2.1%),18384 (2.0%),20335 (2.0%),21284 (2.0%)
ARICA,20424 (1.8%),15547 (2.0%),17044 (2.1%),18379 (2.0%),19887 (1.9%),20234 (1.9%)
ARAUCANIA NORTE,20004 (1.7%),13570 (1.7%),16216 (2.0%),19452 (2.1%),20671 (2.0%),21266 (2.0%)
OSORNO,22306 (1.9%),14744 (1.9%),14752 (1.8%),17248 (1.8%),19481 (1.9%),20314 (1.9%)
MAGALLANES,13864 (1.2%),9085 (1.2%),10605 (1.3%),11573 (1.2%),13383 (1.3%),13621 (1.3%)
AYSEN,10294 (0.9%),7649 (1.0%),7519 (0.9%),8542 (0.9%),10044 (1.0%),10307 (0.9%)
ARAUCO,10495 (0.9%),7506 (1.0%),7422 (0.9%),8971 (1.0%),9965 (1.0%),9649 (0.9%)
CHILOE,11634 (1.0%),6640 (0.8%),6612 (0.8%),8491 (0.9%),8621 (0.8%),9090 (0.8%)
DESCONOCIDO,3 (0.0%),2 (0.0%),0 (0.0%),60 (0.0%),741 (0.1%),593 (0.1%)
NO APLICA,7 (0.0%),202 (0.0%),403 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
IGNORADO,89 (0.0%),88 (0.0%),77 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIO_SALUD):'

,2019,2020,2021,2022,2023,2024
METROPOLITANO SURORIENTE,12838 (13.1%),6619 (10.2%),7923 (11.7%),8736 (11.2%),9363 (10.3%),9573 (9.7%)
METROPOLITANO OCCIDENTE,5752 (5.9%),4041 (6.2%),5104 (7.5%),5911 (7.6%),6750 (7.4%),6961 (7.0%)
DEL MAULE,5802 (5.9%),4334 (6.7%),4448 (6.5%),5060 (6.5%),5618 (6.2%),6545 (6.6%)
METROPOLITANO CENTRAL,5744 (5.9%),4154 (6.4%),3407 (5.0%),4488 (5.7%),5472 (6.0%),5703 (5.8%)
VINA DEL MAR QUILLOTA,7342 (7.5%),2940 (4.5%),2505 (3.7%),3286 (4.2%),4720 (5.2%),4910 (5.0%)
CONCEPCION,4103 (4.2%),3143 (4.8%),3497 (5.1%),4008 (5.1%),4864 (5.4%),5306 (5.4%)
METROPOLITANO ORIENTE,4685 (4.8%),2957 (4.6%),3310 (4.9%),3852 (4.9%),4569 (5.0%),4948 (5.0%)
ARAUCANIA SUR,4448 (4.5%),3465 (5.3%),3150 (4.6%),3275 (4.2%),4055 (4.5%),5190 (5.2%)
METROPOLITANO SUR,4207 (4.3%),3431 (5.3%),3409 (5.0%),3674 (4.7%),4037 (4.5%),4537 (4.6%)
VALPARAISO SAN ANTONIO,6662 (6.8%),2476 (3.8%),2377 (3.5%),2854 (3.7%),3554 (3.9%),3872 (3.9%)
COQUIMBO,3488 (3.6%),2578 (4.0%),2994 (4.4%),3430 (4.4%),4143 (4.6%),4441 (4.5%)
LIBERTADOR B. O HIGGINS,3067 (3.1%),2606 (4.0%),2721 (4.0%),3210 (4.1%),3368 (3.7%),3527 (3.6%)
ANTOFAGASTA,3317 (3.4%),2553 (3.9%),2392 (3.5%),2714 (3.5%),3336 (3.7%),3717 (3.7%)
VALDIVIA,2703 (2.8%),2332 (3.6%),2593 (3.8%),2695 (3.5%),3213 (3.5%),3375 (3.4%)
NUBLE,2217 (2.3%),1816 (2.8%),2197 (3.2%),2548 (3.3%),2669 (2.9%),3274 (3.3%)
TALCAHUANO,2101 (2.1%),1433 (2.2%),1705 (2.5%),2128 (2.7%),2522 (2.8%),2976 (3.0%)
BIOBIO,2129 (2.2%),1525 (2.3%),1678 (2.5%),2270 (2.9%),2369 (2.6%),2612 (2.6%)
DEL RELONCAVI,2304 (2.4%),1848 (2.8%),1762 (2.6%),1821 (2.3%),2290 (2.5%),2400 (2.4%)
OSORNO,2357 (2.4%),1275 (2.0%),1318 (1.9%),1387 (1.8%),1635 (1.8%),1834 (1.8%)
ARICA,1759 (1.8%),1449 (2.2%),1356 (2.0%),1436 (1.8%),1734 (1.9%),1861 (1.9%)
METROPOLITANO NORTE,1780 (1.8%),1206 (1.9%),1360 (2.0%),1646 (2.1%),1676 (1.8%),1883 (1.9%)
ACONCAGUA,1995 (2.0%),1199 (1.8%),1197 (1.8%),1464 (1.9%),1646 (1.8%),1932 (1.9%)
IQUIQUE,1443 (1.5%),1217 (1.9%),1187 (1.7%),1325 (1.7%),1511 (1.7%),1939 (2.0%)
ARAUCANIA NORTE,1208 (1.2%),1021 (1.6%),1115 (1.6%),1224 (1.6%),1524 (1.7%),1418 (1.4%)
ATACAMA,1390 (1.4%),1106 (1.7%),1040 (1.5%),1141 (1.5%),1246 (1.4%),1451 (1.5%)
MAGALLANES,1049 (1.1%),643 (1.0%),721 (1.1%),872 (1.1%),1023 (1.1%),1102 (1.1%)
ARAUCO,791 (0.8%),661 (1.0%),765 (1.1%),800 (1.0%),927 (1.0%),857 (0.9%)
AYSEN,505 (0.5%),470 (0.7%),406 (0.6%),489 (0.6%),482 (0.5%),534 (0.5%)
CHILOE,639 (0.7%),409 (0.6%),271 (0.4%),323 (0.4%),365 (0.4%),441 (0.4%)
DESCONOCIDO,0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),34 (0.0%),34 (0.0%)
NO APLICA,0 (0.0%),12 (0.0%),13 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
IGNORADO,4 (0.0%),7 (0.0%),5 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SERVICIO_SALUD):'

,2019,2020,2021,2022,2023,2024
METROPOLITANO SURORIENTE,87453 (8.3%),63503 (8.9%),71927 (9.6%),80568 (9.4%),83836 (8.8%),81160 (8.2%)
DEL MAULE,70420 (6.7%),50107 (7.0%),50268 (6.7%),60441 (7.1%),65027 (6.9%),76299 (7.7%)
METROPOLITANO OCCIDENTE,64895 (6.2%),44463 (6.2%),46061 (6.1%),55547 (6.5%),64247 (6.8%),66286 (6.7%)
METROPOLITANO SUR,62104 (5.9%),47822 (6.7%),47801 (6.4%),51189 (6.0%),51802 (5.5%),55355 (5.6%)
METROPOLITANO CENTRAL,59736 (5.7%),41035 (5.7%),40536 (5.4%),45837 (5.4%),49012 (5.2%),48632 (4.9%)
ARAUCANIA SUR,53306 (5.1%),37002 (5.2%),35053 (4.7%),38069 (4.5%),42816 (4.5%),53587 (5.4%)
COQUIMBO,48433 (4.6%),32033 (4.5%),34935 (4.7%),40198 (4.7%),47958 (5.1%),47925 (4.9%)
LIBERTADOR B. O HIGGINS,48664 (4.6%),33008 (4.6%),34619 (4.6%),40404 (4.7%),41381 (4.4%),41965 (4.3%)
VINA DEL MAR QUILLOTA,52251 (5.0%),30686 (4.3%),30193 (4.0%),34146 (4.0%),45650 (4.8%),47030 (4.8%)
METROPOLITANO ORIENTE,44281 (4.2%),29652 (4.1%),30421 (4.1%),33812 (4.0%),36100 (3.8%),35746 (3.6%)
METROPOLITANO NORTE,45917 (4.4%),29451 (4.1%),28933 (3.9%),33907 (4.0%),35059 (3.7%),33928 (3.4%)
CONCEPCION,37169 (3.5%),23290 (3.2%),26000 (3.5%),29095 (3.4%),37164 (3.9%),39518 (4.0%)
NUBLE,34377 (3.3%),22869 (3.2%),24866 (3.3%),29252 (3.4%),31919 (3.4%),32886 (3.3%)
VALPARAISO SAN ANTONIO,44953 (4.3%),19863 (2.8%),22500 (3.0%),25665 (3.0%),29974 (3.2%),31184 (3.2%)
ANTOFAGASTA,30140 (2.9%),25253 (3.5%),27160 (3.6%),28854 (3.4%),29690 (3.1%),30751 (3.1%)
BIOBIO,31815 (3.0%),21030 (2.9%),21707 (2.9%),27168 (3.2%),29265 (3.1%),28386 (2.9%)
DEL RELONCAVI,27280 (2.6%),19630 (2.7%),21272 (2.8%),23605 (2.8%),27159 (2.9%),28128 (2.9%)
TALCAHUANO,23147 (2.2%),15530 (2.2%),16444 (2.2%),19860 (2.3%),25328 (2.7%),30094 (3.1%)
VALDIVIA,22854 (2.2%),14707 (2.1%),15125 (2.0%),17453 (2.0%),21630 (2.3%),21015 (2.1%)
IQUIQUE,21709 (2.1%),16421 (2.3%),17147 (2.3%),18590 (2.2%),19616 (2.1%),19024 (1.9%)
ACONCAGUA,22177 (2.1%),15677 (2.2%),15444 (2.1%),17682 (2.1%),20081 (2.1%),20935 (2.1%)
ATACAMA,19680 (1.9%),14867 (2.1%),15891 (2.1%),17243 (2.0%),19089 (2.0%),19833 (2.0%)
ARAUCANIA NORTE,18796 (1.8%),12549 (1.8%),15101 (2.0%),18228 (2.1%),19147 (2.0%),19848 (2.0%)
ARICA,18665 (1.8%),14098 (2.0%),15688 (2.1%),16943 (2.0%),18153 (1.9%),18373 (1.9%)
OSORNO,19949 (1.9%),13469 (1.9%),13434 (1.8%),15861 (1.9%),17846 (1.9%),18480 (1.9%)
MAGALLANES,12815 (1.2%),8442 (1.2%),9884 (1.3%),10701 (1.3%),12360 (1.3%),12519 (1.3%)
AYSEN,9789 (0.9%),7179 (1.0%),7113 (0.9%),8053 (0.9%),9562 (1.0%),9773 (1.0%)
ARAUCO,9704 (0.9%),6845 (1.0%),6657 (0.9%),8171 (1.0%),9038 (1.0%),8792 (0.9%)
CHILOE,10995 (1.0%),6231 (0.9%),6341 (0.8%),8168 (1.0%),8256 (0.9%),8649 (0.9%)
DESCONOCIDO,3 (0.0%),2 (0.0%),0 (0.0%),58 (0.0%),707 (0.1%),559 (0.1%)
NO APLICA,7 (0.0%),190 (0.0%),390 (0.1%),0 (0.0%),0 (0.0%),0 (0.0%)
IGNORADO,85 (0.0%),81 (0.0%),72 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **10. Tipo de procedencia (TIPO_PROCEDENCIA)**
- **Tipo de variable**: Hospitalaria / Administrativa.
- **Descripción**: Indica el origen físico o institucional del paciente inmediatamente antes de ingresar al hospital.
- **Cardinalidad**: Moderada (19 categorías únicas).
- **Veredicto**: **Retener y Agrupar**. El análisis revela un hallazgo estructural crítico para la caracterización: mientras que en el grupo control la mayoría ingresa desde el `SERVICIO DE EMERGENCIA` (~45-54%), el perfil oncológico es radicalmente distinto, proviniendo mayoritariamente de `CENTRO DE ESPECIALIDADES (CDT, CRS)` (~55-64%). Para optimizar su uso en los selectores de características, la variable se agrupará en 5 macro-categorías funcionales que reflejen la vía de acceso: *Atención Primaria / Ambulatoria*, *Urgencia*, *Derivación de Red Hospitalaria*, *Sector Privado* y *Otros*.

In [13]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"TIPO_PROCEDENCIA")
mostrar_resultados(total, oncologico, control, "TIPO_PROCEDENCIA")

[TIPO_PROCEDENCIA] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad TIPO_PROCEDENCIA: 19 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (TIPO_PROCEDENCIA):'

,2019,2020,2021,2022,2023,2024
SERVICIO EMERGENCIA (DOMICILIO),532216 (46.2%),410739 (52.5%),409190 (50.1%),436754 (46.8%),464982 (44.7%),475146 (43.8%)
"CENTRO ESPECIALIDADES (CDT, CRS, CONSULTORIO ADOS. ESP)",408511 (35.5%),206419 (26.4%),227889 (27.9%),282818 (30.3%),346334 (33.3%),369242 (34.0%)
OTROS HOSPITALES DE LA RED,71130 (6.2%),62884 (8.0%),63987 (7.8%),63660 (6.8%),71394 (6.9%),78041 (7.2%)
"APS URGENCIA (SAPU, SUR, SUC)",37707 (3.3%),36944 (4.7%),45545 (5.6%),44039 (4.7%),50490 (4.9%),56485 (5.2%)
CONSULTA PRIVADA,38950 (3.4%),16065 (2.1%),14804 (1.8%),22300 (2.4%),23209 (2.2%),23809 (2.2%)
APS CONSULTORIO (CESFAM),19926 (1.7%),15284 (2.0%),13841 (1.7%),12893 (1.4%),14612 (1.4%),15408 (1.4%)
"OTRAS INSTITUCIONES SALUD (CLINICAS PRIVADAS, DE REHABILITAC",13108 (1.1%),11589 (1.5%),13066 (1.6%),11555 (1.2%),11697 (1.1%),12267 (1.1%)
OTROS HOSPITALES RED NACIONAL,13647 (1.2%),10928 (1.4%),11475 (1.4%),10552 (1.1%),11783 (1.1%),11722 (1.1%)
PLAN DE RESOLUCION LE,0 (0.0%),0 (0.0%),0 (0.0%),31745 (3.4%),16937 (1.6%),57 (0.0%)
ESTRATEGIA CRR,0 (0.0%),0 (0.0%),0 (0.0%),3235 (0.3%),10423 (1.0%),22826 (2.1%)
CIRUGIA MAYOR AMBULATORIA (CMA),9658 (0.8%),4132 (0.5%),4760 (0.6%),4728 (0.5%),4662 (0.4%),5832 (0.5%)
"OTRAS INSTITUCIONES (CARCEL, HOGARES DE ANCIANOS, SENAME, EC",3068 (0.3%),3903 (0.5%),5858 (0.7%),3381 (0.4%),5503 (0.5%),6786 (0.6%)
HOSPITALIZACION DOMICILIARIA,1243 (0.1%),1591 (0.2%),2011 (0.2%),2249 (0.2%),2705 (0.3%),3230 (0.3%)
CARDIOCIRUGIA PAGO GRD,0 (0.0%),0 (0.0%),0 (0.0%),1474 (0.2%),3264 (0.3%),3013 (0.3%)
POSTA RURAL,1337 (0.1%),1155 (0.1%),1109 (0.1%),1077 (0.1%),1108 (0.1%),1333 (0.1%)
DESCONOCIDO,16 (0.0%),2 (0.0%),3084 (0.4%),2 (0.0%),2 (0.0%),5 (0.0%)
HOSPITALIZACION DIURNA,660 (0.1%),177 (0.0%),285 (0.0%),375 (0.0%),482 (0.0%),611 (0.1%)
NO IDENTIFICADO,221 (0.0%),93 (0.0%),5 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
LISTA DE ESPERA,0 (0.0%),5 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UGCC,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (TIPO_PROCEDENCIA):'

,2019,2020,2021,2022,2023,2024
"CENTRO ESPECIALIDADES (CDT, CRS, CONSULTORIO ADOS. ESP)",62367 (63.8%),34814 (53.6%),37940 (55.9%),43489 (55.7%),50023 (55.1%),54557 (55.0%)
SERVICIO EMERGENCIA (DOMICILIO),25581 (26.1%),21339 (32.9%),21105 (31.1%),23550 (30.2%),27719 (30.6%),29911 (30.2%)
OTROS HOSPITALES DE LA RED,3600 (3.7%),3407 (5.2%),3245 (4.8%),3435 (4.4%),4416 (4.9%),5175 (5.2%)
"APS URGENCIA (SAPU, SUR, SUC)",1515 (1.5%),1583 (2.4%),1861 (2.7%),2130 (2.7%),2414 (2.7%),3038 (3.1%)
OTROS HOSPITALES RED NACIONAL,1137 (1.2%),905 (1.4%),825 (1.2%),875 (1.1%),911 (1.0%),1034 (1.0%)
"OTRAS INSTITUCIONES SALUD (CLINICAS PRIVADAS, DE REHABILITAC",836 (0.9%),827 (1.3%),823 (1.2%),811 (1.0%),991 (1.1%),1030 (1.0%)
CONSULTA PRIVADA,1246 (1.3%),581 (0.9%),555 (0.8%),702 (0.9%),771 (0.8%),818 (0.8%)
APS CONSULTORIO (CESFAM),783 (0.8%),682 (1.1%),578 (0.9%),566 (0.7%),684 (0.8%),777 (0.8%)
"OTRAS INSTITUCIONES (CARCEL, HOGARES DE ANCIANOS, SENAME, EC",105 (0.1%),274 (0.4%),234 (0.3%),181 (0.2%),606 (0.7%),849 (0.9%)
PLAN DE RESOLUCION LE,0 (0.0%),0 (0.0%),0 (0.0%),1468 (1.9%),777 (0.9%),2 (0.0%)
CIRUGIA MAYOR AMBULATORIA (CMA),365 (0.4%),224 (0.3%),440 (0.6%),412 (0.5%),419 (0.5%),376 (0.4%)
HOSPITALIZACION DOMICILIARIA,113 (0.1%),163 (0.3%),212 (0.3%),257 (0.3%),345 (0.4%),518 (0.5%)
ESTRATEGIA CRR,0 (0.0%),0 (0.0%),0 (0.0%),99 (0.1%),499 (0.6%),880 (0.9%)
HOSPITALIZACION DIURNA,103 (0.1%),43 (0.1%),36 (0.1%),54 (0.1%),79 (0.1%),80 (0.1%)
POSTA RURAL,50 (0.1%),57 (0.1%),39 (0.1%),28 (0.0%),47 (0.1%),82 (0.1%)
NO IDENTIFICADO,28 (0.0%),25 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
CARDIOCIRUGIA PAGO GRD,0 (0.0%),0 (0.0%),0 (0.0%),12 (0.0%),14 (0.0%),26 (0.0%)
DESCONOCIDO,0 (0.0%),1 (0.0%),33 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
LISTA DE ESPERA,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (TIPO_PROCEDENCIA):'

,2019,2020,2021,2022,2023,2024
SERVICIO EMERGENCIA (DOMICILIO),506635 (48.1%),389400 (54.3%),388085 (51.8%),413204 (48.3%),437263 (46.1%),445235 (45.1%)
"CENTRO ESPECIALIDADES (CDT, CRS, CONSULTORIO ADOS. ESP)",346144 (32.9%),171605 (23.9%),189949 (25.4%),239329 (28.0%),296311 (31.2%),314685 (31.9%)
OTROS HOSPITALES DE LA RED,67530 (6.4%),59477 (8.3%),60742 (8.1%),60225 (7.0%),66978 (7.1%),72866 (7.4%)
"APS URGENCIA (SAPU, SUR, SUC)",36192 (3.4%),35361 (4.9%),43684 (5.8%),41909 (4.9%),48076 (5.1%),53447 (5.4%)
CONSULTA PRIVADA,37704 (3.6%),15484 (2.2%),14249 (1.9%),21598 (2.5%),22438 (2.4%),22991 (2.3%)
APS CONSULTORIO (CESFAM),19143 (1.8%),14602 (2.0%),13263 (1.8%),12327 (1.4%),13928 (1.5%),14631 (1.5%)
"OTRAS INSTITUCIONES SALUD (CLINICAS PRIVADAS, DE REHABILITAC",12272 (1.2%),10762 (1.5%),12243 (1.6%),10744 (1.3%),10706 (1.1%),11237 (1.1%)
OTROS HOSPITALES RED NACIONAL,12510 (1.2%),10023 (1.4%),10650 (1.4%),9677 (1.1%),10872 (1.1%),10688 (1.1%)
PLAN DE RESOLUCION LE,0 (0.0%),0 (0.0%),0 (0.0%),30277 (3.5%),16160 (1.7%),55 (0.0%)
ESTRATEGIA CRR,0 (0.0%),0 (0.0%),0 (0.0%),3136 (0.4%),9924 (1.0%),21946 (2.2%)
CIRUGIA MAYOR AMBULATORIA (CMA),9293 (0.9%),3908 (0.5%),4320 (0.6%),4316 (0.5%),4243 (0.4%),5456 (0.6%)
"OTRAS INSTITUCIONES (CARCEL, HOGARES DE ANCIANOS, SENAME, EC",2963 (0.3%),3629 (0.5%),5624 (0.8%),3200 (0.4%),4897 (0.5%),5937 (0.6%)
HOSPITALIZACION DOMICILIARIA,1130 (0.1%),1428 (0.2%),1799 (0.2%),1992 (0.2%),2360 (0.2%),2712 (0.3%)
CARDIOCIRUGIA PAGO GRD,0 (0.0%),0 (0.0%),0 (0.0%),1462 (0.2%),3250 (0.3%),2987 (0.3%)
POSTA RURAL,1287 (0.1%),1098 (0.2%),1070 (0.1%),1049 (0.1%),1061 (0.1%),1251 (0.1%)
DESCONOCIDO,16 (0.0%),1 (0.0%),3051 (0.4%),2 (0.0%),2 (0.0%),5 (0.0%)
HOSPITALIZACION DIURNA,557 (0.1%),134 (0.0%),249 (0.0%),321 (0.0%),403 (0.0%),531 (0.1%)
NO IDENTIFICADO,193 (0.0%),68 (0.0%),5 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
LISTA DE ESPERA,0 (0.0%),4 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UGCC,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **11. Tipo de ingreso (TIPO_INGRESO)**
- **Tipo de variable**: Hospitalaria / Administrativa.
- **Descripción**: Clasificación administrativa del ingreso del paciente al episodio asistencial.
- **Cardinalidad**: Baja (5 categorías únicas).
- **Veredicto**: **Retener**. Presenta una cardinalidad casi perfecta y expone otra diferencia epidemiológica fundamental: el ~56-65% de los ingresos oncológicos son `PROGRAMADOS`, en contraste directo con el grupo control, que está dominado por la `URGENCIA` (~48-57%). Se mantendrán las tres categorías principales (`URGENCIA`, `PROGRAMADA`, `OBSTETRICA`), y los valores anómalos o marginales (`NO PROGRAMADA`, `NO IDENTIFICADA`, `DESCONOCIDO`) se imputarán a la moda o se unificarán.

In [14]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"TIPO_INGRESO")
mostrar_resultados(total, oncologico, control, "TIPO_INGRESO")

[TIPO_INGRESO] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad TIPO_INGRESO: 5 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (TIPO_INGRESO):'

,2019,2020,2021,2022,2023,2024
URGENCIA,548049 (47.6%),432217 (55.3%),457702 (56.0%),468530 (50.2%),518634 (49.9%),552102 (50.8%)
PROGRAMADA,421644 (36.6%),199311 (25.5%),220715 (27.0%),307367 (32.9%),366371 (35.2%),388739 (35.8%)
OBSTETRICA,181372 (15.8%),150360 (19.2%),138491 (17.0%),156907 (16.8%),154527 (14.9%),144929 (13.3%)
NO IDENTIFICADA,299 (0.0%),18 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,14 (0.0%),0 (0.0%),0 (0.0%),33 (0.0%),55 (0.0%),43 (0.0%)
NO PROGRAMADA,20 (0.0%),5 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (TIPO_INGRESO):'

,2019,2020,2021,2022,2023,2024
PROGRAMADA,63995 (65.4%),36431 (56.1%),38187 (56.2%),45085 (57.8%),52206 (57.5%),55746 (56.2%)
URGENCIA,33623 (34.4%),28275 (43.5%),29540 (43.5%),32677 (41.9%),38203 (42.1%),43027 (43.4%)
OBSTETRICA,197 (0.2%),220 (0.3%),199 (0.3%),302 (0.4%),305 (0.3%),371 (0.4%)
DESCONOCIDO,0 (0.0%),0 (0.0%),0 (0.0%),5 (0.0%),1 (0.0%),9 (0.0%)
NO IDENTIFICADA,14 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (TIPO_INGRESO):'

,2019,2020,2021,2022,2023,2024
URGENCIA,514426 (48.8%),403942 (56.3%),428162 (57.2%),435853 (51.0%),480431 (50.6%),509075 (51.6%)
PROGRAMADA,357649 (33.9%),162880 (22.7%),182528 (24.4%),262282 (30.7%),314165 (33.1%),332993 (33.7%)
OBSTETRICA,181175 (17.2%),150140 (20.9%),138292 (18.5%),156605 (18.3%),154222 (16.3%),144558 (14.7%)
NO IDENTIFICADA,285 (0.0%),18 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,14 (0.0%),0 (0.0%),0 (0.0%),28 (0.0%),54 (0.0%),34 (0.0%)
NO PROGRAMADA,20 (0.0%),5 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **12. Especialidad Médica (ESPECIALIDAD_MEDICA)**
- **Tipo de variable**: Clínica / Hospitalaria.
- **Descripción**: Especialidad médica principal encargada del tratamiento del paciente durante su episodio.
- **Cardinalidad**: Alta (103 categorías únicas, afectadas por cambios de nomenclatura).
- **Veredicto**: **Retener, Limpiar y Agrupar**. Dado que el estudio es de caracterización retrospectiva y no predictivo-prospectivo, no existe riesgo de fuga de información (*Data Leakage*). La alta cardinalidad (103) se debe principalmente a errores tipográficos y saltos en la codificación del MINSAL a partir de 2020 (ej. `CIRUGIA TORAX` vs. `CIRUGIA DE TORAX`). Se desarrollará un diccionario de homologación para fusionar las especialidades equivalentes y condensarlas en ~12 macro-especialidades (ej. *Cirugía*, *Medicina Interna*, *Oncología*, *Ginecología y Obstetricia*), estabilizando la variable para su análisis mediante *Bootstrapping*.

In [15]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"ESPECIALIDAD_MEDICA")
mostrar_resultados(total, oncologico, control, "ESPECIALIDAD_MEDICA")

[ESPECIALIDAD_MEDICA] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad ESPECIALIDAD_MEDICA: 103 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (ESPECIALIDAD_MEDICA):'

,2019,2020,2021,2022,2023,2024
OBSTETRICIA Y GINECOLOGIA,234462 (20.4%),179958 (23.0%),173148 (21.2%),202672 (21.7%),208926 (20.1%),205359 (18.9%)
CIRUGIA GENERAL,185431 (16.1%),124137 (15.9%),120050 (14.7%),137340 (14.7%),149835 (14.4%),162334 (15.0%)
MEDICINA INTERNA,142928 (12.4%),135740 (17.4%),147449 (18.0%),131421 (14.1%),140730 (13.5%),155574 (14.3%)
TRAUMATOLOGIA Y ORTOPEDIA,83285 (7.2%),57434 (7.3%),62207 (7.6%),75259 (8.1%),90911 (8.7%),93848 (8.6%)
PEDIATRIA,78098 (6.8%),35330 (4.5%),40002 (4.9%),59484 (6.4%),71680 (6.9%),68541 (6.3%)
...,...,...,...,...,...,...
IMAGENOLOGIA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
SALUD PUBLICA (ODONTOLOGICA),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%)
IMAGENOLOGIA ORAL Y MAXILOFACIAL,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
MEDICINA MATERNO FETAL,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NUTRIOLOGO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (ESPECIALIDAD_MEDICA):'

,2019,2020,2021,2022,2023,2024
CIRUGIA GENERAL,22150 (22.6%),16872 (26.0%),17550 (25.8%),19433 (24.9%),21464 (23.7%),22244 (22.4%)
MEDICINA INTERNA,15681 (16.0%),13180 (20.3%),12845 (18.9%),14631 (18.7%),16994 (18.7%),19370 (19.5%)
ONCOLOGIA MEDICA,21996 (22.5%),7599 (11.7%),6281 (9.2%),7148 (9.2%),8183 (9.0%),9200 (9.3%)
OBSTETRICIA Y GINECOLOGIA,6971 (7.1%),5544 (8.5%),6035 (8.9%),7131 (9.1%),8033 (8.9%),8825 (8.9%)
UROLOGIA,6021 (6.2%),4632 (7.1%),5298 (7.8%),6267 (8.0%),7513 (8.3%),8063 (8.1%)
...,...,...,...,...,...,...
INFECTOLOGIA PEDIATRICA,0 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
GINECOLOGIA PEDIATRICA Y DE LA ADOLESCENCIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%)
MATRONAS(ES),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%)
ORTODONCIA Y ORTOPEDIA DENTO MAXILOFACIAL,0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
ENDODONCIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (ESPECIALIDAD_MEDICA):'

,2019,2020,2021,2022,2023,2024
OBSTETRICIA Y GINECOLOGIA,227491 (21.6%),174414 (24.3%),167113 (22.3%),195541 (22.9%),200893 (21.2%),196534 (19.9%)
MEDICINA INTERNA,127247 (12.1%),122560 (17.1%),134604 (18.0%),116790 (13.7%),123736 (13.0%),136204 (13.8%)
CIRUGIA GENERAL,163281 (15.5%),107265 (15.0%),102500 (13.7%),117907 (13.8%),128371 (13.5%),140090 (14.2%)
TRAUMATOLOGIA Y ORTOPEDIA,82140 (7.8%),56504 (7.9%),61121 (8.2%),73978 (8.7%),89156 (9.4%),91876 (9.3%)
PEDIATRIA,76950 (7.3%),34323 (4.8%),38851 (5.2%),58326 (6.8%),70563 (7.4%),67351 (6.8%)
...,...,...,...,...,...,...
IMAGENOLOGIA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
SALUD PUBLICA (ODONTOLOGICA),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%)
IMAGENOLOGIA ORAL Y MAXILOFACIAL,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
MEDICINA MATERNO FETAL,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NUTRIOLOGO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

### **13. Tipo de Actividad (TIPO_ACTIVIDAD)**
- **Tipo de variable**: Hospitalaria.
- **Descripción**: Modalidad de atención asociada al episodio clínico.
- **Cardinalidad**: Baja (5 categorías, con inconsistencias temporales).
- **Veredicto**: **Retener y Homologar**. Es un fuerte determinante del consumo de recursos. Sin embargo, el análisis detectó un quiebre en el registro: las categorías `HOSPITALIZACION DIURNA` y `HOSPITALIZACION EN URGENCIA` dejan de utilizarse a partir de 2020. Para garantizar la coherencia longitudinal del estudio a lo largo de los 6 años, estas categorías descontinuadas serán fusionadas dentro de la categoría principal `HOSPITALIZACION`. La variable quedará binarizada en la práctica entre hospitalización clásica y `CIRUGIA MAYOR AMBULATORIA (CMA)`.

In [16]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"TIPO_ACTIVIDAD")
mostrar_resultados(total, oncologico, control, "TIPO_ACTIVIDAD")

[TIPO_ACTIVIDAD] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad TIPO_ACTIVIDAD: 5 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (TIPO_ACTIVIDAD):'

,2019,2020,2021,2022,2023,2024
HOSPITALIZACION,886571 (77.0%),702275 (89.8%),713978 (87.4%),778072 (83.4%),846043 (81.4%),873772 (80.5%)
CIRUGIA MAYOR AMBULATORIA (CMA),146928 (12.8%),79636 (10.2%),102931 (12.6%),154765 (16.6%),193544 (18.6%),212041 (19.5%)
HOSPITALIZACION EN URGENCIA,62551 (5.4%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
HOSPITALIZACION DIURNA,55327 (4.8%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,18 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NO IDENTIFICADO,3 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (TIPO_ACTIVIDAD):'

,2019,2020,2021,2022,2023,2024
HOSPITALIZACION,73808 (75.4%),61278 (94.4%),62237 (91.6%),70160 (89.9%),80500 (88.7%),88072 (88.8%)
CIRUGIA MAYOR AMBULATORIA (CMA),4502 (4.6%),3648 (5.6%),5689 (8.4%),7909 (10.1%),10215 (11.3%),11081 (11.2%)
HOSPITALIZACION DIURNA,16169 (16.5%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
HOSPITALIZACION EN URGENCIA,3350 (3.4%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (TIPO_ACTIVIDAD):'

,2019,2020,2021,2022,2023,2024
HOSPITALIZACION,812763 (77.1%),640997 (89.4%),651741 (87.0%),707912 (82.8%),765543 (80.7%),785700 (79.6%)
CIRUGIA MAYOR AMBULATORIA (CMA),142426 (13.5%),75988 (10.6%),97242 (13.0%),146856 (17.2%),183329 (19.3%),200960 (20.4%)
HOSPITALIZACION EN URGENCIA,59201 (5.6%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
HOSPITALIZACION DIURNA,39158 (3.7%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,18 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NO IDENTIFICADO,3 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **14. Servicio de Ingreso (SERVICIOINGRESO)**
- **Tipo de variable**: Hospitalaria / Operativa.
- **Descripción**: Servicio clínico físico donde el paciente es admitido al iniciar su episodio.
- **Cardinalidad**: Alta (92 categorías únicas con alta redundancia).
- **Veredicto**: **Retener y Agrupar por Complejidad**. Esta variable detalla la carga de infraestructura física del hospital. Al igual que con las especialidades, presenta una alta fragmentación por digitación redundante (ej. `UTI ADULTOS` vs. `UNIDAD DE TRATAMIENTO INTERMEDIO...`). Se aplicará un procesamiento de lenguaje natural (NLP) o mapeo manual estructurado para agrupar estas 92 áreas en niveles de complejidad resolutiva: *Cuidados Críticos (UCI/UTI)*, *Pabellón Quirúrgico / Recuperación*, *Cuidados Medios/Básicos*, y *Maternidad/Pediatría*. Esto reducirá la dimensionalidad previniendo la dispersión de los algoritmos de selección de características.

In [17]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"SERVICIOINGRESO")
mostrar_resultados(total, oncologico, control, "SERVICIOINGRESO")

[SERVICIOINGRESO] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOINGRESO: 92 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOINGRESO):'

,2019,2020,2021,2022,2023,2024
CIRUGIA,132161 (11.5%),91125 (11.7%),84442 (10.3%),95357 (10.2%),99893 (9.6%),101990 (9.4%)
UNIDAD DE RECUPERACION DE PABELLONES (CENTRAL Y CMA),101201 (8.8%),49633 (6.3%),63071 (7.7%),97241 (10.4%),125125 (12.0%),149515 (13.8%)
MEDICINA,101979 (8.9%),90153 (11.5%),86873 (10.6%),79883 (8.6%),81786 (7.9%),93439 (8.6%)
OBSTETRICIA,108329 (9.4%),88038 (11.3%),79730 (9.8%),86407 (9.3%),82838 (8.0%),74134 (6.8%)
PEDIATRIA,60846 (5.3%),30102 (3.8%),33581 (4.1%),42819 (4.6%),49442 (4.8%),46731 (4.3%)
...,...,...,...,...,...,...
PSIQUIATRIA FORENSE ALTA COMPLEJIDAD,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),9 (0.0%)
PSIQUIATRIA CRONICO,2 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
CARDIOCIRUGIA (INFANTIL),1 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NULOS,0 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OTRA,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOINGRESO):'

,2019,2020,2021,2022,2023,2024
CIRUGIA,18271 (18.7%),13833 (21.3%),13699 (20.2%),14972 (19.2%),15891 (17.5%),15686 (15.8%)
MEDICINA,13323 (13.6%),11003 (16.9%),9106 (13.4%),9791 (12.5%),11496 (12.7%),13995 (14.1%)
ONCOLOGIA,16858 (17.2%),7171 (11.0%),5960 (8.8%),6052 (7.8%),6928 (7.6%),7369 (7.4%)
GINECOLOGIA,6685 (6.8%),5334 (8.2%),6095 (9.0%),6943 (8.9%),7704 (8.5%),7815 (7.9%)
UNIDAD DE RECUPERACION DE PABELLONES (CENTRAL Y CMA),3789 (3.9%),2396 (3.7%),3588 (5.3%),4761 (6.1%),5944 (6.6%),6996 (7.1%)
...,...,...,...,...,...,...
UNIDAD DE TRATAMIENTO INTERMEDIO QUEMADOS,1 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
NEONATOLOGIA CUNAS,1 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
AREANEONATOLOGIA CUIDADOS BASICOS,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NULOS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA CRONICO,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOINGRESO):'

,2019,2020,2021,2022,2023,2024
UNIDAD DE RECUPERACION DE PABELLONES (CENTRAL Y CMA),97412 (9.2%),47237 (6.6%),59483 (7.9%),92480 (10.8%),119181 (12.6%),142519 (14.4%)
OBSTETRICIA,108031 (10.3%),87815 (12.2%),79427 (10.6%),86128 (10.1%),82438 (8.7%),73614 (7.5%)
CIRUGIA,113890 (10.8%),77292 (10.8%),70743 (9.4%),80385 (9.4%),84002 (8.9%),86304 (8.7%)
MEDICINA,88656 (8.4%),79150 (11.0%),77767 (10.4%),70092 (8.2%),70290 (7.4%),79444 (8.1%)
PEDIATRIA,58659 (5.6%),28154 (3.9%),31390 (4.2%),40884 (4.8%),47695 (5.0%),45102 (4.6%)
...,...,...,...,...,...,...
PSIQUIATRIA FORENSE ALTA COMPLEJIDAD,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),9 (0.0%)
CARDIOCIRUGIA (INFANTIL),1 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA CRONICO,2 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NULOS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OTRA,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **15. Servicios de Traslado (SERVICIOTRASLADO1 al 9)**
- **Tipo de variable**: Hospitalaria / Operativa.
- **Descripción**: Registro cronológico de las unidades o servicios clínicos específicos a los que el paciente fue trasladado durante la evolución de su hospitalización.
- **Cardinalidad**: Muy Alta y variable (entre 66 y 97 categorías por columna, con múltiples errores tipográficos y códigos numéricos sin descripción).
- **Veredicto**: **Descartar columnas originales y Transformar en Variable Derivada (`CANTIDAD_TRASLADOS`)**. El análisis masivo de datos revela que la matriz es insosteniblemente dispersa: el primer traslado (`SERVICIOTRASLADO1`) posee ~80-86% de valores nulos, escalando drásticamente hasta un 99-100% de nulos entre el cuarto y noveno traslado. Aplicar *One-Hot Encoding* a este bloque inyectaría cientos de columnas vacías, diluyendo el poder estadístico de las variables basales. Sin embargo, el "traslado" en sí mismo es un proxy clínico de inestabilidad o complicación. Por ende, las 9 columnas se colapsarán en una única variable numérica discreta que cuente el número total de traslados por episodio, rescatando la varianza útil sin penalizar la dimensionalidad del modelo.

In [18]:
for i in range(1, 10):
    total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,f"SERVICIOTRASLADO{i}")
    mostrar_resultados(total, oncologico, control, f"SERVICIOTRASLADO{i}")

[SERVICIOTRASLADO1] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOTRASLADO1: 95 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOTRASLADO1):'

,2019,2020,2021,2022,2023,2024
NULOS,985068 (85.6%),617598 (79.0%),648637 (79.4%),770865 (82.6%),872748 (84.0%),912553 (84.0%)
MEDICINA,20641 (1.8%),22337 (2.9%),22322 (2.7%),20295 (2.2%),21444 (2.1%),22333 (2.1%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,12892 (1.1%),14283 (1.8%),16501 (2.0%),14503 (1.6%),16936 (1.6%),19159 (1.8%)
CIRUGIA,14748 (1.3%),15504 (2.0%),12834 (1.6%),10809 (1.2%),10874 (1.0%),11723 (1.1%)
PUERPERIO,15827 (1.4%),12655 (1.6%),9243 (1.1%),11503 (1.2%),7729 (0.7%),7217 (0.7%)
...,...,...,...,...,...,...
PSIQUIATRIA FORENSE ALTA COMPLEJIDAD,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),5 (0.0%)
HOSPITAL DE DIA MEDICO,0 (0.0%),1 (0.0%),3 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CIRUGIA TORAX,0 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%)
0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),1 (0.0%)
420,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOTRASLADO1):'

,2019,2020,2021,2022,2023,2024
NULOS,84613 (86.5%),51742 (79.7%),55193 (81.3%),63912 (81.9%),74625 (82.3%),81075 (81.8%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,2528 (2.6%),1973 (3.0%),1658 (2.4%),2381 (3.0%),2903 (3.2%),3322 (3.4%)
MEDICINA,1697 (1.7%),1853 (2.9%),1388 (2.0%),1602 (2.1%),1861 (2.1%),2070 (2.1%)
CIRUGIA,1726 (1.8%),1919 (3.0%),1555 (2.3%),1524 (2.0%),1741 (1.9%),1982 (2.0%)
UNIDAD DE CUIDADOS INTENSIVOS ADULTO,1085 (1.1%),926 (1.4%),984 (1.4%),981 (1.3%),1095 (1.2%),1331 (1.3%)
...,...,...,...,...,...,...
MEDICINA FISICA Y REHABILITACION,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%)
CIRUGIA MAXILO FACIAL,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
AREANEONATOLOGIA CUIDADOS INTERMEDIOS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
PSIQUIATRIA CRONICO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NEONATOLOGIA INCUBADORAS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOTRASLADO1):'

,2019,2020,2021,2022,2023,2024
NULOS,900455 (85.5%),565856 (78.9%),593444 (79.2%),706953 (82.7%),798123 (84.1%),831478 (84.3%)
MEDICINA,18944 (1.8%),20484 (2.9%),20934 (2.8%),18693 (2.2%),19583 (2.1%),20263 (2.1%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,10364 (1.0%),12310 (1.7%),14843 (2.0%),12122 (1.4%),14033 (1.5%),15837 (1.6%)
CIRUGIA,13022 (1.2%),13585 (1.9%),11279 (1.5%),9285 (1.1%),9133 (1.0%),9741 (1.0%)
PUERPERIO,15817 (1.5%),12650 (1.8%),9231 (1.2%),11485 (1.3%),7716 (0.8%),7210 (0.7%)
...,...,...,...,...,...,...
HOSPITAL DE DIA MEDICO,0 (0.0%),1 (0.0%),3 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CIRUGIA TORAX,0 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%)
0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),1 (0.0%)
HOSPITA DE DIA ONCOLOGICO,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%)
420,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[SERVICIOTRASLADO2] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOTRASLADO2: 94 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOTRASLADO2):'

,2019,2020,2021,2022,2023,2024
NULOS,1097703 (95.3%),724137 (92.6%),758749 (92.9%),881291 (94.5%),984495 (94.7%),1028719 (94.7%)
MEDICINA,7075 (0.6%),9755 (1.2%),11008 (1.3%),7676 (0.8%),7531 (0.7%),7819 (0.7%)
CIRUGIA,7348 (0.6%),6247 (0.8%),5281 (0.6%),5434 (0.6%),5606 (0.5%),6046 (0.6%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,3547 (0.3%),4574 (0.6%),4901 (0.6%),3753 (0.4%),3648 (0.4%),4411 (0.4%)
AGUDOS MEDICINA,2440 (0.2%),2633 (0.3%),2436 (0.3%),2051 (0.2%),2197 (0.2%),2628 (0.2%)
...,...,...,...,...,...,...
PSIQUIATRIA FORENSE MEDIANA COMPLEJIDAD,3 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
HOSPITA DE DIA ONCOLOGICO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),2 (0.0%)
0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
CARDIOCIRUGIA (INFANTIL),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA CRONICO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOTRASLADO2):'

,2019,2020,2021,2022,2023,2024
NULOS,91074 (93.1%),58481 (90.1%),62111 (91.4%),71503 (91.6%),83269 (91.8%),90912 (91.7%)
CIRUGIA,2100 (2.1%),1682 (2.6%),1316 (1.9%),1484 (1.9%),1640 (1.8%),1755 (1.8%)
MEDICINA,718 (0.7%),931 (1.4%),677 (1.0%),794 (1.0%),890 (1.0%),921 (0.9%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,602 (0.6%),582 (0.9%),435 (0.6%),552 (0.7%),605 (0.7%),723 (0.7%)
UNIDAD DE CUIDADOS INTENSIVOS ADULTO,294 (0.3%),282 (0.4%),241 (0.4%),275 (0.4%),347 (0.4%),395 (0.4%)
...,...,...,...,...,...,...
DIABETES Y NUTRICION,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%)
HOSPITA DE DIA ONCOLOGICO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%)
428,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
NEUROPSIQUIATRIA INFANTIL,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD EMERGENCIA (INDIFERENCIADO),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOTRASLADO2):'

,2019,2020,2021,2022,2023,2024
NULOS,1006629 (95.5%),665656 (92.8%),696638 (93.0%),809788 (94.7%),901226 (95.0%),937807 (95.0%)
MEDICINA,6357 (0.6%),8824 (1.2%),10331 (1.4%),6882 (0.8%),6641 (0.7%),6898 (0.7%)
CIRUGIA,5248 (0.5%),4565 (0.6%),3965 (0.5%),3950 (0.5%),3966 (0.4%),4291 (0.4%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,2945 (0.3%),3992 (0.6%),4466 (0.6%),3201 (0.4%),3043 (0.3%),3688 (0.4%)
PUERPERIO,3492 (0.3%),4042 (0.6%),1583 (0.2%),1871 (0.2%),1470 (0.2%),1187 (0.1%)
...,...,...,...,...,...,...
PSIQUIATRIA FORENSE MEDIANA COMPLEJIDAD,3 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
CARDIOCIRUGIA (INFANTIL),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA CRONICO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
HOSPITA DE DIA ONCOLOGICO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[SERVICIOTRASLADO3] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOTRASLADO3: 97 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOTRASLADO3):'

,2019,2020,2021,2022,2023,2024
NULOS,1135168 (98.6%),762920 (97.6%),797687 (97.6%),917047 (98.3%),1023334 (98.4%),1068683 (98.4%)
MEDICINA,2214 (0.2%),2995 (0.4%),3330 (0.4%),2097 (0.2%),1928 (0.2%),2100 (0.2%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,1382 (0.1%),1738 (0.2%),1768 (0.2%),1358 (0.1%),1442 (0.1%),1677 (0.2%)
CIRUGIA,1589 (0.1%),1757 (0.2%),1415 (0.2%),1357 (0.1%),1375 (0.1%),1496 (0.1%)
AGUDOS MEDICINA,888 (0.1%),870 (0.1%),886 (0.1%),654 (0.1%),781 (0.1%),884 (0.1%)
...,...,...,...,...,...,...
428,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
429,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
AREA SOCIOSANITARIA ADULTO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
HOSPITA DE DIA ONCOLOGICO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
HOSPITAL DE DIA QUIRURGICO,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOTRASLADO3):'

,2019,2020,2021,2022,2023,2024
NULOS,95789 (97.9%),62892 (96.9%),66113 (97.3%),76085 (97.5%),88393 (97.4%),96518 (97.3%)
CIRUGIA,414 (0.4%),406 (0.6%),283 (0.4%),325 (0.4%),334 (0.4%),327 (0.3%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,292 (0.3%),252 (0.4%),182 (0.3%),222 (0.3%),276 (0.3%),324 (0.3%)
MEDICINA,236 (0.2%),253 (0.4%),199 (0.3%),218 (0.3%),273 (0.3%),284 (0.3%)
UNIDAD DE CUIDADOS INTENSIVOS ADULTO,148 (0.2%),129 (0.2%),118 (0.2%),145 (0.2%),135 (0.1%),194 (0.2%)
...,...,...,...,...,...,...
AREA MEDICO-QUIRURGICOPEDIATRICA CUIDADOS BASICOS,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
AREANEONATOLOGIA CUIDADOS INTERMEDIOS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
MEDICINA FISICA Y REHABILITACION,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
PENSIONADO MATERNIDAD,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
PSIQUIATRIA CORTA ESTADIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOTRASLADO3):'

,2019,2020,2021,2022,2023,2024
NULOS,1039379 (98.7%),700028 (97.6%),731574 (97.7%),840962 (98.4%),934941 (98.5%),972165 (98.5%)
MEDICINA,1978 (0.2%),2742 (0.4%),3131 (0.4%),1879 (0.2%),1655 (0.2%),1816 (0.2%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,1090 (0.1%),1486 (0.2%),1586 (0.2%),1136 (0.1%),1166 (0.1%),1353 (0.1%)
CIRUGIA,1175 (0.1%),1351 (0.2%),1132 (0.2%),1032 (0.1%),1041 (0.1%),1169 (0.1%)
AGUDOS MEDICINA,794 (0.1%),803 (0.1%),835 (0.1%),588 (0.1%),666 (0.1%),753 (0.1%)
...,...,...,...,...,...,...
429,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
428,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
AREA PSIQUIATRIA INFANTO-ADOLESCENTE CORTA ESTADIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
427,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
HOSPITAL DE DIA QUIRURGICO,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[SERVICIOTRASLADO4] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOTRASLADO4: 91 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOTRASLADO4):'

,2019,2020,2021,2022,2023,2024
NULOS,1145762 (99.5%),775367 (99.2%),809645 (99.1%),927097 (99.4%),1033767 (99.4%),1079472 (99.4%)
MEDICINA,806 (0.1%),1062 (0.1%),1176 (0.1%),765 (0.1%),726 (0.1%),780 (0.1%)
CIRUGIA,656 (0.1%),746 (0.1%),527 (0.1%),482 (0.1%),517 (0.0%),583 (0.1%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,511 (0.0%),591 (0.1%),630 (0.1%),468 (0.1%),545 (0.1%),621 (0.1%)
AGUDOS MEDICINA,344 (0.0%),309 (0.0%),330 (0.0%),262 (0.0%),284 (0.0%),321 (0.0%)
...,...,...,...,...,...,...
420,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CARDIOCIRUGIA (INFANTIL),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
CIRUGIA MAXILO FACIAL,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
PSIQUIATRIA FORENSE MEDIANA COMPLEJIDAD,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA CRONICO,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOTRASLADO4):'

,2019,2020,2021,2022,2023,2024
NULOS,97013 (99.2%),64099 (98.7%),67157 (98.9%),77319 (99.0%),89808 (99.0%),98086 (98.9%)
CIRUGIA,171 (0.2%),188 (0.3%),109 (0.2%),98 (0.1%),138 (0.2%),158 (0.2%)
MEDICINA,103 (0.1%),101 (0.2%),69 (0.1%),89 (0.1%),108 (0.1%),130 (0.1%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,91 (0.1%),97 (0.1%),81 (0.1%),86 (0.1%),101 (0.1%),136 (0.1%)
UNIDAD DE CUIDADOS INTENSIVOS ADULTO,57 (0.1%),50 (0.1%),43 (0.1%),54 (0.1%),57 (0.1%),77 (0.1%)
...,...,...,...,...,...,...
AREA MQ PEDIATRIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
MEDICINA FISICA Y REHABILITACION,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
PSIQUIATRIA CORTA ESTADIA,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS NEONATOLOGIA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOTRASLADO4):'

,2019,2020,2021,2022,2023,2024
NULOS,1048749 (99.5%),711268 (99.2%),742488 (99.1%),849778 (99.4%),943959 (99.5%),981386 (99.5%)
MEDICINA,703 (0.1%),961 (0.1%),1107 (0.1%),676 (0.1%),618 (0.1%),650 (0.1%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,420 (0.0%),494 (0.1%),549 (0.1%),382 (0.0%),444 (0.0%),485 (0.0%)
CIRUGIA,485 (0.0%),558 (0.1%),418 (0.1%),384 (0.0%),379 (0.0%),425 (0.0%)
AGUDOS MEDICINA,300 (0.0%),288 (0.0%),304 (0.0%),229 (0.0%),239 (0.0%),274 (0.0%)
...,...,...,...,...,...,...
428,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CARDIOCIRUGIA (INFANTIL),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
CIRUGIA MAXILO FACIAL,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
PSIQUIATRIA FORENSE MEDIANA COMPLEJIDAD,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA CRONICO,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[SERVICIOTRASLADO5] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOTRASLADO5: 86 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOTRASLADO5):'

,2019,2020,2021,2022,2023,2024
NULOS,1149479 (99.8%),779549 (99.7%),814360 (99.7%),930673 (99.8%),1037308 (99.8%),1083337 (99.8%)
MEDICINA,260 (0.0%),356 (0.0%),356 (0.0%),223 (0.0%),250 (0.0%),315 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,184 (0.0%),235 (0.0%),220 (0.0%),209 (0.0%),208 (0.0%),240 (0.0%)
CIRUGIA,195 (0.0%),230 (0.0%),176 (0.0%),132 (0.0%),208 (0.0%),201 (0.0%)
AGUDOS MEDICINA,144 (0.0%),114 (0.0%),118 (0.0%),109 (0.0%),135 (0.0%),157 (0.0%)
...,...,...,...,...,...,...
418,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
AREA MQ PEDIATRIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CIRUGIA MAXILO FACIAL,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
NEONATOLOGIA INCUBADORAS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD EMERGENCIA ADULTOS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOTRASLADO5):'

,2019,2020,2021,2022,2023,2024
NULOS,97527 (99.7%),64603 (99.5%),67630 (99.6%),77769 (99.6%),90367 (99.6%),98737 (99.6%)
CIRUGIA,50 (0.1%),57 (0.1%),29 (0.0%),33 (0.0%),52 (0.1%),52 (0.1%)
MEDICINA,37 (0.0%),35 (0.1%),25 (0.0%),34 (0.0%),42 (0.0%),56 (0.1%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,41 (0.0%),43 (0.1%),26 (0.0%),29 (0.0%),35 (0.0%),46 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS ADULTO,28 (0.0%),26 (0.0%),18 (0.0%),16 (0.0%),28 (0.0%),35 (0.0%)
AGUDOS MEDICINA,28 (0.0%),21 (0.0%),17 (0.0%),11 (0.0%),26 (0.0%),24 (0.0%)
ONCOLOGIA,10 (0.0%),8 (0.0%),20 (0.0%),10 (0.0%),14 (0.0%),18 (0.0%)
NEUROCIRUGIA ADULTO,15 (0.0%),8 (0.0%),11 (0.0%),15 (0.0%),13 (0.0%),17 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO MEDICINA ADULTO,15 (0.0%),14 (0.0%),11 (0.0%),14 (0.0%),9 (0.0%),16 (0.0%)
AGUDOS CIRUGIA,13 (0.0%),5 (0.0%),6 (0.0%),20 (0.0%),8 (0.0%),18 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS PEDIATRIA,11 (0.0%),7 (0.0%),9 (0.0%),11 (0.0%),15 (0.0%),10 (0.0%)
AREA MEDICO-QUIRURGICO CUIDADOS MEDIOS,0 (0.0%),5 (0.0%),12 (0.0%),6 (0.0%),13 (0.0%),26 (0.0%)
AREA MEDICA ADULTO CUIDADOS MEDIOS,0 (0.0%),3 (0.0%),9 (0.0%),9 (0.0%),11 (0.0%),15 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CIRUGIA ADULTO,4 (0.0%),3 (0.0%),3 (0.0%),9 (0.0%),13 (0.0%),10 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO PEDIATRIA,3 (0.0%),6 (0.0%),16 (0.0%),6 (0.0%),2 (0.0%),6 (0.0%)
UNIDAD DE TRATAMIENTOS INTERMEDIOS MEDICINA,3 (0.0%),4 (0.0%),3 (0.0%),2 (0.0%),12 (0.0%),9 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS (UCI) (INDIFERENCIADO),2 (0.0%),10 (0.0%),3 (0.0%),7 (0.0%),5 (0.0%),5 (0.0%)
AREA QUIRURGICA,7 (0.0%),3 (0.0%),7 (0.0%),7 (0.0%),4 (0.0%),3 (0.0%)
PEDIATRIA,5 (0.0%),5 (0.0%),6 (0.0%),2 (0.0%),5 (0.0%),3 (0.0%)
AREA MEDICO-QUIRURGICO CUIDADOS BASICOS,0 (0.0%),0 (0.0%),6 (0.0%),9 (0.0%),5 (0.0%),5 (0.0%)
UROLOGIA,3 (0.0%),3 (0.0%),8 (0.0%),4 (0.0%),2 (0.0%),2 (0.0%)
AREA MEDICA ADULTO CUIDADOS BASICOS,0 (0.0%),1 (0.0%),11 (0.0%),6 (0.0%),1 (0.0%),1 (0.0%)
NEUROCIRUGIA INFANTIL,1 (0.0%),7 (0.0%),1 (0.0%),3 (0.0%),2 (0.0%),5 (0.0%)
GINECOLOGIA,3 (0.0%),9 (0.0%),1 (0.0%),2 (0.0%),2 (0.0%),2 (0.0%)
SEGUNDA INFANCIA,1 (0.0%),8 (0.0%),5 (0.0%),2 (0.0%),1 (0.0%),2 (0.0%)
GERIATRIA,2 (0.0%),1 (0.0%),4 (0.0%),3 (0.0%),7 (0.0%),1 (0.0%)
UTI ADULTOS,0 (0.0%),3 (0.0%),5 (0.0%),4 (0.0%),1 (0.0%),4 (0.0%)
DERIVACION MEDICO QUIRURGICO,4 (0.0%),3 (0.0%),2 (0.0%),3 (0.0%),2 (0.0%),3 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO NEUROQUIRURGICO,2 (0.0%),2 (0.0%),0 (0.0%),1 (0.0%),2 (0.0%),7 (0.0%)
TRAUMATOLOGIA Y ORTOPEDIA,0 (0.0%),3 (0.0%),2 (0.0%),5 (0.0%),1 (0.0%),3 (0.0%)
AREA DE TRANSPLANTE INFANTIL,2 (0.0%),1 (0.0%),4 (0.0%),1 (0.0%),1 (0.0%),2 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS QUEMADOS,3 (0.0%),3 (0.0%),0 (0.0%),2 (0.0%),2 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CORONARIO,1 (0.0%),2 (0.0%),1 (0.0%),3 (0.0%),0 (0.0%),3 (0.0%)
OTORRINOLARINGOLOGIA,0 (0.0%),4 (0.0%),3 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
AREA MEDICA,3 (0.0%),1 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS MEDICO QUIRURGICOS,1 (0.0%),3 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PENSIONADO ADULTO,0 (0.0%),2 (0.0%),1 (0.0%),2 (0.0%),1 (0.0%),0 (0.0%)
CIRUGIA INFANTIL,0 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS CARDIOLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),2 (0.0%)
DESCONOCIDO,0 (0.0%),0 (0.0%),1 (0.0%),2 (0.0%),1 (0.0%),0 (0.0%)
CIRUGIA CARDIOVASCULAR,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%)
OBSTETRICIA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
LACTANTES,0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
AREAOBSTETRICA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CIRUGIA DE PARTES BLANDAS INFANTIL,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
AREA MEDICO-QUIRURGICOPEDIATRICA CUIDADOS MEDIOS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%)
AREA DE TRANSPLANTE ADULTO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
PENSIONADO PEDIATRICO,1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OFTALMOLOGIA,0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
TRAUMATOLOGIA Y ORTOPEDIA INFANTIL,0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
NEUROCIRUGIA (INDIFERENCIADO),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OBSTETRICIA Y GINECOLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
NEUROLOGIA ADULTO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CARDIOVASCULAR,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO NEUROLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO NEONATOLOGIA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOTRASLADO5):'

,2019,2020,2021,2022,2023,2024
NULOS,1051952 (99.8%),714946 (99.7%),746730 (99.7%),852904 (99.8%),946941 (99.8%),984600 (99.8%)
MEDICINA,223 (0.0%),321 (0.0%),331 (0.0%),189 (0.0%),208 (0.0%),259 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,143 (0.0%),192 (0.0%),194 (0.0%),180 (0.0%),173 (0.0%),194 (0.0%)
CIRUGIA,145 (0.0%),173 (0.0%),147 (0.0%),99 (0.0%),156 (0.0%),149 (0.0%)
AGUDOS MEDICINA,116 (0.0%),93 (0.0%),101 (0.0%),98 (0.0%),109 (0.0%),133 (0.0%)
...,...,...,...,...,...,...
418,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NEONATOLOGIA INCUBADORAS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CIRUGIA MAXILO FACIAL,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
PENSIONADO PEDIATRICO,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD EMERGENCIA ADULTOS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[SERVICIOTRASLADO6] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOTRASLADO6: 79 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOTRASLADO6):'

,2019,2020,2021,2022,2023,2024
NULOS,1150562 (99.9%),780846 (99.9%),815816 (99.9%),931801 (99.9%),1038566 (99.9%),1084664 (99.9%)
MEDICINA,110 (0.0%),166 (0.0%),140 (0.0%),124 (0.0%),112 (0.0%),125 (0.0%)
CIRUGIA,93 (0.0%),116 (0.0%),77 (0.0%),76 (0.0%),88 (0.0%),112 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,69 (0.0%),86 (0.0%),99 (0.0%),90 (0.0%),92 (0.0%),100 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS ADULTO,36 (0.0%),54 (0.0%),56 (0.0%),55 (0.0%),56 (0.0%),56 (0.0%)
...,...,...,...,...,...,...
DIABETES Y NUTRICION,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
AREAOBSTETRICA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
AREA SOCIOSANITARIA ADULTO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
AREA PSIQUIATRIA ADULTO CORTA ESTADIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD EMERGENCIA ADULTOS,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOTRASLADO6):'

,2019,2020,2021,2022,2023,2024
NULOS,97679 (99.8%),64768 (99.8%),67793 (99.8%),77921 (99.8%),90552 (99.8%),98957 (99.8%)
CIRUGIA,33 (0.0%),28 (0.0%),12 (0.0%),16 (0.0%),23 (0.0%),34 (0.0%)
MEDICINA,14 (0.0%),21 (0.0%),9 (0.0%),16 (0.0%),17 (0.0%),23 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,12 (0.0%),13 (0.0%),16 (0.0%),17 (0.0%),15 (0.0%),23 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS ADULTO,9 (0.0%),12 (0.0%),7 (0.0%),12 (0.0%),12 (0.0%),14 (0.0%)
ONCOLOGIA,3 (0.0%),5 (0.0%),14 (0.0%),8 (0.0%),7 (0.0%),9 (0.0%)
AGUDOS CIRUGIA,9 (0.0%),3 (0.0%),5 (0.0%),7 (0.0%),12 (0.0%),7 (0.0%)
AGUDOS MEDICINA,6 (0.0%),5 (0.0%),6 (0.0%),5 (0.0%),13 (0.0%),6 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO MEDICINA ADULTO,8 (0.0%),3 (0.0%),7 (0.0%),9 (0.0%),4 (0.0%),7 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO PEDIATRIA,9 (0.0%),4 (0.0%),9 (0.0%),2 (0.0%),7 (0.0%),2 (0.0%)
NEUROCIRUGIA ADULTO,7 (0.0%),9 (0.0%),3 (0.0%),1 (0.0%),4 (0.0%),9 (0.0%)
AREA MEDICO-QUIRURGICO CUIDADOS MEDIOS,0 (0.0%),2 (0.0%),4 (0.0%),7 (0.0%),6 (0.0%),10 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS PEDIATRIA,2 (0.0%),6 (0.0%),6 (0.0%),4 (0.0%),1 (0.0%),9 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CIRUGIA ADULTO,8 (0.0%),2 (0.0%),1 (0.0%),4 (0.0%),7 (0.0%),4 (0.0%)
AREA MEDICA ADULTO CUIDADOS MEDIOS,0 (0.0%),1 (0.0%),7 (0.0%),1 (0.0%),2 (0.0%),9 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS (UCI) (INDIFERENCIADO),5 (0.0%),9 (0.0%),2 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
PEDIATRIA,3 (0.0%),2 (0.0%),4 (0.0%),3 (0.0%),4 (0.0%),2 (0.0%)
UNIDAD DE TRATAMIENTOS INTERMEDIOS MEDICINA,1 (0.0%),2 (0.0%),0 (0.0%),2 (0.0%),7 (0.0%),6 (0.0%)
UTI ADULTOS,0 (0.0%),3 (0.0%),3 (0.0%),2 (0.0%),2 (0.0%),1 (0.0%)
AREA QUIRURGICA,3 (0.0%),3 (0.0%),1 (0.0%),3 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CORONARIO,1 (0.0%),0 (0.0%),3 (0.0%),2 (0.0%),1 (0.0%),3 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO NEUROQUIRURGICO,2 (0.0%),2 (0.0%),0 (0.0%),1 (0.0%),3 (0.0%),2 (0.0%)
NEUROCIRUGIA INFANTIL,1 (0.0%),2 (0.0%),0 (0.0%),2 (0.0%),4 (0.0%),0 (0.0%)
GERIATRIA,2 (0.0%),2 (0.0%),1 (0.0%),1 (0.0%),1 (0.0%),1 (0.0%)
AREA DE TRANSPLANTE INFANTIL,1 (0.0%),1 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),2 (0.0%)
SEGUNDA INFANCIA,0 (0.0%),5 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UROLOGIA,1 (0.0%),2 (0.0%),2 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%)
AREA MEDICA ADULTO CUIDADOS BASICOS,0 (0.0%),1 (0.0%),1 (0.0%),4 (0.0%),1 (0.0%),0 (0.0%)
AREA MEDICO-QUIRURGICO CUIDADOS BASICOS,0 (0.0%),0 (0.0%),1 (0.0%),4 (0.0%),1 (0.0%),1 (0.0%)
GINECOLOGIA,0 (0.0%),1 (0.0%),1 (0.0%),2 (0.0%),1 (0.0%),1 (0.0%)
DERIVACION MEDICO QUIRURGICO,1 (0.0%),2 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),0 (0.0%)
OTORRINOLARINGOLOGIA,3 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS CARDIOLOGIA,0 (0.0%),1 (0.0%),0 (0.0%),3 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS QUEMADOS,1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),2 (0.0%)
TRAUMATOLOGIA Y ORTOPEDIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),3 (0.0%)
CIRUGIA INFANTIL,2 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
AREA MEDICA,1 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PENSIONADO ADULTO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),3 (0.0%),0 (0.0%)
NEUROCIRUGIA (INDIFERENCIADO),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%)
405,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CARDIOVASCULAR,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
LACTANTES,0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NEUROLOGIA ADULTO,1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OBSTETRICIA,0 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS TRAUMATOLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%)
CIRUGIA PLASTICA-QUEMADOS INFANTIL,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS MEDICO QUIRURGICOS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OFTALMOLOGIA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOTRASLADO6):'

,2019,2020,2021,2022,2023,2024
NULOS,1052883 (99.9%),716078 (99.9%),748023 (99.9%),853880 (99.9%),948014 (99.9%),985707 (99.9%)
MEDICINA,96 (0.0%),145 (0.0%),131 (0.0%),108 (0.0%),95 (0.0%),102 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,57 (0.0%),73 (0.0%),83 (0.0%),73 (0.0%),77 (0.0%),77 (0.0%)
CIRUGIA,60 (0.0%),88 (0.0%),65 (0.0%),60 (0.0%),65 (0.0%),78 (0.0%)
AGUDOS MEDICINA,56 (0.0%),41 (0.0%),35 (0.0%),38 (0.0%),45 (0.0%),53 (0.0%)
...,...,...,...,...,...,...
DIABETES Y NUTRICION,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
AREAOBSTETRICA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
AREA SOCIOSANITARIA ADULTO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
AREA PSIQUIATRIA ADULTO CORTA ESTADIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD EMERGENCIA ADULTOS,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[SERVICIOTRASLADO7] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOTRASLADO7: 73 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOTRASLADO7):'

,2019,2020,2021,2022,2023,2024
NULOS,1150986 (100.0%),781414 (99.9%),816356 (99.9%),932320 (99.9%),1039074 (100.0%),1085232 (99.9%)
MEDICINA,42 (0.0%),61 (0.0%),62 (0.0%),38 (0.0%),38 (0.0%),57 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,44 (0.0%),48 (0.0%),42 (0.0%),48 (0.0%),40 (0.0%),54 (0.0%)
CIRUGIA,44 (0.0%),47 (0.0%),40 (0.0%),31 (0.0%),43 (0.0%),44 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS PEDIATRIA,28 (0.0%),23 (0.0%),31 (0.0%),22 (0.0%),33 (0.0%),36 (0.0%)
...,...,...,...,...,...,...
OBSTETRICIA Y GINECOLOGIA,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
PSIQUIATRIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%)
AREA CUIDADOS INTERMEDIOS PEDIATRICOS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS NEUROLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
PENSIONADO PEDIATRICO,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOTRASLADO7):'

,2019,2020,2021,2022,2023,2024
NULOS,97764 (99.9%),64849 (99.9%),67853 (99.9%),78001 (99.9%),90627 (99.9%),99060 (99.9%)
CIRUGIA,12 (0.0%),17 (0.0%),6 (0.0%),5 (0.0%),10 (0.0%),7 (0.0%)
MEDICINA,3 (0.0%),11 (0.0%),7 (0.0%),12 (0.0%),10 (0.0%),13 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,7 (0.0%),6 (0.0%),2 (0.0%),3 (0.0%),10 (0.0%),10 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS ADULTO,4 (0.0%),6 (0.0%),3 (0.0%),4 (0.0%),8 (0.0%),8 (0.0%)
ONCOLOGIA,3 (0.0%),4 (0.0%),9 (0.0%),4 (0.0%),3 (0.0%),5 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS PEDIATRIA,4 (0.0%),4 (0.0%),7 (0.0%),2 (0.0%),6 (0.0%),3 (0.0%)
AGUDOS MEDICINA,3 (0.0%),2 (0.0%),5 (0.0%),1 (0.0%),8 (0.0%),6 (0.0%)
NEUROCIRUGIA ADULTO,5 (0.0%),2 (0.0%),3 (0.0%),2 (0.0%),4 (0.0%),2 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO MEDICINA ADULTO,0 (0.0%),4 (0.0%),2 (0.0%),5 (0.0%),4 (0.0%),2 (0.0%)
AREA MEDICO-QUIRURGICO CUIDADOS MEDIOS,0 (0.0%),1 (0.0%),2 (0.0%),5 (0.0%),1 (0.0%),8 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CIRUGIA ADULTO,1 (0.0%),0 (0.0%),2 (0.0%),3 (0.0%),5 (0.0%),3 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO PEDIATRIA,1 (0.0%),0 (0.0%),4 (0.0%),3 (0.0%),3 (0.0%),2 (0.0%)
AGUDOS CIRUGIA,4 (0.0%),0 (0.0%),0 (0.0%),5 (0.0%),0 (0.0%),3 (0.0%)
AREA QUIRURGICA,6 (0.0%),1 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTOS INTERMEDIOS MEDICINA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),6 (0.0%)
AREA MEDICA ADULTO CUIDADOS MEDIOS,0 (0.0%),3 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),2 (0.0%)
GERIATRIA,2 (0.0%),0 (0.0%),1 (0.0%),2 (0.0%),2 (0.0%),0 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS (UCI) (INDIFERENCIADO),1 (0.0%),2 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%)
SEGUNDA INFANCIA,0 (0.0%),3 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
PEDIATRIA,2 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),1 (0.0%)
NEUROCIRUGIA INFANTIL,0 (0.0%),1 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),2 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO NEUROQUIRURGICO,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),3 (0.0%),1 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CORONARIO,1 (0.0%),1 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
UROLOGIA,0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
UTI ADULTOS,0 (0.0%),0 (0.0%),3 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
AREA MEDICO-QUIRURGICO CUIDADOS BASICOS,0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%)
AREA MEDICA ADULTO CUIDADOS BASICOS,0 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
DERIVACION MEDICO QUIRURGICO,0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%)
AREA DE TRANSPLANTE INFANTIL,2 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
TRAUMATOLOGIA Y ORTOPEDIA,1 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
GINECOLOGIA,2 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
CIRUGIA INFANTIL,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
405,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD DE AGUDOS MEDICO QUIRURGICOS,0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS QUEMADOS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
OTORRINOLARINGOLOGIA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
LACTANTES,0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS CARDIOLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
CIRUGIA CARDIOVASCULAR,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CIRUGIA PLASTICA-QUEMADOS INFANTIL,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
PENSIONADO PEDIATRICO,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NEUROCIRUGIA (INDIFERENCIADO),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OFTALMOLOGIA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OBSTETRICIA Y GINECOLOGIA,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
NEUROLOGIA ADULTO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOTRASLADO7):'

,2019,2020,2021,2022,2023,2024
NULOS,1053222 (100.0%),716565 (99.9%),748503 (99.9%),854319 (99.9%),948447 (100.0%),986172 (100.0%)
MEDICINA,39 (0.0%),50 (0.0%),55 (0.0%),26 (0.0%),28 (0.0%),44 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,37 (0.0%),42 (0.0%),40 (0.0%),45 (0.0%),30 (0.0%),44 (0.0%)
CIRUGIA,32 (0.0%),30 (0.0%),34 (0.0%),26 (0.0%),33 (0.0%),37 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS PEDIATRIA,24 (0.0%),19 (0.0%),24 (0.0%),20 (0.0%),27 (0.0%),33 (0.0%)
...,...,...,...,...,...,...
411,0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OFTALMOLOGIA,0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
AREA CUIDADOS INTERMEDIOS PEDIATRICOS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
OBSTETRICIA Y GINECOLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD DE AGUDOS NEUROLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[SERVICIOTRASLADO8] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOTRASLADO8: 74 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOTRASLADO8):'

,2019,2020,2021,2022,2023,2024
NULOS,1151175 (100.0%),781653 (100.0%),816614 (100.0%),932540 (100.0%),1039285 (100.0%),1085495 (100.0%)
MEDICINA,29 (0.0%),19 (0.0%),18 (0.0%),24 (0.0%),27 (0.0%),36 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,19 (0.0%),25 (0.0%),25 (0.0%),23 (0.0%),25 (0.0%),24 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO PEDIATRIA,27 (0.0%),19 (0.0%),20 (0.0%),28 (0.0%),19 (0.0%),17 (0.0%)
CIRUGIA,19 (0.0%),17 (0.0%),15 (0.0%),25 (0.0%),17 (0.0%),14 (0.0%)
...,...,...,...,...,...,...
AREA NEONATOLOGIA CUIDADOS INTENSIVOS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
NEUROPSIQUIATRIA INFANTIL,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
AREAOBSTETRICA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS NEUROLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
PSIQUIATRIA CORTA ESTADIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOTRASLADO8):'

,2019,2020,2021,2022,2023,2024
NULOS,97803 (100.0%),64883 (99.9%),67888 (99.9%),78028 (99.9%),90664 (99.9%),99106 (100.0%)
CIRUGIA,5 (0.0%),8 (0.0%),2 (0.0%),5 (0.0%),4 (0.0%),3 (0.0%)
MEDICINA,2 (0.0%),1 (0.0%),1 (0.0%),3 (0.0%),8 (0.0%),9 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,1 (0.0%),3 (0.0%),4 (0.0%),5 (0.0%),3 (0.0%),3 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS ADULTO,3 (0.0%),3 (0.0%),3 (0.0%),1 (0.0%),2 (0.0%),2 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO PEDIATRIA,3 (0.0%),1 (0.0%),4 (0.0%),2 (0.0%),2 (0.0%),1 (0.0%)
AGUDOS MEDICINA,1 (0.0%),1 (0.0%),0 (0.0%),3 (0.0%),3 (0.0%),4 (0.0%)
ONCOLOGIA,0 (0.0%),2 (0.0%),5 (0.0%),2 (0.0%),2 (0.0%),0 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS PEDIATRIA,2 (0.0%),2 (0.0%),2 (0.0%),0 (0.0%),1 (0.0%),3 (0.0%)
AGUDOS CIRUGIA,1 (0.0%),0 (0.0%),2 (0.0%),3 (0.0%),3 (0.0%),1 (0.0%)
AREA MEDICO-QUIRURGICO CUIDADOS MEDIOS,0 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),1 (0.0%),5 (0.0%)
UNIDAD DE TRATAMIENTOS INTERMEDIOS MEDICINA,0 (0.0%),2 (0.0%),0 (0.0%),2 (0.0%),4 (0.0%),1 (0.0%)
PEDIATRIA,2 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),4 (0.0%),1 (0.0%)
NEUROCIRUGIA ADULTO,0 (0.0%),2 (0.0%),0 (0.0%),1 (0.0%),4 (0.0%),1 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS (UCI) (INDIFERENCIADO),1 (0.0%),4 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CIRUGIA ADULTO,2 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),2 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO MEDICINA ADULTO,1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),4 (0.0%)
NEUROCIRUGIA INFANTIL,0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),3 (0.0%),0 (0.0%)
AREA MEDICA ADULTO CUIDADOS BASICOS,0 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%)
UTI ADULTOS,0 (0.0%),2 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO NEUROQUIRURGICO,0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%)
UROLOGIA,0 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
GERIATRIA,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
AREA DE TRANSPLANTE INFANTIL,1 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
AREA MEDICO-QUIRURGICO CUIDADOS BASICOS,0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%)
AREA MEDICA ADULTO CUIDADOS MEDIOS,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CIRUGIA INFANTIL,1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
OTORRINOLARINGOLOGIA,0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS MEDICO QUIRURGICOS,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
SEGUNDA INFANCIA,0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS TRAUMATOLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%)
AREA MEDICA,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
AREA CUIDADOS INTENSIVOS ADULTOS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
GINECOLOGIA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
INFECCIOSOS INFANTIL,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
NEUROLOGIA ADULTO,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DERIVACION MEDICO QUIRURGICO,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
LACTANTES,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
CIRUGIA PLASTICA-QUEMADOS INFANTIL,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CARDIOVASCULAR,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS QUEMADOS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS NEUROLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CORONARIO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOTRASLADO8):'

,2019,2020,2021,2022,2023,2024
NULOS,1053372 (100.0%),716770 (100.0%),748726 (100.0%),854512 (100.0%),948621 (100.0%),986389 (100.0%)
MEDICINA,27 (0.0%),18 (0.0%),17 (0.0%),21 (0.0%),19 (0.0%),27 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,18 (0.0%),22 (0.0%),21 (0.0%),18 (0.0%),22 (0.0%),21 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO PEDIATRIA,24 (0.0%),18 (0.0%),16 (0.0%),26 (0.0%),17 (0.0%),16 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS PEDIATRIA,8 (0.0%),10 (0.0%),18 (0.0%),26 (0.0%),16 (0.0%),12 (0.0%)
...,...,...,...,...,...,...
411,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
NEUROPSIQUIATRIA INFANTIL,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
AREAOBSTETRICA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
AREA NEONATOLOGIA CUIDADOS INTENSIVOS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
PSIQUIATRIA CORTA ESTADIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[SERVICIOTRASLADO9] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOTRASLADO9: 66 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOTRASLADO9):'

,2019,2020,2021,2022,2023,2024
NULOS,1151271 (100.0%),781761 (100.0%),816740 (100.0%),932666 (100.0%),1039408 (100.0%),1085636 (100.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,17 (0.0%),17 (0.0%),15 (0.0%),19 (0.0%),10 (0.0%),16 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO PEDIATRIA,13 (0.0%),8 (0.0%),16 (0.0%),19 (0.0%),11 (0.0%),14 (0.0%)
MEDICINA,13 (0.0%),21 (0.0%),11 (0.0%),5 (0.0%),10 (0.0%),15 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS PEDIATRIA,16 (0.0%),8 (0.0%),13 (0.0%),11 (0.0%),11 (0.0%),11 (0.0%)
...,...,...,...,...,...,...
PSIQUIATRIA CORTA ESTADIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD DE AGUDOS TRAUMATOLOGIA,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS MEDICO QUIRURGICOS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD EMERGENCIA (INDIFERENCIADO),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOTRASLADO9):'

,2019,2020,2021,2022,2023,2024
NULOS,97819 (100.0%),64902 (100.0%),67904 (100.0%),78046 (100.0%),90681 (100.0%),99128 (100.0%)
MEDICINA,1 (0.0%),4 (0.0%),2 (0.0%),2 (0.0%),4 (0.0%),3 (0.0%)
ONCOLOGIA,3 (0.0%),1 (0.0%),4 (0.0%),2 (0.0%),0 (0.0%),3 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,1 (0.0%),5 (0.0%),1 (0.0%),0 (0.0%),4 (0.0%),1 (0.0%)
AGUDOS MEDICINA,0 (0.0%),1 (0.0%),1 (0.0%),1 (0.0%),5 (0.0%),2 (0.0%)
CIRUGIA,0 (0.0%),1 (0.0%),2 (0.0%),4 (0.0%),2 (0.0%),1 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS ADULTO,0 (0.0%),2 (0.0%),1 (0.0%),0 (0.0%),4 (0.0%),1 (0.0%)
AREA MEDICO-QUIRURGICO CUIDADOS MEDIOS,0 (0.0%),2 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%),3 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO MEDICINA ADULTO,1 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),3 (0.0%),1 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS PEDIATRIA,0 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),3 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO PEDIATRIA,2 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),2 (0.0%)
NEUROCIRUGIA ADULTO,0 (0.0%),0 (0.0%),1 (0.0%),2 (0.0%),2 (0.0%),0 (0.0%)
AREA DE TRANSPLANTE INFANTIL,1 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
AGUDOS CIRUGIA,1 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),0 (0.0%)
SEGUNDA INFANCIA,0 (0.0%),2 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTOS INTERMEDIOS MEDICINA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),2 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CIRUGIA ADULTO,0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),0 (0.0%)
UTI ADULTOS,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
AREA MEDICA ADULTO CUIDADOS MEDIOS,0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PEDIATRIA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
PENSIONADO ADULTO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
GERIATRIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%)
CIRUGIA INFANTIL,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
LACTANTES,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
AREA QUIRURGICA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS CARDIOLOGIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS QUEMADOS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO CORONARIO,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO NEUROQUIRURGICO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD EMERGENCIA (INDIFERENCIADO),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOTRASLADO9):'

,2019,2020,2021,2022,2023,2024
NULOS,1053452 (100.0%),716859 (100.0%),748836 (100.0%),854620 (100.0%),948727 (100.0%),986508 (100.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFERENCIADO) ADULTO,16 (0.0%),12 (0.0%),14 (0.0%),19 (0.0%),6 (0.0%),15 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO PEDIATRIA,11 (0.0%),7 (0.0%),16 (0.0%),18 (0.0%),11 (0.0%),12 (0.0%)
UNIDAD DE CUIDADOS INTENSIVOS PEDIATRIA,16 (0.0%),8 (0.0%),11 (0.0%),10 (0.0%),8 (0.0%),11 (0.0%)
MEDICINA,12 (0.0%),17 (0.0%),9 (0.0%),3 (0.0%),6 (0.0%),12 (0.0%)
...,...,...,...,...,...,...
AREA CUIDADOS INTENSIVOS PEDIATRICOS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS MEDICO QUIRURGICOS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
UNIDAD DE AGUDOS TRAUMATOLOGIA,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
PSIQUIATRIA CORTA ESTADIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

### **16. Servicio de Alta (SERVICIOALTA)**
- **Tipo de variable**: Hospitalaria / Operativa.
- **Descripción**: Servicio clínico específico desde donde el paciente es egresado al finalizar su trayectoria hospitalaria.
- **Cardinalidad**: Alta (89 categorías únicas, con redundancias semánticas equivalentes al servicio de ingreso).
- **Veredicto**: **Descartar**. Aunque en un estudio de caracterización retrospectiva la temporalidad no representa un riesgo estricto de fuga de datos (*Data Leakage*), retener esta variable resulta redundante y tautológico. El servicio de alta exhibe una alta colinealidad tanto con el `SERVICIOINGRESO` como con la variable objetivo `TIPOALTA` (Mortalidad). Al conservar el servicio basal (Ingreso) y medir la inestabilidad intrahospitalaria mediante la variable derivada `CANTIDAD_TRASLADOS`, el estado estructural del paciente queda perfectamente caracterizado sin necesidad de lidiar con las 89 categorías ruidosas del servicio final.

In [19]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"SERVICIOALTA")
mostrar_resultados(total, oncologico, control, "SERVICIOALTA")

[SERVICIOALTA] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SERVICIOALTA: 89 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SERVICIOALTA):'

,2019,2020,2021,2022,2023,2024
CIRUGIA,141858 (12.3%),102697 (13.1%),93323 (11.4%),102292 (11.0%),107584 (10.3%),109985 (10.1%)
MEDICINA,121845 (10.6%),110431 (14.1%),107134 (13.1%),99776 (10.7%),103103 (9.9%),115096 (10.6%)
UNIDAD DE RECUPERACION DE PABELLONES (CENTRAL Y CMA),104023 (9.0%),50003 (6.4%),63777 (7.8%),100663 (10.8%),129020 (12.4%),147403 (13.6%)
OBSTETRICIA,91501 (7.9%),74212 (9.5%),71878 (8.8%),76691 (8.2%),79049 (7.6%),71136 (6.6%)
PEDIATRIA,65634 (5.7%),31601 (4.0%),34239 (4.2%),45146 (4.8%),52653 (5.1%),50154 (4.6%)
...,...,...,...,...,...,...
PSIQUIATRIA FORENSE MEDIANA COMPLEJIDAD,20 (0.0%),19 (0.0%),14 (0.0%),25 (0.0%),9 (0.0%),14 (0.0%)
PSIQUIATRIA FORENSE ALTA COMPLEJIDAD,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),13 (0.0%)
CIRUGIA TORAX,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CARDIOCIRUGIA (INFANTIL),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA MEDIANA ESTADIA,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SERVICIOALTA):'

,2019,2020,2021,2022,2023,2024
CIRUGIA,18866 (19.3%),14856 (22.9%),14511 (21.4%),15603 (20.0%),16778 (18.5%),16793 (16.9%)
MEDICINA,14469 (14.8%),11997 (18.5%),9792 (14.4%),10940 (14.0%),12953 (14.3%),15491 (15.6%)
ONCOLOGIA,17156 (17.5%),7674 (11.8%),6431 (9.5%),6457 (8.3%),7269 (8.0%),7774 (7.8%)
GINECOLOGIA,6705 (6.9%),5340 (8.2%),6061 (8.9%),6931 (8.9%),7620 (8.4%),7775 (7.8%)
UNIDAD DE RECUPERACION DE PABELLONES (CENTRAL Y CMA),3905 (4.0%),2494 (3.8%),3608 (5.3%),4863 (6.2%),6078 (6.7%),6811 (6.9%)
...,...,...,...,...,...,...
UNIDAD DE CUIDADOS INTENSIVOS NEONATOLOGIA,2 (0.0%),0 (0.0%),3 (0.0%),4 (0.0%),1 (0.0%),1 (0.0%)
NEONATOLOGIA CUNAS,0 (0.0%),2 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),1 (0.0%)
MEDICINA FISICA Y REHABILITACION,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),4 (0.0%)
UNIDAD DE TRATAMIENTO INTERMEDIO QUEMADOS,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
AREANEONATOLOGIA CUIDADOS BASICOS,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SERVICIOALTA):'

,2019,2020,2021,2022,2023,2024
MEDICINA,107376 (10.2%),98434 (13.7%),97342 (13.0%),88836 (10.4%),90150 (9.5%),99605 (10.1%)
UNIDAD DE RECUPERACION DE PABELLONES (CENTRAL Y CMA),100118 (9.5%),47509 (6.6%),60169 (8.0%),95800 (11.2%),122942 (13.0%),140592 (14.2%)
CIRUGIA,122992 (11.7%),87841 (12.3%),78812 (10.5%),86689 (10.1%),90806 (9.6%),93192 (9.4%)
OBSTETRICIA,91360 (8.7%),74050 (10.3%),71593 (9.6%),76465 (8.9%),78652 (8.3%),70655 (7.2%)
PEDIATRIA,63354 (6.0%),29729 (4.1%),32297 (4.3%),43518 (5.1%),51023 (5.4%),48527 (4.9%)
...,...,...,...,...,...,...
AREA DE TRANSPLANTE INFANTIL,5 (0.0%),9 (0.0%),3 (0.0%),5 (0.0%),2 (0.0%),5 (0.0%)
PSIQUIATRIA FORENSE ALTA COMPLEJIDAD,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),13 (0.0%)
CIRUGIA TORAX,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
CARDIOCIRUGIA (INFANTIL),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
PSIQUIATRIA MEDIANA ESTADIA,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **17. Datos Neonatales (CONDICIONDEALTANEONATO, SEXORN, RNESTADO)**
- **Tipo de variable**: Clínica / Hospitalaria.
- **Descripción**: Bloque de variables repetidas (hasta 4 para partos múltiples) que registran la supervivencia, sexo y condición fisiológica de un recién nacido al alta.
- **Cardinalidad**: Muy Baja (1 a 13 categorías útiles, pero con más del 99% de los registros agrupados en nulos o ceros).
- **Veredicto**: **Descartar por varianza nula y contexto clínico**. La extracción de frecuencias demuestra que los valores válidos en estas columnas son estadísticamente inexistentes para la población de interés (los nulos alcanzan el 99.9% en la cohorte oncológica en todos los años). Un parto en una paciente con un diagnóstico principal de neoplasia maligna activa es un evento clínico extremadamente atípico (*outlier* severo). Retener estas 12 columnas (4 de condición, 4 de sexo, 4 de estado) inyectaría vectores de ceros absolutos al conjunto de datos, no aportando información discriminativa para las variables de severidad, mortalidad o consumo de recursos en oncología.

In [20]:
for i in range(1, 5):
    total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,f"CONDICIONDEALTANEONATO{i}")
    mostrar_resultados(total, oncologico, control, f"CONDICIONDEALTANEONATO{i}")
    total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,f"SEXORN{i}")
    mostrar_resultados(total, oncologico, control, f"SEXORN{i}")
    total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,f"RN{i}ESTADO")
    mostrar_resultados(total, oncologico, control, f"RN{i}ESTADO")

[CONDICIONDEALTANEONATO1] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad CONDICIONDEALTANEONATO1: 2 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (CONDICIONDEALTANEONATO1):'

,2019,2020,2021,2022,2023,2024
NULOS,1022454 (88.8%),781910 (100.0%),816909 (100.0%),932837 (100.0%),1039587 (100.0%),1085813 (100.0%)
VIVO,128156 (11.1%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
FALLECIDO,788 (0.1%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (CONDICIONDEALTANEONATO1):'

,2019,2020,2021,2022,2023,2024
NULOS,97754 (99.9%),64926 (100.0%),67926 (100.0%),78069 (100.0%),90715 (100.0%),99153 (100.0%)
VIVO,74 (0.1%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
FALLECIDO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (CONDICIONDEALTANEONATO1):'

,2019,2020,2021,2022,2023,2024
NULOS,924700 (87.8%),716984 (100.0%),748983 (100.0%),854768 (100.0%),948872 (100.0%),986660 (100.0%)
VIVO,128082 (12.2%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
FALLECIDO,787 (0.1%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[SEXORN1] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SEXORN1: 2 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SEXORN1):'

,2019,2020,2021,2022,2023,2024
NULOS,1022764 (88.8%),672840 (86.1%),720978 (88.3%),822893 (88.2%),932854 (89.7%),988785 (91.1%)
HOMBRE,65781 (5.7%),55608 (7.1%),48607 (6.0%),55559 (6.0%),54061 (5.2%),48848 (4.5%)
MUJER,62719 (5.4%),53376 (6.8%),47263 (5.8%),54319 (5.8%),52621 (5.1%),48133 (4.4%)
DESCONOCIDO,134 (0.0%),87 (0.0%),61 (0.0%),66 (0.0%),51 (0.0%),47 (0.0%)

'2. Frecuencia para cohorte oncológica (SEXORN1):'

,2019,2020,2021,2022,2023,2024
NULOS,97754 (99.9%),64852 (99.9%),67837 (99.9%),77947 (99.8%),90599 (99.9%),99031 (99.9%)
MUJER,35 (0.0%),41 (0.1%),45 (0.1%),63 (0.1%),60 (0.1%),55 (0.1%)
HOMBRE,39 (0.0%),33 (0.1%),44 (0.1%),58 (0.1%),56 (0.1%),67 (0.1%)
DESCONOCIDO,1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SEXORN1):'

,2019,2020,2021,2022,2023,2024
NULOS,925010 (87.8%),607988 (84.8%),653141 (87.2%),744946 (87.2%),842255 (88.8%),889754 (90.2%)
HOMBRE,65742 (6.2%),55575 (7.8%),48563 (6.5%),55501 (6.5%),54005 (5.7%),48781 (4.9%)
MUJER,62684 (5.9%),53335 (7.4%),47218 (6.3%),54256 (6.3%),52561 (5.5%),48078 (4.9%)
DESCONOCIDO,133 (0.0%),87 (0.0%),61 (0.0%),65 (0.0%),51 (0.0%),47 (0.0%)

[RN1ESTADO] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad RN1ESTADO: 13 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (RN1ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,18 (0.0%),426794 (54.6%),720421 (88.2%),821837 (88.1%),931844 (89.6%),987927 (91.0%)
0.0,1023287 (88.9%),246826 (31.6%),723 (0.1%),795 (0.1%),751 (0.1%),620 (0.1%)
9.0,90315 (7.8%),77684 (9.9%),68719 (8.4%),77929 (8.4%),75616 (7.3%),68404 (6.3%)
10.0,30581 (2.7%),24265 (3.1%),20779 (2.5%),25068 (2.7%),23981 (2.3%),21897 (2.0%)
8.0,4883 (0.4%),4346 (0.6%),4073 (0.5%),4774 (0.5%),4907 (0.5%),4722 (0.4%)
7.0,950 (0.1%),758 (0.1%),861 (0.1%),958 (0.1%),993 (0.1%),861 (0.1%)
6.0,451 (0.0%),417 (0.1%),364 (0.0%),442 (0.0%),440 (0.0%),399 (0.0%)
5.0,258 (0.0%),233 (0.0%),250 (0.0%),260 (0.0%),267 (0.0%),235 (0.0%)
1.0,294 (0.0%),264 (0.0%),268 (0.0%),215 (0.0%),231 (0.0%),197 (0.0%)
11.0,4 (0.0%),0 (0.0%),133 (0.0%),217 (0.0%),252 (0.0%),249 (0.0%)
4.0,145 (0.0%),148 (0.0%),129 (0.0%),129 (0.0%),137 (0.0%),127 (0.0%)
3.0,112 (0.0%),88 (0.0%),98 (0.0%),132 (0.0%),101 (0.0%),87 (0.0%)
2.0,99 (0.0%),88 (0.0%),91 (0.0%),81 (0.0%),67 (0.0%),88 (0.0%)
-1.0,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (RN1ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,0 (0.0%),40599 (62.5%),67837 (99.9%),77947 (99.8%),90599 (99.9%),99031 (99.9%)
0.0,97755 (99.9%),24255 (37.4%),5 (0.0%),2 (0.0%),1 (0.0%),3 (0.0%)
9.0,46 (0.0%),52 (0.1%),61 (0.1%),85 (0.1%),85 (0.1%),71 (0.1%)
10.0,22 (0.0%),11 (0.0%),16 (0.0%),26 (0.0%),13 (0.0%),32 (0.0%)
8.0,3 (0.0%),6 (0.0%),5 (0.0%),6 (0.0%),8 (0.0%),9 (0.0%)
6.0,1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),3 (0.0%),1 (0.0%)
7.0,0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),3 (0.0%)
1.0,1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),3 (0.0%),0 (0.0%)
5.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
3.0,0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%),0 (0.0%)
2.0,1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
4.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%)

'3. Frecuencia para cohorte control (RN1ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,18 (0.0%),386195 (53.9%),652584 (87.1%),743890 (87.0%),841245 (88.7%),888896 (90.1%)
0.0,925532 (87.8%),222571 (31.0%),718 (0.1%),793 (0.1%),750 (0.1%),617 (0.1%)
9.0,90269 (8.6%),77632 (10.8%),68658 (9.2%),77844 (9.1%),75531 (8.0%),68333 (6.9%)
10.0,30559 (2.9%),24254 (3.4%),20763 (2.8%),25042 (2.9%),23968 (2.5%),21865 (2.2%)
8.0,4880 (0.5%),4340 (0.6%),4068 (0.5%),4768 (0.6%),4899 (0.5%),4713 (0.5%)
7.0,950 (0.1%),757 (0.1%),860 (0.1%),958 (0.1%),992 (0.1%),858 (0.1%)
6.0,450 (0.0%),417 (0.1%),363 (0.0%),442 (0.1%),437 (0.0%),398 (0.0%)
5.0,258 (0.0%),232 (0.0%),250 (0.0%),260 (0.0%),266 (0.0%),234 (0.0%)
1.0,293 (0.0%),264 (0.0%),268 (0.0%),214 (0.0%),228 (0.0%),197 (0.0%)
11.0,4 (0.0%),0 (0.0%),133 (0.0%),217 (0.0%),252 (0.0%),249 (0.0%)
4.0,145 (0.0%),148 (0.0%),129 (0.0%),129 (0.0%),137 (0.0%),125 (0.0%)
3.0,112 (0.0%),87 (0.0%),98 (0.0%),131 (0.0%),100 (0.0%),87 (0.0%)
2.0,98 (0.0%),88 (0.0%),91 (0.0%),80 (0.0%),67 (0.0%),88 (0.0%)
-1.0,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[CONDICIONDEALTANEONATO2] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad CONDICIONDEALTANEONATO2: 2 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (CONDICIONDEALTANEONATO2):'

,2019,2020,2021,2022,2023,2024
NULOS,1149822 (99.9%),781911 (100.0%),816909 (100.0%),932837 (100.0%),1039587 (100.0%),1085813 (100.0%)
VIVO,1534 (0.1%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
FALLECIDO,42 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (CONDICIONDEALTANEONATO2):'

,2019,2020,2021,2022,2023,2024
NULOS,97829 (100.0%),64926 (100.0%),67926 (100.0%),78069 (100.0%),90715 (100.0%),99153 (100.0%)

'3. Frecuencia para cohorte control (CONDICIONDEALTANEONATO2):'

,2019,2020,2021,2022,2023,2024
NULOS,1051993 (99.9%),716985 (100.0%),748983 (100.0%),854768 (100.0%),948872 (100.0%),986660 (100.0%)
VIVO,1534 (0.1%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
FALLECIDO,42 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[SEXORN2] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SEXORN2: 2 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SEXORN2):'

,2019,2020,2021,2022,2023,2024
NULOS,1149824 (99.9%),780494 (99.8%),815547 (99.8%),931312 (99.8%),1038192 (99.9%),1084495 (99.9%)
MUJER,757 (0.1%),695 (0.1%),678 (0.1%),802 (0.1%),712 (0.1%),670 (0.1%)
HOMBRE,811 (0.1%),712 (0.1%),681 (0.1%),717 (0.1%),679 (0.1%),646 (0.1%)
DESCONOCIDO,6 (0.0%),10 (0.0%),3 (0.0%),6 (0.0%),4 (0.0%),2 (0.0%)

'2. Frecuencia para cohorte oncológica (SEXORN2):'

,2019,2020,2021,2022,2023,2024
NULOS,97829 (100.0%),64923 (100.0%),67924 (100.0%),78069 (100.0%),90711 (100.0%),99153 (100.0%)
MUJER,0 (0.0%),3 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%)
HOMBRE,0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SEXORN2):'

,2019,2020,2021,2022,2023,2024
NULOS,1051995 (99.9%),715571 (99.8%),747623 (99.8%),853243 (99.8%),947481 (99.9%),985342 (99.9%)
MUJER,757 (0.1%),692 (0.1%),678 (0.1%),802 (0.1%),710 (0.1%),670 (0.1%)
HOMBRE,811 (0.1%),712 (0.1%),679 (0.1%),717 (0.1%),677 (0.1%),646 (0.1%)
DESCONOCIDO,6 (0.0%),10 (0.0%),3 (0.0%),6 (0.0%),4 (0.0%),2 (0.0%)

[RN2ESTADO] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad RN2ESTADO: 12 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (RN2ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,19 (0.0%),494895 (63.3%),815547 (99.8%),931312 (99.8%),1038192 (99.9%),1084495 (99.9%)
0.0,1149844 (99.9%),285639 (36.5%),33 (0.0%),36 (0.0%),26 (0.0%),19 (0.0%)
9.0,1074 (0.1%),935 (0.1%),922 (0.1%),1010 (0.1%),936 (0.1%),856 (0.1%)
10.0,242 (0.0%),203 (0.0%),188 (0.0%),225 (0.0%),204 (0.0%),192 (0.0%)
8.0,144 (0.0%),154 (0.0%),140 (0.0%),163 (0.0%),142 (0.0%),158 (0.0%)
7.0,30 (0.0%),36 (0.0%),31 (0.0%),36 (0.0%),29 (0.0%),34 (0.0%)
1.0,12 (0.0%),11 (0.0%),19 (0.0%),17 (0.0%),23 (0.0%),25 (0.0%)
6.0,11 (0.0%),10 (0.0%),20 (0.0%),16 (0.0%),12 (0.0%),17 (0.0%)
5.0,9 (0.0%),11 (0.0%),4 (0.0%),5 (0.0%),9 (0.0%),4 (0.0%)
4.0,4 (0.0%),3 (0.0%),3 (0.0%),11 (0.0%),7 (0.0%),7 (0.0%)
3.0,7 (0.0%),7 (0.0%),1 (0.0%),3 (0.0%),4 (0.0%),3 (0.0%)
2.0,2 (0.0%),7 (0.0%),1 (0.0%),2 (0.0%),1 (0.0%),3 (0.0%)
11.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (RN2ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,0 (0.0%),40640 (62.6%),67924 (100.0%),78069 (100.0%),90711 (100.0%),99153 (100.0%)
0.0,97829 (100.0%),24283 (37.4%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
9.0,0 (0.0%),3 (0.0%),0 (0.0%),0 (0.0%),3 (0.0%),0 (0.0%)
10.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
8.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (RN2ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,19 (0.0%),454255 (63.4%),747623 (99.8%),853243 (99.8%),947481 (99.9%),985342 (99.9%)
0.0,1052015 (99.9%),261356 (36.5%),33 (0.0%),36 (0.0%),26 (0.0%),19 (0.0%)
9.0,1074 (0.1%),932 (0.1%),922 (0.1%),1010 (0.1%),933 (0.1%),856 (0.1%)
10.0,242 (0.0%),203 (0.0%),187 (0.0%),225 (0.0%),203 (0.0%),192 (0.0%)
8.0,144 (0.0%),154 (0.0%),139 (0.0%),163 (0.0%),142 (0.0%),158 (0.0%)
7.0,30 (0.0%),36 (0.0%),31 (0.0%),36 (0.0%),29 (0.0%),34 (0.0%)
1.0,12 (0.0%),11 (0.0%),19 (0.0%),17 (0.0%),23 (0.0%),25 (0.0%)
6.0,11 (0.0%),10 (0.0%),20 (0.0%),16 (0.0%),12 (0.0%),17 (0.0%)
5.0,9 (0.0%),11 (0.0%),4 (0.0%),5 (0.0%),9 (0.0%),4 (0.0%)
4.0,4 (0.0%),3 (0.0%),3 (0.0%),11 (0.0%),7 (0.0%),7 (0.0%)
3.0,7 (0.0%),7 (0.0%),1 (0.0%),3 (0.0%),4 (0.0%),3 (0.0%)
2.0,2 (0.0%),7 (0.0%),1 (0.0%),2 (0.0%),1 (0.0%),3 (0.0%)
11.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%)

[CONDICIONDEALTANEONATO3] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad CONDICIONDEALTANEONATO3: 0 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (CONDICIONDEALTANEONATO3):'

,2019,2020,2021,2022,2023,2024
NULOS,1151398 (100.0%),781911 (100.0%),816909 (100.0%),932837 (100.0%),1039587 (100.0%),1085813 (100.0%)

'2. Frecuencia para cohorte oncológica (CONDICIONDEALTANEONATO3):'

,2019,2020,2021,2022,2023,2024
NULOS,97829 (100.0%),64926 (100.0%),67926 (100.0%),78069 (100.0%),90715 (100.0%),99153 (100.0%)

'3. Frecuencia para cohorte control (CONDICIONDEALTANEONATO3):'

,2019,2020,2021,2022,2023,2024
NULOS,1053569 (100.0%),716985 (100.0%),748983 (100.0%),854768 (100.0%),948872 (100.0%),986660 (100.0%)

[SEXORN3] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SEXORN3: 2 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SEXORN3):'

,2019,2020,2021,2022,2023,2024
NULOS,1151385 (100.0%),781897 (100.0%),816900 (100.0%),932826 (100.0%),1039574 (100.0%),1085798 (100.0%)
MUJER,5 (0.0%),11 (0.0%),3 (0.0%),6 (0.0%),8 (0.0%),5 (0.0%)
HOMBRE,7 (0.0%),2 (0.0%),6 (0.0%),5 (0.0%),5 (0.0%),10 (0.0%)
DESCONOCIDO,1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SEXORN3):'

,2019,2020,2021,2022,2023,2024
NULOS,97829 (100.0%),64926 (100.0%),67926 (100.0%),78069 (100.0%),90714 (100.0%),99153 (100.0%)
MUJER,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (SEXORN3):'

,2019,2020,2021,2022,2023,2024
NULOS,1053556 (100.0%),716971 (100.0%),748974 (100.0%),854757 (100.0%),948860 (100.0%),986645 (100.0%)
MUJER,5 (0.0%),11 (0.0%),3 (0.0%),6 (0.0%),7 (0.0%),5 (0.0%)
HOMBRE,7 (0.0%),2 (0.0%),6 (0.0%),5 (0.0%),5 (0.0%),10 (0.0%)
DESCONOCIDO,1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[RN3ESTADO] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad RN3ESTADO: 8 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (RN3ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,19 (0.0%),495805 (63.4%),816900 (100.0%),932826 (100.0%),1039574 (100.0%),1085798 (100.0%)
0.0,1151367 (100.0%),286093 (36.6%),0 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%)
9.0,8 (0.0%),9 (0.0%),3 (0.0%),9 (0.0%),7 (0.0%),6 (0.0%)
8.0,3 (0.0%),3 (0.0%),4 (0.0%),2 (0.0%),3 (0.0%),4 (0.0%)
10.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
6.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
7.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
5.0,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
4.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (RN3ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,0 (0.0%),40642 (62.6%),67926 (100.0%),78069 (100.0%),90714 (100.0%),99153 (100.0%)
0.0,97829 (100.0%),24284 (37.4%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
9.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (RN3ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,19 (0.0%),455163 (63.5%),748974 (100.0%),854757 (100.0%),948860 (100.0%),986645 (100.0%)
0.0,1053538 (100.0%),261809 (36.5%),0 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%)
9.0,8 (0.0%),9 (0.0%),3 (0.0%),9 (0.0%),6 (0.0%),6 (0.0%)
8.0,3 (0.0%),3 (0.0%),4 (0.0%),2 (0.0%),3 (0.0%),4 (0.0%)
10.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
6.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
7.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
5.0,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
4.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[CONDICIONDEALTANEONATO4] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad CONDICIONDEALTANEONATO4: 0 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (CONDICIONDEALTANEONATO4):'

,2019,2020,2021,2022,2023,2024
NULOS,1151398 (100.0%),781911 (100.0%),816909 (100.0%),932837 (100.0%),1039587 (100.0%),1085813 (100.0%)

'2. Frecuencia para cohorte oncológica (CONDICIONDEALTANEONATO4):'

,2019,2020,2021,2022,2023,2024
NULOS,97829 (100.0%),64926 (100.0%),67926 (100.0%),78069 (100.0%),90715 (100.0%),99153 (100.0%)

'3. Frecuencia para cohorte control (CONDICIONDEALTANEONATO4):'

,2019,2020,2021,2022,2023,2024
NULOS,1053569 (100.0%),716985 (100.0%),748983 (100.0%),854768 (100.0%),948872 (100.0%),986660 (100.0%)

[SEXORN4] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad SEXORN4: 1 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (SEXORN4):'

,2019,2020,2021,2022,2023,2024
NULOS,1151397 (100.0%),781910 (100.0%),816909 (100.0%),932837 (100.0%),1039587 (100.0%),1085813 (100.0%)
DESCONOCIDO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
MUJER,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (SEXORN4):'

,2019,2020,2021,2022,2023,2024
NULOS,97829 (100.0%),64926 (100.0%),67926 (100.0%),78069 (100.0%),90715 (100.0%),99153 (100.0%)

'3. Frecuencia para cohorte control (SEXORN4):'

,2019,2020,2021,2022,2023,2024
NULOS,1053568 (100.0%),716984 (100.0%),748983 (100.0%),854768 (100.0%),948872 (100.0%),986660 (100.0%)
DESCONOCIDO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
MUJER,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[RN4ESTADO] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad RN4ESTADO: 2 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (RN4ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,19 (0.0%),495815 (63.4%),816909 (100.0%),932837 (100.0%),1039587 (100.0%),1085813 (100.0%)
0.0,1151379 (100.0%),286095 (36.6%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
9.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (RN4ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,0 (0.0%),40642 (62.6%),67926 (100.0%),78069 (100.0%),90715 (100.0%),99153 (100.0%)
0.0,97829 (100.0%),24284 (37.4%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (RN4ESTADO):'

,2019,2020,2021,2022,2023,2024
NULOS,19 (0.0%),455173 (63.5%),748983 (100.0%),854768 (100.0%),948872 (100.0%),986660 (100.0%)
0.0,1053550 (100.0%),261811 (36.5%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
9.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **18. Diagnóstico Principal de Ingreso (DIAGNOSTICO1)**
- **Tipo de variable**: Clínica.
- **Descripción**: Representa la condición clínica principal que motiva el ingreso hospitalario del paciente al episodio asistencial.
- **Cardinalidad**: Muy alta en su forma nativa (9.711 categorías únicas a lo largo del periodo), reducida a 16 macro-categorías en la etapa de clasificación.
- **Veredicto**: **Retener y Agrupar (`CATEGORIA_CANCER`)**. Mantener los códigos CIE-10 nativos generaría una matriz inmanejable y dispersa. La estrategia implementada de agrupar los códigos oncológicos (C00-C97) en 15 macro-categorías topográficas (más el grupo control `SIN_CANCER`) es la solución óptima. Reduce drásticamente la dimensionalidad de 9.711 a 16, capturando perfectamente el motivo basal del episodio para perfilar al paciente, sin diluir el peso de la variable en los algoritmos de selección de características.

### **19. Diagnósticos Secundarios (DIAGNOSTICO2 al DIAGNOSTICO35)**
- **Tipo de variable**: Clínica.
- **Descripción**: Códigos CIE-10 adicionales que documentan comorbilidades preexistentes (ej. Hipertensión I10, Diabetes E11.9), metástasis en otros órganos, o complicaciones clínicas surgidas durante la hospitalización.
- **Cardinalidad**: Extrema y decreciente (inicia en 15.300 categorías únicas en el diagnóstico 2 y desciende hasta 799 en el diagnóstico 35).
- **Veredicto**: **Descartar columnas originales y Sintetizar**. El análisis masivo revela que la tasa de valores nulos escala aceleradamente: roza el 12-18% en el `DIAGNOSTICO2`, supera el 50% en el `DIAGNOSTICO5` y alcanza el 99-100% desde el `DIAGNOSTICO15` en adelante. Aplicar *One-Hot Encoding* a estas 34 columnas inyectaría más de 100.000 nuevas dimensiones al conjunto de datos, compuestas casi en su totalidad por ceros. Esto provocaría el colapso computacional y la pérdida de capacidad de generalización del modelo (maldición de la dimensionalidad). Su valor clínico se rescatará exclusivamente a través de variables derivadas.

---

### **Variables Derivadas de los Diagnósticos (Ingeniería de Características)**

Para capturar la riqueza clínica de las 35 columnas de diagnóstico sin comprometer la estabilidad matemática del conjunto de datos, se generarán las siguientes variables sintetizadas:

### **a) Categoría Oncológica (CATEGORIA_CANCER)**
- **Tipo de variable**: Clínica Derivada (Categórica).
- **Descripción**: Clasificación topográfica del tumor maligno del paciente. Agrupa los códigos CIE-10 nativos (C00-C97) encontrados durante el escaneo de diagnósticos.
- **Cardinalidad**: Baja (15 macro-categorías oncológicas + 1 categoría `SIN_CANCER`).
- **Veredicto**: **Crear e Incluir**. Es la variable estructural del estudio. Transforma los cientos de códigos oncológicos específicos en 15 sistemas anatómicos manejables. Su creación permite segmentar a la población y habilitar a los algoritmos predictivos para evaluar cómo el tipo específico de cáncer (ej. digestivo vs. respiratorio) altera el perfil de riesgo y el consumo de recursos frente al grupo de control.

### **b) Tipo de Diagnóstico Oncológico (TIPO_DIAGNOSTICO_ONCO)**
- **Tipo de variable**: Clínica Derivada (Categórica).
- **Descripción**: Indicador que clasifica la jerarquía del hallazgo oncológico durante el episodio hospitalario.
- **Cardinalidad**: Muy Baja (3 categorías: `PRINCIPAL`, `SECUNDARIO`, `SIN_CANCER`).
- **Veredicto**: **Crear e Incluir**. Esta variable corrige un sesgo metodológico crítico. Diferencia a los pacientes que ingresaron al hospital *por* su cáncer (`PRINCIPAL` - Diagnóstico 1) de aquellos que ingresaron por otro motivo pero que *padecen* un cáncer activo que complica su cuadro (`SECUNDARIO` - Diagnóstico 2 al 35). Esta distinción es vital para que el selector de características pueda aislar el impacto del tumor como comorbilidad agravante.

### **c) Carga Oncológica (CARGA_ONCOLOGICA)**
- **Tipo de variable**: Clínica Derivada (Numérica discreta).
- **Descripción**: Conteo del total de diagnósticos que inician con la letra "C" (neoplasias malignas, C00-C97) a lo largo de las 35 columnas para un mismo paciente.
- **Cardinalidad**: Baja (rango numérico acotado).
- **Veredicto**: **Crear e Incluir**. Actúa como un proxy clínico sólido de la diseminación de la enfermedad (metástasis) o la presencia de múltiples tumores primarios sincronizados. Esta variable permite a los modelos medir numéricamente la extensión del cáncer, factor que impacta directamente en la severidad y el consumo de recursos.

### **d) Carga de Comorbilidades (NUM_COMORBILIDADES)**
- **Tipo de variable**: Clínica Derivada (Numérica discreta).
- **Descripción**: Conteo del total de códigos CIE-10 que NO inician con la letra "C" (patologías no oncológicas) registrados entre los diagnósticos 2 y 35.
- **Cardinalidad**: Baja (rango numérico acotado).
- **Veredicto**: **Crear e Incluir**. En oncología, el desenlace clínico no depende exclusivamente del tumor. Las comorbilidades descompensadas (ej. fallas renales, cardiovasculares o metabólicas) agravan la estadía. Cuantificar este volumen de patologías secundarias proporciona al algoritmo una métrica directa de la fragilidad sistémica basal del paciente.

### **e) Comorbilidad Principal (COMORBILIDAD_PRINCIPAL)**
- **Tipo de variable**: Clínica Derivada (Categórica).
- **Descripción**: Identificación del primer código CIE-10 no oncológico (que no empieza con "C") registrado en los diagnósticos secundarios, representando la patología crónica o complicación más relevante del paciente.
- **Cardinalidad**: Moderada (Top N agrupado).
- **Veredicto**: **Crear y Agrupar**. Para evitar reintroducir el problema de la alta dimensionalidad, se identificará únicamente el *Top 10 o Top 15* de las enfermedades crónicas más prevalentes extraídas de las matrices de frecuencia (como Hipertensión Arterial [I10] o Diabetes Mellitus [E11.9]). El resto de las afecciones minoritarias se colapsarán bajo la macro-categoría `OTRA_COMORBILIDAD`, y los pacientes sin patologías extra se etiquetarán como `SIN_COMORBILIDAD`.

In [21]:
for i in range(1, 36):
    total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,f"DIAGNOSTICO{i}")
    mostrar_resultados(total, oncologico, control, f"DIAGNOSTICO{i}")

[DIAGNOSTICO1] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO1: 9711 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO1):'

,2019,2020,2021,2022,2023,2024
H26.9,30377 (2.6%),13783 (1.8%),17794 (2.2%),26595 (2.9%),31612 (3.0%),33390 (3.1%)
K80.2,23796 (2.1%),12115 (1.5%),12476 (1.5%),18997 (2.0%),21126 (2.0%),20717 (1.9%)
U07.1,0 (0.0%),33047 (4.2%),55156 (6.8%),13161 (1.4%),3128 (0.3%),2153 (0.2%)
K35.8,20401 (1.8%),17581 (2.2%),16999 (2.1%),16042 (1.7%),15863 (1.5%),16638 (1.5%)
O80.0,23911 (2.1%),19765 (2.5%),15073 (1.8%),14000 (1.5%),13278 (1.3%),9472 (0.9%)
...,...,...,...,...,...,...
A00.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z97.1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z97.2,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z97.3,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z97.4,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO1):'

,2019,2020,2021,2022,2023,2024
Z51.1,23238 (23.8%),8163 (12.6%),7050 (10.4%),7171 (9.2%),8061 (8.9%),9262 (9.3%)
C50.9,4228 (4.3%),2788 (4.3%),3224 (4.7%),4348 (5.6%),4753 (5.2%),4660 (4.7%)
C73,1513 (1.5%),1238 (1.9%),1460 (2.1%),1873 (2.4%),2128 (2.3%),2126 (2.1%)
C16.9,1946 (2.0%),1413 (2.2%),1399 (2.1%),1699 (2.2%),1852 (2.0%),1907 (1.9%)
C61,1949 (2.0%),1214 (1.9%),1283 (1.9%),1595 (2.0%),2024 (2.2%),2147 (2.2%)
...,...,...,...,...,...,...
Z71.3,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z71.9,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A05.8,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A07.1,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
H35.2,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO1):'

,2019,2020,2021,2022,2023,2024
H26.9,30103 (2.9%),13678 (1.9%),17644 (2.4%),26235 (3.1%),31174 (3.3%),32952 (3.3%)
K80.2,23630 (2.2%),12002 (1.7%),12366 (1.7%),18784 (2.2%),20871 (2.2%),20494 (2.1%)
K35.8,20356 (1.9%),17532 (2.4%),16925 (2.3%),15977 (1.9%),15778 (1.7%),16534 (1.7%)
U07.1,0 (0.0%),32053 (4.5%),53767 (7.2%),12184 (1.4%),2870 (0.3%),1976 (0.2%)
O80.0,23902 (2.3%),19760 (2.8%),15066 (2.0%),13995 (1.6%),13275 (1.4%),9469 (1.0%)
...,...,...,...,...,...,...
T23.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
M12.41,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z92.6,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z90.8,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z96.9,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO2] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO2: 15300 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO2):'

,2019,2020,2021,2022,2023,2024
NULOS,200588 (17.4%),101149 (12.9%),100467 (12.3%),125543 (13.5%),133709 (12.9%),133658 (12.3%)
I10,87858 (7.6%),46862 (6.0%),50092 (6.1%),65343 (7.0%),75160 (7.2%),79048 (7.3%)
Z37.0,27529 (2.4%),22390 (2.9%),16574 (2.0%),16715 (1.8%),14784 (1.4%),12295 (1.1%)
J12.8,197 (0.0%),31363 (4.0%),52681 (6.4%),11179 (1.2%),3059 (0.3%),2529 (0.2%)
E11.9,20071 (1.7%),10286 (1.3%),11926 (1.5%),14850 (1.6%),17583 (1.7%),18182 (1.7%)
...,...,...,...,...,...,...
M23.10,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
W23.18,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
W23.14,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A01.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z94.6,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO2):'

,2019,2020,2021,2022,2023,2024
I10,7235 (7.4%),4921 (7.6%),5537 (8.2%),6879 (8.8%),7798 (8.6%),8378 (8.4%)
NULOS,6508 (6.7%),4553 (7.0%),4841 (7.1%),5577 (7.1%),5931 (6.5%),5433 (5.5%)
C91.0,3741 (3.8%),1846 (2.8%),2051 (3.0%),1919 (2.5%),2319 (2.6%),2056 (2.1%)
C50.9,5265 (5.4%),813 (1.3%),744 (1.1%),981 (1.3%),1112 (1.2%),1269 (1.3%)
E11.9,1547 (1.6%),947 (1.5%),1303 (1.9%),1580 (2.0%),1719 (1.9%),1944 (2.0%)
...,...,...,...,...,...,...
B88.9,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B96.6,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
R49.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A02.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
Z97.4,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO2):'

,2019,2020,2021,2022,2023,2024
NULOS,194080 (18.4%),96596 (13.5%),95626 (12.8%),119966 (14.0%),127778 (13.5%),128225 (13.0%)
I10,80623 (7.7%),41941 (5.8%),44555 (5.9%),58464 (6.8%),67362 (7.1%),70670 (7.2%)
Z37.0,27522 (2.6%),22387 (3.1%),16568 (2.2%),16711 (2.0%),14776 (1.6%),12288 (1.2%)
J12.8,195 (0.0%),30400 (4.2%),51344 (6.9%),10355 (1.2%),2849 (0.3%),2358 (0.2%)
E11.9,18524 (1.8%),9339 (1.3%),10623 (1.4%),13270 (1.6%),15864 (1.7%),16238 (1.6%)
...,...,...,...,...,...,...
X09.90,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
X09.84,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
O87.3,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A06.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z94.6,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO3] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO3: 13022 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO3):'

,2019,2020,2021,2022,2023,2024
NULOS,397057 (34.5%),209027 (26.7%),206062 (25.2%),249451 (26.7%),268293 (25.8%),266299 (24.5%)
I10,73296 (6.4%),46002 (5.9%),48966 (6.0%),55710 (6.0%),64114 (6.2%),67866 (6.3%)
E11.9,32534 (2.8%),19140 (2.4%),20424 (2.5%),25722 (2.8%),29829 (2.9%),32088 (3.0%)
Z37.0,30186 (2.6%),23602 (3.0%),18061 (2.2%),19505 (2.1%),18097 (1.7%),16172 (1.5%)
E66.9,14865 (1.3%),11951 (1.5%),15533 (1.9%),18288 (2.0%),19491 (1.9%),20475 (1.9%)
...,...,...,...,...,...,...
W55.92,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
W55.72,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
W55.29,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
W55.19,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
W55.04,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO3):'

,2019,2020,2021,2022,2023,2024
NULOS,23353 (23.9%),11579 (17.8%),11607 (17.1%),12463 (16.0%),13473 (14.9%),12736 (12.8%)
I10,8635 (8.8%),5228 (8.1%),5778 (8.5%),6505 (8.3%),7529 (8.3%),8312 (8.4%)
E11.9,3366 (3.4%),2244 (3.5%),2492 (3.7%),2912 (3.7%),3469 (3.8%),3768 (3.8%)
E03.9,1419 (1.5%),879 (1.4%),1104 (1.6%),1314 (1.7%),1542 (1.7%),1661 (1.7%)
C78.7,1670 (1.7%),1050 (1.6%),997 (1.5%),1047 (1.3%),1170 (1.3%),1453 (1.5%)
...,...,...,...,...,...,...
M87.80,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
M87.30,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M87.16,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
M87.05,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
M86.94,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO3):'

,2019,2020,2021,2022,2023,2024
NULOS,373704 (35.5%),197448 (27.5%),194455 (26.0%),236988 (27.7%),254820 (26.9%),253563 (25.7%)
I10,64661 (6.1%),40774 (5.7%),43188 (5.8%),49205 (5.8%),56585 (6.0%),59554 (6.0%)
E11.9,29168 (2.8%),16896 (2.4%),17932 (2.4%),22810 (2.7%),26360 (2.8%),28320 (2.9%)
Z37.0,30180 (2.9%),23597 (3.3%),18057 (2.4%),19495 (2.3%),18091 (1.9%),16167 (1.6%)
E66.9,14215 (1.3%),11419 (1.6%),14818 (2.0%),17503 (2.0%),18664 (2.0%),19552 (2.0%)
...,...,...,...,...,...,...
W55.29,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A03.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
F16.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
F15.4,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
K00.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[DIAGNOSTICO4] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO4: 11672 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO4):'

,2019,2020,2021,2022,2023,2024
NULOS,563596 (48.9%),313580 (40.1%),309641 (37.9%),369356 (39.6%),398948 (38.4%),395327 (36.4%)
I10,47427 (4.1%),35010 (4.5%),36280 (4.4%),38545 (4.1%),43943 (4.2%),48608 (4.5%)
E11.9,22283 (1.9%),15793 (2.0%),16856 (2.1%),18506 (2.0%),21289 (2.0%),23018 (2.1%)
Z37.0,23535 (2.0%),19705 (2.5%),16301 (2.0%),18355 (2.0%),17761 (1.7%),15109 (1.4%)
E66.9,14060 (1.2%),12053 (1.5%),16946 (2.1%),17980 (1.9%),18801 (1.8%),20205 (1.9%)
...,...,...,...,...,...,...
W20.14,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A16.4,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
H31.2,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
W20.02,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
H30.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO4):'

,2019,2020,2021,2022,2023,2024
NULOS,34637 (35.4%),18937 (29.2%),19208 (28.3%),20538 (26.3%),22400 (24.7%),21724 (21.9%)
I10,6358 (6.5%),4104 (6.3%),4335 (6.4%),4908 (6.3%),5711 (6.3%),6503 (6.6%)
E11.9,3122 (3.2%),1936 (3.0%),2125 (3.1%),2470 (3.2%),2827 (3.1%),3155 (3.2%)
Z92.4,1810 (1.9%),1178 (1.8%),1025 (1.5%),1510 (1.9%),1901 (2.1%),1897 (1.9%)
Z92.2,2040 (2.1%),1116 (1.7%),1204 (1.8%),1350 (1.7%),1676 (1.8%),1786 (1.8%)
...,...,...,...,...,...,...
A28.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A19.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A17.9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A17.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A16.3,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO4):'

,2019,2020,2021,2022,2023,2024
NULOS,528959 (50.2%),294643 (41.1%),290433 (38.8%),348818 (40.8%),376548 (39.7%),373603 (37.9%)
I10,41069 (3.9%),30906 (4.3%),31945 (4.3%),33637 (3.9%),38232 (4.0%),42105 (4.3%)
Z37.0,23525 (2.2%),19695 (2.7%),16297 (2.2%),18344 (2.1%),17754 (1.9%),15107 (1.5%)
E11.9,19161 (1.8%),13857 (1.9%),14731 (2.0%),16036 (1.9%),18462 (1.9%),19863 (2.0%)
E66.9,13286 (1.3%),11510 (1.6%),16098 (2.1%),17047 (2.0%),17854 (1.9%),19151 (1.9%)
...,...,...,...,...,...,...
A39.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
V05.99,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
V06.01,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
V06.99,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
V09.19,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[DIAGNOSTICO5] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO5: 10663 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO5):'

,2019,2020,2021,2022,2023,2024
NULOS,711184 (61.8%),413821 (52.9%),408531 (50.0%),483242 (51.8%),525141 (50.5%),522303 (48.1%)
I10,30349 (2.6%),24164 (3.1%),25232 (3.1%),27394 (2.9%),31275 (3.0%),34584 (3.2%)
Z37.0,17467 (1.5%),15520 (2.0%),14134 (1.7%),16798 (1.8%),16500 (1.6%),14601 (1.3%)
Z92.2,16413 (1.4%),9549 (1.2%),11049 (1.4%),13006 (1.4%),17217 (1.7%),18867 (1.7%)
E11.9,14076 (1.2%),11506 (1.5%),12096 (1.5%),12794 (1.4%),14600 (1.4%),16376 (1.5%)
...,...,...,...,...,...,...
Q01.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
P96.3,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
P95,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
P94.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
B26.8,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO5):'

,2019,2020,2021,2022,2023,2024
NULOS,46136 (47.2%),26828 (41.3%),27130 (39.9%),29299 (37.5%),31777 (35.0%),31731 (32.0%)
I10,4292 (4.4%),2987 (4.6%),3091 (4.6%),3753 (4.8%),4295 (4.7%),5042 (5.1%)
E11.9,2024 (2.1%),1502 (2.3%),1590 (2.3%),1761 (2.3%),2157 (2.4%),2347 (2.4%)
Z92.2,2457 (2.5%),1250 (1.9%),1418 (2.1%),1568 (2.0%),2124 (2.3%),2211 (2.2%)
Z92.4,1680 (1.7%),1169 (1.8%),1108 (1.6%),1509 (1.9%),2052 (2.3%),2102 (2.1%)
...,...,...,...,...,...,...
A15.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A15.4,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A16.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A08.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z93.9,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO5):'

,2019,2020,2021,2022,2023,2024
NULOS,665048 (63.1%),386993 (54.0%),381401 (50.9%),453943 (53.1%),493364 (52.0%),490572 (49.7%)
I10,26057 (2.5%),21177 (3.0%),22141 (3.0%),23641 (2.8%),26980 (2.8%),29542 (3.0%)
Z37.0,17455 (1.7%),15512 (2.2%),14127 (1.9%),16784 (2.0%),16490 (1.7%),14589 (1.5%)
Z92.2,13956 (1.3%),8299 (1.2%),9631 (1.3%),11438 (1.3%),15093 (1.6%),16656 (1.7%)
E66.9,9620 (0.9%),9295 (1.3%),12263 (1.6%),13387 (1.6%),13949 (1.5%),15250 (1.5%)
...,...,...,...,...,...,...
W16.88,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
W16.49,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
W16.08,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
W15.81,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
W15.49,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO6] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO6: 9791 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO6):'

,2019,2020,2021,2022,2023,2024
NULOS,828888 (72.0%),497634 (63.6%),494090 (60.5%),580657 (62.2%),633878 (61.0%),634055 (58.4%)
I10,18800 (1.6%),16906 (2.2%),17899 (2.2%),19402 (2.1%),22104 (2.1%),24712 (2.3%)
Z92.2,13632 (1.2%),8699 (1.1%),9696 (1.2%),11850 (1.3%),15904 (1.5%),18056 (1.7%)
Z37.0,11520 (1.0%),10583 (1.4%),10788 (1.3%),13432 (1.4%),13714 (1.3%),12082 (1.1%)
Z92.4,9108 (0.8%),5805 (0.7%),6679 (0.8%),10144 (1.1%),14204 (1.4%),14776 (1.4%)
...,...,...,...,...,...,...
A05.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A15.5,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A15.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A16.7,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A16.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO6):'

,2019,2020,2021,2022,2023,2024
NULOS,56745 (58.0%),34082 (52.5%),34523 (50.8%),37598 (48.2%),41113 (45.3%),41728 (42.1%)
I10,2687 (2.7%),2069 (3.2%),2232 (3.3%),2792 (3.6%),3304 (3.6%),3693 (3.7%)
Z92.2,2292 (2.3%),1160 (1.8%),1305 (1.9%),1554 (2.0%),2051 (2.3%),2333 (2.4%)
Z92.4,1469 (1.5%),1022 (1.6%),961 (1.4%),1339 (1.7%),1981 (2.2%),1967 (2.0%)
E11.9,1337 (1.4%),1070 (1.6%),1067 (1.6%),1242 (1.6%),1503 (1.7%),1765 (1.8%)
...,...,...,...,...,...,...
Q24.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Q23.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Q22.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
Q22.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Q18.1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO6):'

,2019,2020,2021,2022,2023,2024
NULOS,772143 (73.3%),463552 (64.7%),459567 (61.4%),543059 (63.5%),592765 (62.5%),592327 (60.0%)
I10,16113 (1.5%),14837 (2.1%),15667 (2.1%),16610 (1.9%),18800 (2.0%),21019 (2.1%)
Z37.0,11509 (1.1%),10575 (1.5%),10774 (1.4%),13421 (1.6%),13706 (1.4%),12068 (1.2%)
Z92.2,11340 (1.1%),7539 (1.1%),8391 (1.1%),10296 (1.2%),13853 (1.5%),15723 (1.6%)
Z92.4,7639 (0.7%),4783 (0.7%),5718 (0.8%),8805 (1.0%),12223 (1.3%),12809 (1.3%)
...,...,...,...,...,...,...
A07.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A07.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A07.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A06.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A06.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[DIAGNOSTICO7] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO7: 9032 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO7):'

,2019,2020,2021,2022,2023,2024
NULOS,918627 (79.8%),565115 (72.3%),564947 (69.2%),659796 (70.7%),722949 (69.5%),727746 (67.0%)
I10,12083 (1.0%),11999 (1.5%),12848 (1.6%),13774 (1.5%),15776 (1.5%),18008 (1.7%)
Z92.2,10483 (0.9%),7268 (0.9%),8210 (1.0%),10026 (1.1%),13367 (1.3%),15425 (1.4%)
Z92.4,6911 (0.6%),4655 (0.6%),5518 (0.7%),8294 (0.9%),11991 (1.2%),12696 (1.2%)
Z37.0,6740 (0.6%),6412 (0.8%),7186 (0.9%),9061 (1.0%),9275 (0.9%),8905 (0.8%)
...,...,...,...,...,...,...
O63.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
W16.88,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
O68.3,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
O66.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
O46.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO7):'

,2019,2020,2021,2022,2023,2024
NULOS,66007 (67.5%),40457 (62.3%),41078 (60.5%),44881 (57.5%),49774 (54.9%),51010 (51.4%)
I10,1689 (1.7%),1480 (2.3%),1551 (2.3%),1907 (2.4%),2302 (2.5%),2812 (2.8%)
Z92.2,1941 (2.0%),963 (1.5%),1121 (1.7%),1393 (1.8%),1903 (2.1%),2122 (2.1%)
Z92.4,1208 (1.2%),740 (1.1%),796 (1.2%),1170 (1.5%),1720 (1.9%),1891 (1.9%)
E11.9,897 (0.9%),695 (1.1%),801 (1.2%),964 (1.2%),1192 (1.3%),1401 (1.4%)
...,...,...,...,...,...,...
Z99.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A08.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A07.9,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A06.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A05.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO7):'

,2019,2020,2021,2022,2023,2024
NULOS,852620 (80.9%),524658 (73.2%),523869 (69.9%),614915 (71.9%),673175 (70.9%),676736 (68.6%)
I10,10394 (1.0%),10519 (1.5%),11297 (1.5%),11867 (1.4%),13474 (1.4%),15196 (1.5%)
Z92.2,8542 (0.8%),6305 (0.9%),7089 (0.9%),8633 (1.0%),11464 (1.2%),13303 (1.3%)
Z37.0,6730 (0.6%),6400 (0.9%),7179 (1.0%),9044 (1.1%),9263 (1.0%),8889 (0.9%)
Z92.4,5703 (0.5%),3915 (0.5%),4722 (0.6%),7124 (0.8%),10271 (1.1%),10805 (1.1%)
...,...,...,...,...,...,...
Z94.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A08.5,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A04.6,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A15.4,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A06.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[DIAGNOSTICO8] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO8: 8353 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO8):'

,2019,2020,2021,2022,2023,2024
NULOS,984760 (85.5%),617582 (79.0%),621193 (76.0%),722594 (77.5%),794214 (76.4%),804082 (74.1%)
I10,8004 (0.7%),8643 (1.1%),9409 (1.2%),9863 (1.1%),11605 (1.1%),13402 (1.2%)
Z92.2,7460 (0.6%),5684 (0.7%),6397 (0.8%),7907 (0.8%),10696 (1.0%),12723 (1.2%)
Z92.4,5166 (0.4%),3649 (0.5%),4447 (0.5%),6598 (0.7%),9759 (0.9%),9991 (0.9%)
Z37.0,3621 (0.3%),3546 (0.5%),4248 (0.5%),5521 (0.6%),5875 (0.6%),5785 (0.5%)
...,...,...,...,...,...,...
T40.6,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
T39.4,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
T38.9,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
G21.3,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
G14,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO8):'

,2019,2020,2021,2022,2023,2024
NULOS,73737 (75.4%),45660 (70.3%),46642 (68.7%),51250 (65.6%),57337 (63.2%),59320 (59.8%)
I10,1193 (1.2%),1042 (1.6%),1091 (1.6%),1377 (1.8%),1742 (1.9%),2098 (2.1%)
Z92.2,1330 (1.4%),778 (1.2%),908 (1.3%),1131 (1.4%),1516 (1.7%),1837 (1.9%)
Z92.4,881 (0.9%),648 (1.0%),651 (1.0%),1017 (1.3%),1458 (1.6%),1492 (1.5%)
E11.9,553 (0.6%),542 (0.8%),558 (0.8%),731 (0.9%),873 (1.0%),1123 (1.1%)
...,...,...,...,...,...,...
M25.88,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
M30.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M31.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A27.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A31.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO8):'

,2019,2020,2021,2022,2023,2024
NULOS,911023 (86.5%),571922 (79.8%),574551 (76.7%),671344 (78.5%),736877 (77.7%),744762 (75.5%)
I10,6811 (0.6%),7601 (1.1%),8318 (1.1%),8486 (1.0%),9863 (1.0%),11304 (1.1%)
Z92.2,6130 (0.6%),4906 (0.7%),5489 (0.7%),6776 (0.8%),9180 (1.0%),10886 (1.1%)
Z92.4,4285 (0.4%),3001 (0.4%),3796 (0.5%),5581 (0.7%),8301 (0.9%),8499 (0.9%)
Z37.0,3615 (0.3%),3533 (0.5%),4235 (0.6%),5503 (0.6%),5862 (0.6%),5768 (0.6%)
...,...,...,...,...,...,...
T47.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
T46.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
T46.7,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
I20.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
T46.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[DIAGNOSTICO9] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO9: 7738 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO9):'

,2019,2020,2021,2022,2023,2024
NULOS,1032280 (89.7%),657478 (84.1%),665423 (81.5%),771084 (82.7%),849815 (81.7%),864722 (79.6%)
I10,5281 (0.5%),6128 (0.8%),7011 (0.9%),7253 (0.8%),8360 (0.8%),9364 (0.9%)
Z92.2,5382 (0.5%),4614 (0.6%),5001 (0.6%),6305 (0.7%),8438 (0.8%),10115 (0.9%)
Z92.4,3633 (0.3%),2859 (0.4%),3473 (0.4%),5180 (0.6%),7578 (0.7%),7847 (0.7%)
E11.9,2383 (0.2%),2905 (0.4%),3356 (0.4%),3447 (0.4%),3875 (0.4%),4480 (0.4%)
...,...,...,...,...,...,...
A06.0,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A06.9,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A07.8,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A07.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
Z93.9,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO9):'

,2019,2020,2021,2022,2023,2024
NULOS,79691 (81.5%),49918 (76.9%),51082 (75.2%),56469 (72.3%),63616 (70.1%),66379 (66.9%)
I10,815 (0.8%),752 (1.2%),811 (1.2%),1067 (1.4%),1266 (1.4%),1507 (1.5%)
Z92.2,1079 (1.1%),639 (1.0%),634 (0.9%),920 (1.2%),1197 (1.3%),1597 (1.6%)
Z92.4,656 (0.7%),492 (0.8%),513 (0.8%),798 (1.0%),1121 (1.2%),1219 (1.2%)
E11.9,395 (0.4%),360 (0.6%),383 (0.6%),545 (0.7%),677 (0.7%),774 (0.8%)
...,...,...,...,...,...,...
A15.3,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A15.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A08.5,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A08.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A07.8,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO9):'

,2019,2020,2021,2022,2023,2024
NULOS,952589 (90.4%),607560 (84.7%),614341 (82.0%),714615 (83.6%),786199 (82.9%),798343 (80.9%)
I10,4466 (0.4%),5376 (0.7%),6200 (0.8%),6186 (0.7%),7094 (0.7%),7857 (0.8%)
Z92.2,4303 (0.4%),3975 (0.6%),4367 (0.6%),5385 (0.6%),7241 (0.8%),8518 (0.9%)
Z92.4,2977 (0.3%),2367 (0.3%),2960 (0.4%),4382 (0.5%),6457 (0.7%),6628 (0.7%)
E11.9,1988 (0.2%),2545 (0.4%),2973 (0.4%),2902 (0.3%),3198 (0.3%),3706 (0.4%)
...,...,...,...,...,...,...
S82.31,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
S90.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
S86.9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
S86.8,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
S85.5,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO10] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO10: 7240 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO10):'

,2019,2020,2021,2022,2023,2024
NULOS,1065974 (92.6%),687575 (87.9%),699442 (85.6%),808272 (86.6%),892311 (85.8%),912334 (84.0%)
I10,3453 (0.3%),4290 (0.5%),5288 (0.6%),5353 (0.6%),6117 (0.6%),7131 (0.7%)
Z92.2,3804 (0.3%),3433 (0.4%),3963 (0.5%),4866 (0.5%),6539 (0.6%),7878 (0.7%)
Z92.4,2492 (0.2%),2125 (0.3%),2608 (0.3%),3877 (0.4%),5774 (0.6%),6197 (0.6%)
E11.9,1549 (0.1%),2087 (0.3%),2525 (0.3%),2541 (0.3%),2752 (0.3%),3196 (0.3%)
...,...,...,...,...,...,...
M87.38,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
M87.35,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
M87.17,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A08.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A07.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO10):'

,2019,2020,2021,2022,2023,2024
NULOS,84558 (86.4%),53296 (82.1%),54700 (80.5%),60908 (78.0%),68808 (75.9%),72352 (73.0%)
Z92.2,703 (0.7%),496 (0.8%),515 (0.8%),742 (1.0%),967 (1.1%),1262 (1.3%)
I10,502 (0.5%),543 (0.8%),622 (0.9%),810 (1.0%),974 (1.1%),1205 (1.2%)
Z92.4,435 (0.4%),371 (0.6%),433 (0.6%),557 (0.7%),922 (1.0%),1007 (1.0%)
E11.9,251 (0.3%),277 (0.4%),320 (0.5%),394 (0.5%),483 (0.5%),570 (0.6%)
...,...,...,...,...,...,...
A54.8,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A04.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
J70.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
J70.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
J70.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO10):'

,2019,2020,2021,2022,2023,2024
NULOS,981416 (93.2%),634279 (88.5%),644742 (86.1%),747364 (87.4%),823503 (86.8%),839982 (85.1%)
I10,2951 (0.3%),3747 (0.5%),4666 (0.6%),4543 (0.5%),5143 (0.5%),5926 (0.6%)
Z92.2,3101 (0.3%),2937 (0.4%),3448 (0.5%),4124 (0.5%),5572 (0.6%),6616 (0.7%)
Z92.4,2057 (0.2%),1754 (0.2%),2175 (0.3%),3320 (0.4%),4852 (0.5%),5190 (0.5%)
E11.9,1298 (0.1%),1810 (0.3%),2205 (0.3%),2147 (0.3%),2269 (0.2%),2626 (0.3%)
...,...,...,...,...,...,...
Z93.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
S15.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A42.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
S15.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A04.2,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO11] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO11: 6688 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO11):'

,2019,2020,2021,2022,2023,2024
NULOS,1089640 (94.6%),710062 (90.8%),725406 (88.8%),836350 (89.7%),924776 (89.0%),949077 (87.4%)
Z92.2,2724 (0.2%),2637 (0.3%),3084 (0.4%),3683 (0.4%),4984 (0.5%),6406 (0.6%)
I10,2365 (0.2%),3190 (0.4%),3958 (0.5%),4005 (0.4%),4708 (0.5%),5265 (0.5%)
Z92.4,1791 (0.2%),1609 (0.2%),1982 (0.2%),3062 (0.3%),4365 (0.4%),4665 (0.4%)
E11.9,981 (0.1%),1463 (0.2%),1873 (0.2%),1954 (0.2%),2046 (0.2%),2387 (0.2%)
...,...,...,...,...,...,...
Z93.9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z94.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
Z94.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A15.7,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A08.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO11):'

,2019,2020,2021,2022,2023,2024
NULOS,88034 (90.0%),55967 (86.2%),57496 (84.6%),64228 (82.3%),73135 (80.6%),77299 (78.0%)
Z92.2,488 (0.5%),355 (0.5%),410 (0.6%),573 (0.7%),734 (0.8%),1038 (1.0%)
I10,398 (0.4%),363 (0.6%),444 (0.7%),606 (0.8%),737 (0.8%),903 (0.9%)
Z92.4,313 (0.3%),284 (0.4%),303 (0.4%),494 (0.6%),749 (0.8%),806 (0.8%)
E11.9,169 (0.2%),192 (0.3%),242 (0.4%),291 (0.4%),357 (0.4%),469 (0.5%)
...,...,...,...,...,...,...
E77.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
E74.9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
E74.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
E70.3,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A46,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO11):'

,2019,2020,2021,2022,2023,2024
NULOS,1001606 (95.1%),654095 (91.2%),667910 (89.2%),772122 (90.3%),851641 (89.8%),871778 (88.4%)
I10,1967 (0.2%),2827 (0.4%),3514 (0.5%),3399 (0.4%),3971 (0.4%),4362 (0.4%)
Z92.2,2236 (0.2%),2282 (0.3%),2674 (0.4%),3110 (0.4%),4250 (0.4%),5368 (0.5%)
Z92.4,1478 (0.1%),1325 (0.2%),1679 (0.2%),2568 (0.3%),3616 (0.4%),3859 (0.4%)
E11.9,812 (0.1%),1271 (0.2%),1631 (0.2%),1663 (0.2%),1689 (0.2%),1918 (0.2%)
...,...,...,...,...,...,...
S21.7,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
S21.8,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
S22.31,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
S26.81,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A06.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO12] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO12: 6204 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO12):'

,2019,2020,2021,2022,2023,2024
NULOS,1106354 (96.1%),726997 (93.0%),745183 (91.2%),857491 (91.9%),949542 (91.3%),977571 (90.0%)
Z92.2,1941 (0.2%),2077 (0.3%),2387 (0.3%),2883 (0.3%),3953 (0.4%),4980 (0.5%)
I10,1600 (0.1%),2206 (0.3%),2777 (0.3%),3043 (0.3%),3322 (0.3%),3978 (0.4%)
Z92.4,1334 (0.1%),1243 (0.2%),1601 (0.2%),2380 (0.3%),3411 (0.3%),3671 (0.3%)
E11.9,710 (0.1%),1084 (0.1%),1354 (0.2%),1374 (0.1%),1566 (0.2%),1717 (0.2%)
...,...,...,...,...,...,...
R83.6,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
R82.8,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
R82.6,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
E63.9,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
E61.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO12):'

,2019,2020,2021,2022,2023,2024
NULOS,90670 (92.7%),57935 (89.2%),59706 (87.9%),66967 (85.8%),76574 (84.4%),81355 (82.0%)
Z92.2,344 (0.4%),276 (0.4%),321 (0.5%),433 (0.6%),573 (0.6%),835 (0.8%)
I10,244 (0.2%),287 (0.4%),311 (0.5%),454 (0.6%),529 (0.6%),680 (0.7%)
Z92.4,230 (0.2%),221 (0.3%),243 (0.4%),361 (0.5%),548 (0.6%),568 (0.6%)
Z92.6,171 (0.2%),114 (0.2%),131 (0.2%),229 (0.3%),295 (0.3%),370 (0.4%)
...,...,...,...,...,...,...
A02.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A04.0,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A04.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z94.9,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z96.3,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO12):'

,2019,2020,2021,2022,2023,2024
NULOS,1015684 (96.4%),669062 (93.3%),685477 (91.5%),790524 (92.5%),872968 (92.0%),896216 (90.8%)
Z92.2,1597 (0.2%),1801 (0.3%),2066 (0.3%),2450 (0.3%),3380 (0.4%),4145 (0.4%)
I10,1356 (0.1%),1919 (0.3%),2466 (0.3%),2589 (0.3%),2793 (0.3%),3298 (0.3%)
Z92.4,1104 (0.1%),1022 (0.1%),1358 (0.2%),2019 (0.2%),2863 (0.3%),3103 (0.3%)
E11.9,594 (0.1%),942 (0.1%),1185 (0.2%),1142 (0.1%),1293 (0.1%),1404 (0.1%)
...,...,...,...,...,...,...
R94.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
I15.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
I09.8,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z96.3,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A18.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[DIAGNOSTICO13] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO13: 5741 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO13):'

,2019,2020,2021,2022,2023,2024
NULOS,1118456 (97.1%),739891 (94.6%),760227 (93.1%),873665 (93.7%),968718 (93.2%),1000092 (92.1%)
Z92.2,1486 (0.1%),1548 (0.2%),1908 (0.2%),2278 (0.2%),3090 (0.3%),3927 (0.4%)
I10,1163 (0.1%),1616 (0.2%),2166 (0.3%),2159 (0.2%),2457 (0.2%),2958 (0.3%)
Z92.4,942 (0.1%),940 (0.1%),1228 (0.2%),1780 (0.2%),2670 (0.3%),2863 (0.3%)
E11.9,504 (0.0%),743 (0.1%),981 (0.1%),1043 (0.1%),1132 (0.1%),1317 (0.1%)
...,...,...,...,...,...,...
G51.8,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
G51.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
G50.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
R46.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
R45.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO13):'

,2019,2020,2021,2022,2023,2024
NULOS,92575 (94.6%),59519 (91.7%),61380 (90.4%),69185 (88.6%),79330 (87.4%),84742 (85.5%)
Z92.2,264 (0.3%),206 (0.3%),253 (0.4%),350 (0.4%),451 (0.5%),627 (0.6%)
I10,174 (0.2%),213 (0.3%),245 (0.4%),325 (0.4%),461 (0.5%),490 (0.5%)
Z92.4,180 (0.2%),131 (0.2%),175 (0.3%),293 (0.4%),487 (0.5%),490 (0.5%)
Z92.6,122 (0.1%),80 (0.1%),133 (0.2%),182 (0.2%),222 (0.2%),288 (0.3%)
...,...,...,...,...,...,...
M79.99,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
M79.89,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
M79.69,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
M79.66,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M79.62,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO13):'

,2019,2020,2021,2022,2023,2024
NULOS,1025881 (97.4%),680372 (94.9%),698847 (93.3%),804480 (94.1%),889388 (93.7%),915350 (92.8%)
Z92.2,1222 (0.1%),1342 (0.2%),1655 (0.2%),1928 (0.2%),2639 (0.3%),3300 (0.3%)
I10,989 (0.1%),1403 (0.2%),1921 (0.3%),1834 (0.2%),1996 (0.2%),2468 (0.3%)
Z92.4,762 (0.1%),809 (0.1%),1053 (0.1%),1487 (0.2%),2183 (0.2%),2373 (0.2%)
E11.9,417 (0.0%),621 (0.1%),865 (0.1%),865 (0.1%),934 (0.1%),1077 (0.1%)
...,...,...,...,...,...,...
Z99.4,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A18.1,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A16.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A15.8,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A15.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[DIAGNOSTICO14] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO14: 5377 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO14):'

,2019,2020,2021,2022,2023,2024
NULOS,1127055 (97.9%),749453 (95.8%),772044 (94.5%),886005 (95.0%),983619 (94.6%),1017431 (93.7%)
Z92.2,1039 (0.1%),1173 (0.2%),1531 (0.2%),1794 (0.2%),2392 (0.2%),3210 (0.3%)
I10,837 (0.1%),1139 (0.1%),1610 (0.2%),1648 (0.2%),1806 (0.2%),2204 (0.2%)
Z92.4,686 (0.1%),750 (0.1%),1024 (0.1%),1425 (0.2%),2157 (0.2%),2329 (0.2%)
E11.9,292 (0.0%),554 (0.1%),745 (0.1%),757 (0.1%),868 (0.1%),1068 (0.1%)
...,...,...,...,...,...,...
A51.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A51.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
N95.9,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
N94.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
N92.6,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO14):'

,2019,2020,2021,2022,2023,2024
NULOS,93938 (96.0%),60687 (93.5%),62703 (92.3%),70957 (90.9%),81604 (90.0%),87473 (88.2%)
Z92.2,158 (0.2%),146 (0.2%),173 (0.3%),296 (0.4%),416 (0.5%),562 (0.6%)
I10,155 (0.2%),164 (0.3%),184 (0.3%),258 (0.3%),318 (0.4%),387 (0.4%)
Z92.4,119 (0.1%),150 (0.2%),159 (0.2%),244 (0.3%),330 (0.4%),394 (0.4%)
Z92.6,99 (0.1%),87 (0.1%),75 (0.1%),121 (0.2%),176 (0.2%),229 (0.2%)
...,...,...,...,...,...,...
I37.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
I33.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B35.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
B34.9,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B34.1,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO14):'

,2019,2020,2021,2022,2023,2024
NULOS,1033117 (98.1%),688766 (96.1%),709341 (94.7%),815048 (95.4%),902015 (95.1%),929958 (94.3%)
Z92.2,881 (0.1%),1027 (0.1%),1358 (0.2%),1498 (0.2%),1976 (0.2%),2648 (0.3%)
I10,682 (0.1%),975 (0.1%),1426 (0.2%),1390 (0.2%),1488 (0.2%),1817 (0.2%)
Z92.4,567 (0.1%),600 (0.1%),865 (0.1%),1181 (0.1%),1827 (0.2%),1935 (0.2%)
E11.9,233 (0.0%),467 (0.1%),650 (0.1%),632 (0.1%),706 (0.1%),860 (0.1%)
...,...,...,...,...,...,...
F10.7,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A18.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A48.0,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A18.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A07.9,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO15] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO15: 5026 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO15):'

,2019,2020,2021,2022,2023,2024
NULOS,1133311 (98.4%),756884 (96.8%),781406 (95.7%),895776 (96.0%),995137 (95.7%),1031135 (95.0%)
Z92.2,760 (0.1%),872 (0.1%),1232 (0.2%),1440 (0.2%),1928 (0.2%),2535 (0.2%)
I10,534 (0.0%),847 (0.1%),1271 (0.2%),1215 (0.1%),1430 (0.1%),1790 (0.2%)
Z92.4,507 (0.0%),539 (0.1%),828 (0.1%),1124 (0.1%),1693 (0.2%),1783 (0.2%)
E11.9,242 (0.0%),388 (0.0%),587 (0.1%),567 (0.1%),562 (0.1%),720 (0.1%)
...,...,...,...,...,...,...
A19.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A18.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A18.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A05.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A16.1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO15):'

,2019,2020,2021,2022,2023,2024
NULOS,94942 (97.0%),61639 (94.9%),63787 (93.9%),72424 (92.8%),83399 (91.9%),89692 (90.5%)
Z92.2,143 (0.1%),140 (0.2%),150 (0.2%),218 (0.3%),315 (0.3%),416 (0.4%)
Z92.4,89 (0.1%),92 (0.1%),113 (0.2%),187 (0.2%),308 (0.3%),328 (0.3%)
I10,103 (0.1%),94 (0.1%),145 (0.2%),191 (0.2%),249 (0.3%),308 (0.3%)
Z92.6,59 (0.1%),60 (0.1%),69 (0.1%),120 (0.2%),156 (0.2%),189 (0.2%)
...,...,...,...,...,...,...
A51.0,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A49.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A49.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A08.4,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A02.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO15):'

,2019,2020,2021,2022,2023,2024
NULOS,1038369 (98.6%),695245 (97.0%),717619 (95.8%),823352 (96.3%),911738 (96.1%),941443 (95.4%)
Z92.2,617 (0.1%),732 (0.1%),1082 (0.1%),1222 (0.1%),1613 (0.2%),2119 (0.2%)
I10,431 (0.0%),753 (0.1%),1126 (0.2%),1024 (0.1%),1181 (0.1%),1482 (0.2%)
Z92.4,418 (0.0%),447 (0.1%),715 (0.1%),937 (0.1%),1385 (0.1%),1455 (0.1%)
E11.9,193 (0.0%),335 (0.0%),508 (0.1%),471 (0.1%),475 (0.1%),584 (0.1%)
...,...,...,...,...,...,...
A20.7,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A33,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A36.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A40.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A08.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[DIAGNOSTICO16] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO16: 4683 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO16):'

,2019,2020,2021,2022,2023,2024
NULOS,1137967 (98.8%),762462 (97.5%),788655 (96.5%),903254 (96.8%),1004218 (96.6%),1041808 (95.9%)
Z92.2,516 (0.0%),681 (0.1%),952 (0.1%),1163 (0.1%),1462 (0.1%),2007 (0.2%)
I10,383 (0.0%),613 (0.1%),982 (0.1%),923 (0.1%),1022 (0.1%),1259 (0.1%)
Z92.4,341 (0.0%),406 (0.1%),598 (0.1%),930 (0.1%),1311 (0.1%),1485 (0.1%)
E11.9,148 (0.0%),278 (0.0%),486 (0.1%),427 (0.0%),417 (0.0%),513 (0.0%)
...,...,...,...,...,...,...
A17.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A18.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A18.2,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A18.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A31.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO16):'

,2019,2020,2021,2022,2023,2024
NULOS,95671 (97.8%),62415 (96.1%),64659 (95.2%),73511 (94.2%),84853 (93.5%),91485 (92.3%)
Z92.2,83 (0.1%),105 (0.2%),121 (0.2%),191 (0.2%),243 (0.3%),344 (0.3%)
Z92.4,70 (0.1%),67 (0.1%),90 (0.1%),147 (0.2%),233 (0.3%),284 (0.3%)
I10,51 (0.1%),79 (0.1%),120 (0.2%),126 (0.2%),185 (0.2%),225 (0.2%)
Z92.6,54 (0.1%),43 (0.1%),53 (0.1%),74 (0.1%),110 (0.1%),151 (0.2%)
...,...,...,...,...,...,...
A16.2,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A15.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A63.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A60.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A59.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO16):'

,2019,2020,2021,2022,2023,2024
NULOS,1042296 (98.9%),700047 (97.6%),723996 (96.7%),829743 (97.1%),919365 (96.9%),950323 (96.3%)
Z92.2,433 (0.0%),576 (0.1%),831 (0.1%),972 (0.1%),1219 (0.1%),1663 (0.2%)
I10,332 (0.0%),534 (0.1%),862 (0.1%),797 (0.1%),837 (0.1%),1034 (0.1%)
Z92.4,271 (0.0%),339 (0.0%),508 (0.1%),783 (0.1%),1078 (0.1%),1201 (0.1%)
Z92.1,167 (0.0%),244 (0.0%),288 (0.0%),294 (0.0%),432 (0.0%),493 (0.0%)
...,...,...,...,...,...,...
Q61.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
Q61.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Q60.4,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Q60.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
Q56.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[DIAGNOSTICO17] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO17: 4319 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO17):'

,2019,2020,2021,2022,2023,2024
NULOS,1141214 (99.1%),766744 (98.1%),794418 (97.2%),909250 (97.5%),1011310 (97.3%),1050446 (96.7%)
Z92.2,415 (0.0%),521 (0.1%),732 (0.1%),923 (0.1%),1188 (0.1%),1644 (0.2%)
Z92.4,271 (0.0%),330 (0.0%),527 (0.1%),761 (0.1%),1084 (0.1%),1136 (0.1%)
I10,274 (0.0%),445 (0.1%),750 (0.1%),691 (0.1%),821 (0.1%),903 (0.1%)
Z92.1,141 (0.0%),161 (0.0%),257 (0.0%),336 (0.0%),385 (0.0%),503 (0.0%)
...,...,...,...,...,...,...
Q39.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Q37.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
Q37.3,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A02.2,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A16.7,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO17):'

,2019,2020,2021,2022,2023,2024
NULOS,96191 (98.3%),62963 (97.0%),65353 (96.2%),74455 (95.4%),85947 (94.7%),93017 (93.8%)
Z92.2,66 (0.1%),83 (0.1%),93 (0.1%),161 (0.2%),188 (0.2%),302 (0.3%)
Z92.4,52 (0.1%),56 (0.1%),74 (0.1%),133 (0.2%),183 (0.2%),216 (0.2%)
I10,36 (0.0%),51 (0.1%),84 (0.1%),99 (0.1%),144 (0.2%),150 (0.2%)
Z92.6,27 (0.0%),30 (0.0%),42 (0.1%),50 (0.1%),84 (0.1%),119 (0.1%)
...,...,...,...,...,...,...
A81.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A86,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B02.8,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B08.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B18.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO17):'

,2019,2020,2021,2022,2023,2024
NULOS,1045023 (99.2%),703781 (98.2%),729065 (97.3%),834795 (97.7%),925363 (97.5%),957429 (97.0%)
Z92.2,349 (0.0%),438 (0.1%),639 (0.1%),762 (0.1%),1000 (0.1%),1342 (0.1%)
Z92.4,219 (0.0%),274 (0.0%),453 (0.1%),628 (0.1%),901 (0.1%),920 (0.1%)
I10,238 (0.0%),394 (0.1%),666 (0.1%),592 (0.1%),677 (0.1%),753 (0.1%)
Z92.1,126 (0.0%),140 (0.0%),226 (0.0%),276 (0.0%),322 (0.0%),424 (0.0%)
...,...,...,...,...,...,...
Q52.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Q52.6,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Q53.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
Q55.4,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Q55.6,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO18] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO18: 3969 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO18):'

,2019,2020,2021,2022,2023,2024
NULOS,1143737 (99.3%),770028 (98.5%),798881 (97.8%),913903 (98.0%),1016928 (97.8%),1057269 (97.4%)
Z92.2,295 (0.0%),380 (0.0%),626 (0.1%),762 (0.1%),967 (0.1%),1325 (0.1%)
Z92.4,182 (0.0%),267 (0.0%),373 (0.0%),586 (0.1%),830 (0.1%),930 (0.1%)
I10,174 (0.0%),367 (0.0%),539 (0.1%),572 (0.1%),627 (0.1%),758 (0.1%)
Z92.1,132 (0.0%),136 (0.0%),203 (0.0%),242 (0.0%),329 (0.0%),388 (0.0%)
...,...,...,...,...,...,...
Q25.5,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Q38.5,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Q38.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Q35.3,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Q35.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO18):'

,2019,2020,2021,2022,2023,2024
NULOS,96599 (98.7%),63384 (97.6%),65838 (96.9%),75157 (96.3%),86906 (95.8%),94214 (95.0%)
Z92.2,62 (0.1%),53 (0.1%),84 (0.1%),122 (0.2%),167 (0.2%),249 (0.3%)
Z92.4,32 (0.0%),55 (0.1%),55 (0.1%),89 (0.1%),139 (0.2%),161 (0.2%)
I10,28 (0.0%),40 (0.1%),60 (0.1%),97 (0.1%),107 (0.1%),138 (0.1%)
Z92.6,18 (0.0%),21 (0.0%),30 (0.0%),61 (0.1%),92 (0.1%),85 (0.1%)
...,...,...,...,...,...,...
M43.16,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M43.06,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A16.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z99.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A79.8,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO18):'

,2019,2020,2021,2022,2023,2024
NULOS,1047138 (99.4%),706644 (98.6%),733043 (97.9%),838746 (98.1%),930022 (98.0%),963055 (97.6%)
Z92.2,233 (0.0%),327 (0.0%),542 (0.1%),640 (0.1%),800 (0.1%),1076 (0.1%)
Z92.4,150 (0.0%),212 (0.0%),318 (0.0%),497 (0.1%),691 (0.1%),769 (0.1%)
I10,146 (0.0%),327 (0.0%),479 (0.1%),475 (0.1%),520 (0.1%),620 (0.1%)
Z92.1,106 (0.0%),115 (0.0%),180 (0.0%),210 (0.0%),272 (0.0%),322 (0.0%)
...,...,...,...,...,...,...
A36.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A30.9,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A52.9,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A52.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
E56.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO19] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO19: 3687 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO19):'

,2019,2020,2021,2022,2023,2024
NULOS,1145514 (99.5%),772531 (98.8%),802489 (98.2%),917707 (98.4%),1021377 (98.2%),1062614 (97.9%)
Z92.2,245 (0.0%),280 (0.0%),490 (0.1%),586 (0.1%),771 (0.1%),1137 (0.1%)
Z92.4,136 (0.0%),196 (0.0%),325 (0.0%),514 (0.1%),681 (0.1%),730 (0.1%)
I10,156 (0.0%),269 (0.0%),430 (0.1%),430 (0.0%),461 (0.0%),597 (0.1%)
Z92.1,73 (0.0%),117 (0.0%),155 (0.0%),200 (0.0%),236 (0.0%),324 (0.0%)
...,...,...,...,...,...,...
B00.2,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
B00.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
B00.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
B02.1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A41.3,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO19):'

,2019,2020,2021,2022,2023,2024
NULOS,96915 (99.1%),63756 (98.2%),66256 (97.5%),75724 (97.0%),87661 (96.6%),95146 (96.0%)
Z92.2,52 (0.1%),47 (0.1%),65 (0.1%),87 (0.1%),131 (0.1%),193 (0.2%)
Z92.4,31 (0.0%),27 (0.0%),62 (0.1%),93 (0.1%),128 (0.1%),118 (0.1%)
I10,22 (0.0%),42 (0.1%),54 (0.1%),70 (0.1%),78 (0.1%),107 (0.1%)
Z92.6,20 (0.0%),17 (0.0%),30 (0.0%),46 (0.1%),44 (0.0%),79 (0.1%)
...,...,...,...,...,...,...
A08.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A08.3,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A08.2,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A07.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A04.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO19):'

,2019,2020,2021,2022,2023,2024
NULOS,1048599 (99.5%),708775 (98.9%),736233 (98.3%),841983 (98.5%),933716 (98.4%),967468 (98.1%)
Z92.2,193 (0.0%),233 (0.0%),425 (0.1%),499 (0.1%),640 (0.1%),944 (0.1%)
Z92.4,105 (0.0%),169 (0.0%),263 (0.0%),421 (0.0%),553 (0.1%),612 (0.1%)
I10,134 (0.0%),227 (0.0%),376 (0.1%),360 (0.0%),383 (0.0%),490 (0.0%)
Z92.1,62 (0.0%),105 (0.0%),145 (0.0%),176 (0.0%),189 (0.0%),279 (0.0%)
...,...,...,...,...,...,...
A28.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A27.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A19.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
B00.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A18.1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO20] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO20: 3419 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO20):'

,2019,2020,2021,2022,2023,2024
NULOS,1146823 (99.6%),774520 (99.1%),805369 (98.6%),920755 (98.7%),1025016 (98.6%),1067027 (98.3%)
Z92.2,159 (0.0%),230 (0.0%),388 (0.0%),497 (0.1%),593 (0.1%),871 (0.1%)
Z92.4,102 (0.0%),165 (0.0%),224 (0.0%),409 (0.0%),538 (0.1%),594 (0.1%)
I10,122 (0.0%),213 (0.0%),354 (0.0%),322 (0.0%),336 (0.0%),461 (0.0%)
Z29.0,35 (0.0%),120 (0.0%),245 (0.0%),162 (0.0%),137 (0.0%),149 (0.0%)
...,...,...,...,...,...,...
P96.1,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
P74.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
P74.9,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
P78.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
P78.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO20):'

,2019,2020,2021,2022,2023,2024
NULOS,97136 (99.3%),64008 (98.6%),66616 (98.1%),76176 (97.6%),88265 (97.3%),95870 (96.7%)
Z92.2,30 (0.0%),28 (0.0%),52 (0.1%),76 (0.1%),98 (0.1%),160 (0.2%)
Z92.4,24 (0.0%),31 (0.0%),30 (0.0%),62 (0.1%),107 (0.1%),119 (0.1%)
I10,12 (0.0%),28 (0.0%),38 (0.1%),43 (0.1%),56 (0.1%),79 (0.1%)
Z90.4,11 (0.0%),13 (0.0%),14 (0.0%),31 (0.0%),48 (0.1%),55 (0.1%)
...,...,...,...,...,...,...
K82.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A53.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A60.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B02.9,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
B07,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO20):'

,2019,2020,2021,2022,2023,2024
NULOS,1049687 (99.6%),710512 (99.1%),738753 (98.6%),844579 (98.8%),936751 (98.7%),971157 (98.4%)
Z92.2,129 (0.0%),202 (0.0%),336 (0.0%),421 (0.0%),495 (0.1%),711 (0.1%)
Z92.4,78 (0.0%),134 (0.0%),194 (0.0%),347 (0.0%),431 (0.0%),475 (0.0%)
I10,110 (0.0%),185 (0.0%),316 (0.0%),279 (0.0%),280 (0.0%),382 (0.0%)
Z29.0,33 (0.0%),106 (0.0%),230 (0.0%),145 (0.0%),116 (0.0%),124 (0.0%)
...,...,...,...,...,...,...
B08.5,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
M48.99,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M48.96,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M48.80,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
M48.59,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO21] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO21: 3112 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO21):'

,2019,2020,2021,2022,2023,2024
NULOS,1147906 (99.7%),776078 (99.3%),807626 (98.9%),923205 (99.0%),1027879 (98.9%),1070571 (98.6%)
Z92.2,142 (0.0%),190 (0.0%),342 (0.0%),355 (0.0%),523 (0.1%),697 (0.1%)
Z92.4,74 (0.0%),127 (0.0%),191 (0.0%),295 (0.0%),367 (0.0%),465 (0.0%)
I10,75 (0.0%),167 (0.0%),275 (0.0%),236 (0.0%),283 (0.0%),365 (0.0%)
Z29.0,22 (0.0%),91 (0.0%),169 (0.0%),125 (0.0%),129 (0.0%),141 (0.0%)
...,...,...,...,...,...,...
P36.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
P27.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
P26.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
P56.9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
P55.1,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO21):'

,2019,2020,2021,2022,2023,2024
NULOS,97323 (99.5%),64223 (98.9%),66895 (98.5%),76552 (98.1%),88736 (97.8%),96512 (97.3%)
Z92.2,19 (0.0%),20 (0.0%),51 (0.1%),58 (0.1%),96 (0.1%),109 (0.1%)
Z92.4,13 (0.0%),13 (0.0%),24 (0.0%),52 (0.1%),71 (0.1%),97 (0.1%)
I10,7 (0.0%),14 (0.0%),27 (0.0%),40 (0.1%),62 (0.1%),64 (0.1%)
Z92.6,10 (0.0%),17 (0.0%),14 (0.0%),28 (0.0%),31 (0.0%),54 (0.1%)
...,...,...,...,...,...,...
B34.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
B24,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A04.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
Z98.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B00.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO21):'

,2019,2020,2021,2022,2023,2024
NULOS,1050583 (99.7%),711855 (99.3%),740731 (98.9%),846653 (99.1%),939143 (99.0%),974059 (98.7%)
Z92.2,123 (0.0%),170 (0.0%),291 (0.0%),297 (0.0%),427 (0.0%),588 (0.1%)
Z92.4,61 (0.0%),114 (0.0%),167 (0.0%),243 (0.0%),296 (0.0%),368 (0.0%)
I10,68 (0.0%),153 (0.0%),248 (0.0%),196 (0.0%),221 (0.0%),301 (0.0%)
Z29.0,18 (0.0%),85 (0.0%),158 (0.0%),109 (0.0%),109 (0.0%),120 (0.0%)
...,...,...,...,...,...,...
P75,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z96.5,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
Z94.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A63.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A52.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO22] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO22: 2879 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO22):'

,2019,2020,2021,2022,2023,2024
NULOS,1148702 (99.8%),777345 (99.4%),809496 (99.1%),925079 (99.2%),1030060 (99.1%),1073383 (98.9%)
Z92.2,92 (0.0%),156 (0.0%),236 (0.0%),287 (0.0%),420 (0.0%),635 (0.1%)
Z92.4,72 (0.0%),87 (0.0%),167 (0.0%),242 (0.0%),373 (0.0%),387 (0.0%)
I10,50 (0.0%),100 (0.0%),202 (0.0%),173 (0.0%),213 (0.0%),276 (0.0%)
Z92.1,33 (0.0%),60 (0.0%),58 (0.0%),124 (0.0%),137 (0.0%),162 (0.0%)
...,...,...,...,...,...,...
H31.3,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
H30.8,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z91.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B33.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
B30.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO22):'

,2019,2020,2021,2022,2023,2024
NULOS,97447 (99.6%),64371 (99.1%),67089 (98.8%),76830 (98.4%),89112 (98.2%),97022 (97.9%)
Z92.2,17 (0.0%),18 (0.0%),31 (0.0%),46 (0.1%),81 (0.1%),116 (0.1%)
Z92.4,10 (0.0%),21 (0.0%),23 (0.0%),36 (0.0%),72 (0.1%),72 (0.1%)
I10,7 (0.0%),10 (0.0%),21 (0.0%),26 (0.0%),38 (0.0%),46 (0.0%)
Z92.6,2 (0.0%),11 (0.0%),21 (0.0%),21 (0.0%),32 (0.0%),39 (0.0%)
...,...,...,...,...,...,...
A18.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A15.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A09.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A08.3,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A04.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO22):'

,2019,2020,2021,2022,2023,2024
NULOS,1051255 (99.8%),712974 (99.4%),742407 (99.1%),848249 (99.2%),940948 (99.2%),976361 (99.0%)
Z92.2,75 (0.0%),138 (0.0%),205 (0.0%),241 (0.0%),339 (0.0%),519 (0.1%)
Z92.4,62 (0.0%),66 (0.0%),144 (0.0%),206 (0.0%),301 (0.0%),315 (0.0%)
I10,43 (0.0%),90 (0.0%),181 (0.0%),147 (0.0%),175 (0.0%),230 (0.0%)
Z92.1,29 (0.0%),54 (0.0%),50 (0.0%),104 (0.0%),111 (0.0%),140 (0.0%)
...,...,...,...,...,...,...
B21.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z92.5,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z94.3,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A46,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A40.8,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO23] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO23: 2658 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO23):'

,2019,2020,2021,2022,2023,2024
NULOS,1149311 (99.8%),778268 (99.5%),810946 (99.3%),926585 (99.3%),1031856 (99.3%),1075672 (99.1%)
Z92.2,78 (0.0%),92 (0.0%),204 (0.0%),253 (0.0%),353 (0.0%),481 (0.0%)
Z92.4,44 (0.0%),73 (0.0%),133 (0.0%),194 (0.0%),285 (0.0%),326 (0.0%)
I10,45 (0.0%),106 (0.0%),164 (0.0%),156 (0.0%),168 (0.0%),223 (0.0%)
Z90.4,24 (0.0%),37 (0.0%),45 (0.0%),71 (0.0%),86 (0.0%),197 (0.0%)
...,...,...,...,...,...,...
B20.7,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
H66.3,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
H66.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z91.4,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B02.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO23):'

,2019,2020,2021,2022,2023,2024
NULOS,97543 (99.7%),64487 (99.3%),67265 (99.0%),77057 (98.7%),89396 (98.5%),97439 (98.3%)
Z92.2,7 (0.0%),12 (0.0%),31 (0.0%),47 (0.1%),61 (0.1%),94 (0.1%)
Z92.4,8 (0.0%),12 (0.0%),15 (0.0%),30 (0.0%),43 (0.0%),65 (0.1%)
I10,7 (0.0%),7 (0.0%),15 (0.0%),23 (0.0%),27 (0.0%),34 (0.0%)
Z90.4,4 (0.0%),10 (0.0%),14 (0.0%),10 (0.0%),20 (0.0%),37 (0.0%)
...,...,...,...,...,...,...
B20.7,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
B20.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B17.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B02.2,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
B00.9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO23):'

,2019,2020,2021,2022,2023,2024
NULOS,1051768 (99.8%),713781 (99.6%),743681 (99.3%),849528 (99.4%),942460 (99.3%),978233 (99.1%)
Z92.2,71 (0.0%),80 (0.0%),173 (0.0%),206 (0.0%),292 (0.0%),387 (0.0%)
Z92.4,36 (0.0%),61 (0.0%),118 (0.0%),164 (0.0%),242 (0.0%),261 (0.0%)
I10,38 (0.0%),99 (0.0%),149 (0.0%),133 (0.0%),141 (0.0%),189 (0.0%)
Z29.0,17 (0.0%),61 (0.0%),104 (0.0%),67 (0.0%),74 (0.0%),72 (0.0%)
...,...,...,...,...,...,...
B35.8,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
L85.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
L28.1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A49.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A51.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[DIAGNOSTICO24] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO24: 2505 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO24):'

,2019,2020,2021,2022,2023,2024
NULOS,1149751 (99.9%),778976 (99.6%),812153 (99.4%),927765 (99.5%),1033338 (99.4%),1077488 (99.2%)
Z92.2,58 (0.0%),91 (0.0%),157 (0.0%),202 (0.0%),269 (0.0%),401 (0.0%)
Z92.4,36 (0.0%),46 (0.0%),110 (0.0%),157 (0.0%),217 (0.0%),260 (0.0%)
I10,35 (0.0%),75 (0.0%),128 (0.0%),129 (0.0%),115 (0.0%),158 (0.0%)
Z90.4,17 (0.0%),28 (0.0%),45 (0.0%),61 (0.0%),87 (0.0%),194 (0.0%)
...,...,...,...,...,...,...
N14.2,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
N14.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z99.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A49.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A46,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO24):'

,2019,2020,2021,2022,2023,2024
NULOS,97589 (99.8%),64568 (99.4%),67417 (99.3%),77245 (98.9%),89651 (98.8%),97759 (98.6%)
Z92.2,13 (0.0%),13 (0.0%),20 (0.0%),31 (0.0%),34 (0.0%),69 (0.1%)
Z92.4,5 (0.0%),5 (0.0%),20 (0.0%),41 (0.1%),39 (0.0%),45 (0.0%)
I10,8 (0.0%),9 (0.0%),11 (0.0%),18 (0.0%),21 (0.0%),30 (0.0%)
Z92.6,6 (0.0%),8 (0.0%),12 (0.0%),23 (0.0%),21 (0.0%),20 (0.0%)
...,...,...,...,...,...,...
L05.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
L03.3,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z99.3,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z99.1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z99.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO24):'

,2019,2020,2021,2022,2023,2024
NULOS,1052162 (99.9%),714408 (99.6%),744736 (99.4%),850520 (99.5%),943687 (99.5%),979729 (99.3%)
Z92.2,45 (0.0%),78 (0.0%),137 (0.0%),171 (0.0%),235 (0.0%),332 (0.0%)
Z92.4,31 (0.0%),41 (0.0%),90 (0.0%),116 (0.0%),178 (0.0%),215 (0.0%)
I10,27 (0.0%),66 (0.0%),117 (0.0%),111 (0.0%),94 (0.0%),128 (0.0%)
Z90.4,15 (0.0%),25 (0.0%),37 (0.0%),49 (0.0%),62 (0.0%),166 (0.0%)
...,...,...,...,...,...,...
A81.2,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A60.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A59.9,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A52.3,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A49.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[DIAGNOSTICO25] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO25: 2269 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO25):'

,2019,2020,2021,2022,2023,2024
NULOS,1150122 (99.9%),779573 (99.7%),813081 (99.5%),928762 (99.6%),1034504 (99.5%),1079003 (99.4%)
Z92.2,47 (0.0%),59 (0.0%),122 (0.0%),153 (0.0%),212 (0.0%),332 (0.0%)
Z92.4,22 (0.0%),50 (0.0%),84 (0.0%),126 (0.0%),189 (0.0%),215 (0.0%)
I10,23 (0.0%),57 (0.0%),122 (0.0%),89 (0.0%),122 (0.0%),153 (0.0%)
Z92.1,12 (0.0%),38 (0.0%),39 (0.0%),64 (0.0%),72 (0.0%),94 (0.0%)
...,...,...,...,...,...,...
H00.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
B16.9,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
B00.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B00.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B00.2,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO25):'

,2019,2020,2021,2022,2023,2024
NULOS,97649 (99.8%),64645 (99.6%),67531 (99.4%),77408 (99.2%),89887 (99.1%),98035 (98.9%)
Z92.2,11 (0.0%),10 (0.0%),11 (0.0%),31 (0.0%),40 (0.0%),53 (0.1%)
Z92.4,4 (0.0%),5 (0.0%),10 (0.0%),21 (0.0%),25 (0.0%),38 (0.0%)
I10,4 (0.0%),6 (0.0%),13 (0.0%),16 (0.0%),17 (0.0%),32 (0.0%)
Z92.6,1 (0.0%),4 (0.0%),8 (0.0%),9 (0.0%),9 (0.0%),30 (0.0%)
...,...,...,...,...,...,...
B98.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
F10.4,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
M47.97,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z91.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A40.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO25):'

,2019,2020,2021,2022,2023,2024
NULOS,1052473 (99.9%),714928 (99.7%),745550 (99.5%),851354 (99.6%),944617 (99.6%),980968 (99.4%)
Z92.2,36 (0.0%),49 (0.0%),111 (0.0%),122 (0.0%),172 (0.0%),279 (0.0%)
Z92.4,18 (0.0%),45 (0.0%),74 (0.0%),105 (0.0%),164 (0.0%),177 (0.0%)
I10,19 (0.0%),51 (0.0%),109 (0.0%),73 (0.0%),105 (0.0%),121 (0.0%)
Z29.0,8 (0.0%),32 (0.0%),58 (0.0%),55 (0.0%),63 (0.0%),64 (0.0%)
...,...,...,...,...,...,...
J84.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B86,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
B90.2,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B91,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
Z92.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[DIAGNOSTICO26] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO26: 2079 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO26):'

,2019,2020,2021,2022,2023,2024
NULOS,1150366 (99.9%),780024 (99.8%),813828 (99.6%),929552 (99.6%),1035480 (99.6%),1080211 (99.5%)
Z92.2,28 (0.0%),44 (0.0%),116 (0.0%),142 (0.0%),185 (0.0%),260 (0.0%)
Z92.4,16 (0.0%),34 (0.0%),56 (0.0%),100 (0.0%),133 (0.0%),161 (0.0%)
I10,21 (0.0%),46 (0.0%),83 (0.0%),79 (0.0%),75 (0.0%),113 (0.0%)
Z29.0,9 (0.0%),28 (0.0%),70 (0.0%),48 (0.0%),52 (0.0%),53 (0.0%)
...,...,...,...,...,...,...
N41.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
N41.2,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
N41.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
N20.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A04.8,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO26):'

,2019,2020,2021,2022,2023,2024
NULOS,97673 (99.8%),64702 (99.7%),67612 (99.5%),77534 (99.3%),90037 (99.3%),98225 (99.1%)
Z92.2,5 (0.0%),4 (0.0%),14 (0.0%),25 (0.0%),39 (0.0%),50 (0.1%)
Z92.4,5 (0.0%),5 (0.0%),9 (0.0%),18 (0.0%),24 (0.0%),30 (0.0%)
Z90.4,4 (0.0%),3 (0.0%),2 (0.0%),12 (0.0%),12 (0.0%),25 (0.0%)
Z86.4,3 (0.0%),2 (0.0%),2 (0.0%),14 (0.0%),14 (0.0%),20 (0.0%)
...,...,...,...,...,...,...
L98.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
L98.4,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
K85.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A08.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A49.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO26):'

,2019,2020,2021,2022,2023,2024
NULOS,1052693 (99.9%),715322 (99.8%),746216 (99.6%),852018 (99.7%),945443 (99.6%),981986 (99.5%)
Z92.2,23 (0.0%),40 (0.0%),102 (0.0%),117 (0.0%),146 (0.0%),210 (0.0%)
Z92.4,11 (0.0%),29 (0.0%),47 (0.0%),82 (0.0%),109 (0.0%),131 (0.0%)
I10,17 (0.0%),42 (0.0%),77 (0.0%),67 (0.0%),64 (0.0%),95 (0.0%)
Z29.0,9 (0.0%),25 (0.0%),64 (0.0%),46 (0.0%),40 (0.0%),44 (0.0%)
...,...,...,...,...,...,...
B35.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B37.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z97.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z96.9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A41.1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO27] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO27: 1900 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO27):'

,2019,2020,2021,2022,2023,2024
NULOS,1150574 (99.9%),780391 (99.8%),814441 (99.7%),930215 (99.7%),1036236 (99.7%),1081241 (99.6%)
Z92.2,22 (0.0%),29 (0.0%),85 (0.0%),82 (0.0%),167 (0.0%),209 (0.0%)
Z92.4,16 (0.0%),28 (0.0%),73 (0.0%),79 (0.0%),95 (0.0%),117 (0.0%)
I10,9 (0.0%),42 (0.0%),66 (0.0%),55 (0.0%),70 (0.0%),91 (0.0%)
Z90.4,10 (0.0%),13 (0.0%),23 (0.0%),47 (0.0%),36 (0.0%),96 (0.0%)
...,...,...,...,...,...,...
M99.53,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
N20.2,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
N20.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
N15.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
N14.1,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO27):'

,2019,2020,2021,2022,2023,2024
NULOS,97704 (99.9%),64741 (99.7%),67663 (99.6%),77659 (99.5%),90165 (99.4%),98392 (99.2%)
Z92.2,6 (0.0%),5 (0.0%),13 (0.0%),12 (0.0%),31 (0.0%),42 (0.0%)
Z92.4,3 (0.0%),3 (0.0%),9 (0.0%),21 (0.0%),15 (0.0%),24 (0.0%)
Z90.4,4 (0.0%),4 (0.0%),4 (0.0%),9 (0.0%),8 (0.0%),20 (0.0%)
I10,2 (0.0%),2 (0.0%),7 (0.0%),6 (0.0%),9 (0.0%),14 (0.0%)
...,...,...,...,...,...,...
K62.6,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
K62.8,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
K63.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
K22.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
K25.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO27):'

,2019,2020,2021,2022,2023,2024
NULOS,1052870 (99.9%),715650 (99.8%),746778 (99.7%),852556 (99.7%),946071 (99.7%),982849 (99.6%)
Z92.2,16 (0.0%),24 (0.0%),72 (0.0%),70 (0.0%),136 (0.0%),167 (0.0%)
Z92.4,13 (0.0%),25 (0.0%),64 (0.0%),58 (0.0%),80 (0.0%),93 (0.0%)
I10,7 (0.0%),40 (0.0%),59 (0.0%),49 (0.0%),61 (0.0%),77 (0.0%)
Z29.0,3 (0.0%),24 (0.0%),43 (0.0%),38 (0.0%),29 (0.0%),42 (0.0%)
...,...,...,...,...,...,...
M89.88,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M89.80,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
M89.50,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M86.65,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
M86.18,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[DIAGNOSTICO28] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO28: 1752 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO28):'

,2019,2020,2021,2022,2023,2024
NULOS,1150740 (99.9%),780679 (99.8%),814904 (99.8%),930743 (99.8%),1036837 (99.7%),1082006 (99.6%)
Z92.2,22 (0.0%),31 (0.0%),70 (0.0%),91 (0.0%),118 (0.0%),179 (0.0%)
Z92.4,20 (0.0%),24 (0.0%),31 (0.0%),52 (0.0%),89 (0.0%),128 (0.0%)
I10,8 (0.0%),22 (0.0%),49 (0.0%),33 (0.0%),47 (0.0%),65 (0.0%)
Z90.4,4 (0.0%),9 (0.0%),17 (0.0%),26 (0.0%),45 (0.0%),70 (0.0%)
...,...,...,...,...,...,...
M79.10,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
M77.91,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M76.85,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M75.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
M75.5,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO28):'

,2019,2020,2021,2022,2023,2024
NULOS,97732 (99.9%),64781 (99.8%),67719 (99.7%),77740 (99.6%),90278 (99.5%),98515 (99.4%)
Z92.2,2 (0.0%),5 (0.0%),9 (0.0%),19 (0.0%),15 (0.0%),18 (0.0%)
Z92.4,4 (0.0%),5 (0.0%),5 (0.0%),7 (0.0%),21 (0.0%),26 (0.0%)
Z90.4,0 (0.0%),3 (0.0%),2 (0.0%),10 (0.0%),9 (0.0%),14 (0.0%)
Z92.6,1 (0.0%),4 (0.0%),8 (0.0%),6 (0.0%),8 (0.0%),11 (0.0%)
...,...,...,...,...,...,...
K62.6,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
K62.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
K60.2,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z96.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z95.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO28):'

,2019,2020,2021,2022,2023,2024
NULOS,1053008 (99.9%),715898 (99.8%),747185 (99.8%),853003 (99.8%),946559 (99.8%),983491 (99.7%)
Z92.2,20 (0.0%),26 (0.0%),61 (0.0%),72 (0.0%),103 (0.0%),161 (0.0%)
Z92.4,16 (0.0%),19 (0.0%),26 (0.0%),45 (0.0%),68 (0.0%),102 (0.0%)
I10,7 (0.0%),20 (0.0%),41 (0.0%),27 (0.0%),39 (0.0%),58 (0.0%)
Z29.0,4 (0.0%),16 (0.0%),35 (0.0%),15 (0.0%),29 (0.0%),35 (0.0%)
...,...,...,...,...,...,...
I05.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
I05.1,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
I05.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
I31.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
I31.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO29] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO29: 1553 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO29):'

,2019,2020,2021,2022,2023,2024
NULOS,1150870 (100.0%),780926 (99.9%),815298 (99.8%),931106 (99.8%),1037374 (99.8%),1082716 (99.7%)
Z92.2,14 (0.0%),25 (0.0%),57 (0.0%),78 (0.0%),77 (0.0%),177 (0.0%)
Z92.4,18 (0.0%),12 (0.0%),35 (0.0%),47 (0.0%),66 (0.0%),96 (0.0%)
I10,5 (0.0%),19 (0.0%),30 (0.0%),30 (0.0%),38 (0.0%),51 (0.0%)
Z86.4,1 (0.0%),4 (0.0%),20 (0.0%),25 (0.0%),41 (0.0%),38 (0.0%)
...,...,...,...,...,...,...
A52.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A51.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
I70.10,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A07.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z97.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO29):'

,2019,2020,2021,2022,2023,2024
NULOS,97757 (99.9%),64800 (99.8%),67762 (99.8%),77801 (99.7%),90369 (99.6%),98637 (99.5%)
Z92.4,3 (0.0%),4 (0.0%),5 (0.0%),7 (0.0%),13 (0.0%),20 (0.0%)
Z92.2,1 (0.0%),3 (0.0%),5 (0.0%),11 (0.0%),9 (0.0%),17 (0.0%)
Z86.4,0 (0.0%),1 (0.0%),6 (0.0%),8 (0.0%),6 (0.0%),10 (0.0%)
Z90.4,1 (0.0%),1 (0.0%),3 (0.0%),3 (0.0%),7 (0.0%),11 (0.0%)
...,...,...,...,...,...,...
B49,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
I46.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
I44.7,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B37.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A09.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO29):'

,2019,2020,2021,2022,2023,2024
NULOS,1053113 (100.0%),716126 (99.9%),747536 (99.8%),853305 (99.8%),947005 (99.8%),984079 (99.7%)
Z92.2,13 (0.0%),22 (0.0%),52 (0.0%),67 (0.0%),68 (0.0%),160 (0.0%)
Z92.4,15 (0.0%),8 (0.0%),30 (0.0%),40 (0.0%),53 (0.0%),76 (0.0%)
I10,4 (0.0%),19 (0.0%),27 (0.0%),25 (0.0%),35 (0.0%),43 (0.0%)
Z29.0,5 (0.0%),8 (0.0%),31 (0.0%),28 (0.0%),15 (0.0%),23 (0.0%)
...,...,...,...,...,...,...
M05.99,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A40.8,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A19.9,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A07.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
D48.5,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO30] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO30: 1429 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO30):'

,2019,2020,2021,2022,2023,2024
NULOS,1150979 (100.0%),781126 (99.9%),815619 (99.8%),931448 (99.9%),1037793 (99.8%),1083263 (99.8%)
Z92.2,12 (0.0%),24 (0.0%),40 (0.0%),50 (0.0%),77 (0.0%),183 (0.0%)
Z92.4,9 (0.0%),8 (0.0%),24 (0.0%),43 (0.0%),53 (0.0%),96 (0.0%)
I10,6 (0.0%),17 (0.0%),29 (0.0%),31 (0.0%),33 (0.0%),44 (0.0%)
Z29.0,5 (0.0%),12 (0.0%),34 (0.0%),23 (0.0%),25 (0.0%),25 (0.0%)
...,...,...,...,...,...,...
J86.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
L03.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
K92.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z97.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
J43.2,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO30):'

,2019,2020,2021,2022,2023,2024
NULOS,97769 (99.9%),64822 (99.8%),67797 (99.8%),77860 (99.7%),90433 (99.7%),98749 (99.6%)
Z92.2,4 (0.0%),3 (0.0%),3 (0.0%),4 (0.0%),6 (0.0%),24 (0.0%)
Z92.4,2 (0.0%),2 (0.0%),4 (0.0%),10 (0.0%),9 (0.0%),11 (0.0%)
I10,1 (0.0%),3 (0.0%),7 (0.0%),9 (0.0%),5 (0.0%),3 (0.0%)
Z90.4,0 (0.0%),1 (0.0%),7 (0.0%),4 (0.0%),2 (0.0%),11 (0.0%)
...,...,...,...,...,...,...
K25.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
K22.3,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
K21.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z91.5,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
C79.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO30):'

,2019,2020,2021,2022,2023,2024
NULOS,1053210 (100.0%),716304 (99.9%),747822 (99.8%),853588 (99.9%),947360 (99.8%),984514 (99.8%)
Z92.2,8 (0.0%),21 (0.0%),37 (0.0%),46 (0.0%),71 (0.0%),159 (0.0%)
Z92.4,7 (0.0%),6 (0.0%),20 (0.0%),33 (0.0%),44 (0.0%),85 (0.0%)
I10,5 (0.0%),14 (0.0%),22 (0.0%),22 (0.0%),28 (0.0%),41 (0.0%)
Z29.0,4 (0.0%),10 (0.0%),32 (0.0%),20 (0.0%),21 (0.0%),24 (0.0%)
...,...,...,...,...,...,...
M47.82,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
M46.96,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M46.56,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M41.90,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
M35.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[DIAGNOSTICO31] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO31: 1244 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO31):'

,2019,2020,2021,2022,2023,2024
NULOS,1151064 (100.0%),781286 (99.9%),815878 (99.9%),931725 (99.9%),1038142 (99.9%),1083780 (99.8%)
Z92.2,3 (0.0%),14 (0.0%),29 (0.0%),42 (0.0%),61 (0.0%),98 (0.0%)
Z92.4,10 (0.0%),16 (0.0%),26 (0.0%),30 (0.0%),43 (0.0%),116 (0.0%)
I10,4 (0.0%),16 (0.0%),27 (0.0%),16 (0.0%),36 (0.0%),38 (0.0%)
Z29.0,6 (0.0%),9 (0.0%),32 (0.0%),12 (0.0%),18 (0.0%),18 (0.0%)
...,...,...,...,...,...,...
M86.67,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
M86.18,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
M81.90,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
M8000/1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A41.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO31):'

,2019,2020,2021,2022,2023,2024
NULOS,97785 (100.0%),64848 (99.9%),67824 (99.8%),77903 (99.8%),90489 (99.8%),98832 (99.7%)
Z92.2,1 (0.0%),0 (0.0%),5 (0.0%),9 (0.0%),8 (0.0%),19 (0.0%)
Z92.4,1 (0.0%),3 (0.0%),2 (0.0%),9 (0.0%),9 (0.0%),13 (0.0%)
I10,1 (0.0%),4 (0.0%),1 (0.0%),3 (0.0%),5 (0.0%),7 (0.0%)
Z92.6,0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%),3 (0.0%),11 (0.0%)
...,...,...,...,...,...,...
C78.7,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
C79.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
C79.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
D38.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A41.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO31):'

,2019,2020,2021,2022,2023,2024
NULOS,1053279 (100.0%),716438 (99.9%),748054 (99.9%),853822 (99.9%),947653 (99.9%),984948 (99.8%)
Z92.2,2 (0.0%),14 (0.0%),24 (0.0%),33 (0.0%),53 (0.0%),79 (0.0%)
Z92.4,9 (0.0%),13 (0.0%),24 (0.0%),21 (0.0%),34 (0.0%),103 (0.0%)
I10,3 (0.0%),12 (0.0%),26 (0.0%),13 (0.0%),31 (0.0%),31 (0.0%)
Z29.0,5 (0.0%),8 (0.0%),28 (0.0%),10 (0.0%),15 (0.0%),16 (0.0%)
...,...,...,...,...,...,...
B48.8,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B44.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
B44.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
B36.9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B35.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[DIAGNOSTICO32] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO32: 1158 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO32):'

,2019,2020,2021,2022,2023,2024
NULOS,1151130 (100.0%),781389 (99.9%),816092 (99.9%),931962 (99.9%),1038424 (99.9%),1084196 (99.9%)
Z92.2,10 (0.0%),15 (0.0%),24 (0.0%),23 (0.0%),34 (0.0%),90 (0.0%)
Z92.4,4 (0.0%),4 (0.0%),18 (0.0%),18 (0.0%),36 (0.0%),49 (0.0%)
I10,8 (0.0%),4 (0.0%),13 (0.0%),15 (0.0%),21 (0.0%),22 (0.0%)
Z29.0,2 (0.0%),10 (0.0%),24 (0.0%),8 (0.0%),15 (0.0%),22 (0.0%)
...,...,...,...,...,...,...
B44.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B48.7,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B49,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B91,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
G41.9,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO32):'

,2019,2020,2021,2022,2023,2024
NULOS,97795 (100.0%),64858 (99.9%),67848 (99.9%),77941 (99.8%),90533 (99.8%),98901 (99.7%)
Z92.2,3 (0.0%),4 (0.0%),4 (0.0%),3 (0.0%),5 (0.0%),16 (0.0%)
Z92.4,1 (0.0%),0 (0.0%),1 (0.0%),3 (0.0%),10 (0.0%),8 (0.0%)
I10,0 (0.0%),0 (0.0%),0 (0.0%),3 (0.0%),6 (0.0%),4 (0.0%)
Z92.6,0 (0.0%),2 (0.0%),0 (0.0%),2 (0.0%),7 (0.0%),2 (0.0%)
...,...,...,...,...,...,...
B96.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
I34.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B96.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
I35.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
Z21,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO32):'

,2019,2020,2021,2022,2023,2024
NULOS,1053335 (100.0%),716531 (99.9%),748244 (99.9%),854021 (99.9%),947891 (99.9%),985295 (99.9%)
Z92.2,7 (0.0%),11 (0.0%),20 (0.0%),20 (0.0%),29 (0.0%),74 (0.0%)
Z92.4,3 (0.0%),4 (0.0%),17 (0.0%),15 (0.0%),26 (0.0%),41 (0.0%)
Z29.0,1 (0.0%),10 (0.0%),21 (0.0%),7 (0.0%),15 (0.0%),18 (0.0%)
I10,8 (0.0%),4 (0.0%),13 (0.0%),12 (0.0%),15 (0.0%),18 (0.0%)
...,...,...,...,...,...,...
B02.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
B02.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A63.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A49.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
A49.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO33] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO33: 1034 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO33):'

,2019,2020,2021,2022,2023,2024
NULOS,1151187 (100.0%),781496 (99.9%),816263 (99.9%),932138 (99.9%),1038643 (99.9%),1084507 (99.9%)
Z92.2,6 (0.0%),9 (0.0%),23 (0.0%),26 (0.0%),42 (0.0%),58 (0.0%)
Z92.4,3 (0.0%),2 (0.0%),11 (0.0%),16 (0.0%),23 (0.0%),41 (0.0%)
I10,2 (0.0%),12 (0.0%),18 (0.0%),13 (0.0%),17 (0.0%),16 (0.0%)
Z29.0,2 (0.0%),11 (0.0%),20 (0.0%),10 (0.0%),16 (0.0%),13 (0.0%)
...,...,...,...,...,...,...
M32.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
M31.1,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
M25.61,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
M25.41,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
M23.89,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO33):'

,2019,2020,2021,2022,2023,2024
NULOS,97806 (100.0%),64876 (99.9%),67863 (99.9%),77969 (99.9%),90570 (99.8%),98951 (99.8%)
Z92.2,1 (0.0%),2 (0.0%),5 (0.0%),3 (0.0%),5 (0.0%),9 (0.0%)
I10,0 (0.0%),1 (0.0%),3 (0.0%),3 (0.0%),3 (0.0%),4 (0.0%)
Z92.4,0 (0.0%),1 (0.0%),0 (0.0%),2 (0.0%),4 (0.0%),5 (0.0%)
Z86.4,0 (0.0%),1 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),7 (0.0%)
...,...,...,...,...,...,...
I69.4,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
C92.9,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
D25.9,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
D35.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B37.4,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO33):'

,2019,2020,2021,2022,2023,2024
NULOS,1053381 (100.0%),716620 (99.9%),748400 (99.9%),854169 (99.9%),948073 (99.9%),985556 (99.9%)
Z92.2,5 (0.0%),7 (0.0%),18 (0.0%),23 (0.0%),37 (0.0%),49 (0.0%)
Z92.4,3 (0.0%),1 (0.0%),11 (0.0%),14 (0.0%),19 (0.0%),36 (0.0%)
I10,2 (0.0%),11 (0.0%),15 (0.0%),10 (0.0%),14 (0.0%),12 (0.0%)
Z29.0,2 (0.0%),10 (0.0%),18 (0.0%),10 (0.0%),14 (0.0%),10 (0.0%)
...,...,...,...,...,...,...
M23.89,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
M19.81,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
M16.7,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
A49.0,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A41.2,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO34] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO34: 935 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO34):'

,2019,2020,2021,2022,2023,2024
NULOS,1151223 (100.0%),781576 (100.0%),816396 (99.9%),932288 (99.9%),1038838 (99.9%),1084774 (99.9%)
Z92.2,3 (0.0%),11 (0.0%),12 (0.0%),17 (0.0%),26 (0.0%),42 (0.0%)
Z92.4,4 (0.0%),9 (0.0%),15 (0.0%),17 (0.0%),21 (0.0%),33 (0.0%)
Z29.0,1 (0.0%),4 (0.0%),15 (0.0%),16 (0.0%),15 (0.0%),11 (0.0%)
I10,1 (0.0%),5 (0.0%),13 (0.0%),12 (0.0%),13 (0.0%),16 (0.0%)
...,...,...,...,...,...,...
B97.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
C18.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
C53.9,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
C61,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
C78.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO34):'

,2019,2020,2021,2022,2023,2024
NULOS,97810 (100.0%),64885 (99.9%),67881 (99.9%),78002 (99.9%),90628 (99.9%),99015 (99.9%)
Z92.2,0 (0.0%),1 (0.0%),1 (0.0%),5 (0.0%),5 (0.0%),7 (0.0%)
Z92.4,0 (0.0%),3 (0.0%),3 (0.0%),4 (0.0%),2 (0.0%),6 (0.0%)
L89.1,0 (0.0%),1 (0.0%),1 (0.0%),3 (0.0%),1 (0.0%),2 (0.0%)
Z51.5,1 (0.0%),1 (0.0%),0 (0.0%),2 (0.0%),1 (0.0%),1 (0.0%)
...,...,...,...,...,...,...
Z93.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z95.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z98.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
Z98.2,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
Z99.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO34):'

,2019,2020,2021,2022,2023,2024
NULOS,1053413 (100.0%),716691 (100.0%),748515 (99.9%),854286 (99.9%),948210 (99.9%),985759 (99.9%)
Z92.2,3 (0.0%),10 (0.0%),11 (0.0%),12 (0.0%),21 (0.0%),35 (0.0%)
Z92.4,4 (0.0%),6 (0.0%),12 (0.0%),13 (0.0%),19 (0.0%),27 (0.0%)
Z29.0,1 (0.0%),4 (0.0%),13 (0.0%),15 (0.0%),13 (0.0%),11 (0.0%)
I10,1 (0.0%),4 (0.0%),13 (0.0%),12 (0.0%),11 (0.0%),14 (0.0%)
...,...,...,...,...,...,...
M00.97,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
L98.8,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
A15.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
B37.2,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
B37.1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[DIAGNOSTICO35] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad DIAGNOSTICO35: 799 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (DIAGNOSTICO35):'

,2019,2020,2021,2022,2023,2024
NULOS,1151259 (100.0%),781642 (100.0%),816554 (100.0%),932447 (100.0%),1039065 (99.9%),1085096 (99.9%)
Z92.2,6 (0.0%),3 (0.0%),14 (0.0%),11 (0.0%),20 (0.0%),35 (0.0%)
Z92.4,3 (0.0%),3 (0.0%),2 (0.0%),9 (0.0%),9 (0.0%),18 (0.0%)
I10,0 (0.0%),3 (0.0%),7 (0.0%),5 (0.0%),13 (0.0%),15 (0.0%)
E66.9,1 (0.0%),6 (0.0%),9 (0.0%),8 (0.0%),10 (0.0%),5 (0.0%)
...,...,...,...,...,...,...
I74.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
I74.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
I74.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z99.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z97.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (DIAGNOSTICO35):'

,2019,2020,2021,2022,2023,2024
NULOS,97814 (100.0%),64903 (100.0%),67919 (100.0%),78050 (100.0%),90701 (100.0%),99116 (100.0%)
Z87.1,1 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
I10,0 (0.0%),0 (0.0%),1 (0.0%),2 (0.0%),0 (0.0%),0 (0.0%)
Z87.4,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),1 (0.0%),1 (0.0%)
Z92.2,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%)
...,...,...,...,...,...,...
Z92.6,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z93.5,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
Z95.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
Z96.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
Z98.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (DIAGNOSTICO35):'

,2019,2020,2021,2022,2023,2024
NULOS,1053445 (100.0%),716739 (100.0%),748635 (100.0%),854397 (100.0%),948364 (99.9%),985980 (99.9%)
Z92.2,5 (0.0%),3 (0.0%),14 (0.0%),11 (0.0%),20 (0.0%),33 (0.0%)
Z92.4,3 (0.0%),3 (0.0%),2 (0.0%),9 (0.0%),8 (0.0%),18 (0.0%)
I10,0 (0.0%),3 (0.0%),6 (0.0%),3 (0.0%),13 (0.0%),15 (0.0%)
E66.9,1 (0.0%),5 (0.0%),9 (0.0%),8 (0.0%),10 (0.0%),5 (0.0%)
...,...,...,...,...,...,...
I71.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
I74.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
D47.3,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
D50.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
D52.9,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

### **20. Procedimientos Médicos (PROCEDIMIENTO1 al PROCEDIMIENTO30)**
- **Tipo de variable**: Clínica / Hospitalaria.
- **Descripción**: Bloque de 30 columnas que registran, mediante códigos CIE-9-MC o similares, las intervenciones médicas, quirúrgicas, diagnósticas o terapéuticas realizadas al paciente durante su hospitalización.
- **Cardinalidad**: Extrema y decreciente (inicia en 3.999 categorías únicas en el procedimiento 1, disminuyendo hasta ~760 categorías en el procedimiento 30).
- **Veredicto**: **Descartar columnas originales y Sintetizar**. Dado que el objetivo es caracterizar el consumo de recursos y la severidad del perfil oncológico en retrospectiva, no existe riesgo de fuga de datos. Sin embargo, el análisis de frecuencias masivo revela un obstáculo matemático severo: la variable `PROCEDIMIENTO2` ya presenta una tasa de nulos de entre 6.3% y 11.5%, la cual escala drásticamente hasta alcanzar un 99.3% de nulos en el `PROCEDIMIENTO30`. Aplicar *One-Hot Encoding* a este bloque inyectaría aproximadamente 30.000 nuevas columnas al conjunto de datos, provocando un sobreajuste masivo (*overfitting*) y el colapso de la memoria durante el entrenamiento de los algoritmos. Su valor predictivo se extraerá exclusivamente mediante variables derivadas.

---

### **Variables Derivadas de los Procedimientos (Ingeniería de Características)**

Para aprovechar la información crítica sobre las intervenciones hospitalarias sin sufrir la "maldición de la dimensionalidad", se crearán las siguientes variables consolidadas:

### **a) Carga de Procedimientos (NUM_PROCEDIMIENTOS)**
- **Tipo de variable**: Clínica Derivada (Numérica discreta).
- **Descripción**: Conteo del total de procedimientos válidos (no nulos) registrados a lo largo de las 30 columnas para un mismo paciente durante el episodio.
- **Cardinalidad**: Baja (rango numérico continuo acotado, ej. de 0 a 30).
- **Veredicto**: **Crear e Incluir**. Esta variable actúa como un proxy directo del esfuerzo clínico y del consumo de recursos. Los algoritmos de selección de características (como XGBoost) podrán utilizar este conteo para diferenciar numéricamente los episodios oncológicos altamente invasivos (múltiples cirugías o terapias complejas) de aquellos de manejo conservador.

### **b) Intervención Quirúrgica Principal (PROCEDIMIENTO_QUIRURGICO_PRINCIPAL)**
- **Tipo de variable**: Clínica Derivada (Categórica binarizada o agrupada).
- **Descripción**: Identificación del procedimiento más relevante (usualmente el registrado en `PROCEDIMIENTO1`) o clasificación del paciente según si fue sometido a una intervención quirúrgica mayor vs. tratamiento médico exclusivo.
- **Cardinalidad**: Muy Baja (si se binariza: *Sí/No*; o moderada si se agrupa en *Top 10 procedimientos*).
- **Veredicto**: **Crear e Incluir**. Para evitar las más de 3.900 categorías de la primera columna, se propone mapear el `PROCEDIMIENTO1` (o buscar en todo el bloque) utilizando un diccionario que agrupe los códigos en categorías de alta relevancia oncológica, tales como: *Cirugía de Resección Tumoral*, *Quimioterapia/Radioterapia*, *Biopsia/Diagnóstico Invasivo*, o *Procedimiento de Soporte*. Alternativamente, se puede binarizar simplemente como paciente "Quirúrgico" o "Médico". Esto permitirá al modelo asociar intervenciones invasivas con métricas de severidad o prolongación de la estadía.

In [22]:
for i in range(1, 31):
    total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,f"PROCEDIMIENTO{i}")
    mostrar_resultados(total, oncologico, control, f"PROCEDIMIENTO{i}")

[PROCEDIMIENTO1] Extrayendo y procesando datos masivos (Una sola pasada)...

✓ Cardinalidad PROCEDIMIENTO1: 3999 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO1):'

,2019,2020,2021,2022,2023,2024
73.59,68095 (5.9%),57658 (7.4%),50072 (6.1%),57559 (6.2%),55205 (5.3%),48546 (4.5%)
74.1,53690 (4.7%),45258 (5.8%),40735 (5.0%),46571 (5.0%),45974 (4.4%),42964 (4.0%)
51.23,41824 (3.6%),27527 (3.5%),29882 (3.7%),37397 (4.0%),42029 (4.0%),43394 (4.0%)
13.41,41636 (3.6%),20170 (2.6%),25214 (3.1%),37005 (4.0%),47898 (4.6%),48619 (4.5%)
87.03,35318 (3.1%),24939 (3.2%),24905 (3.0%),28057 (3.0%),29506 (2.8%),32838 (3.0%)
...,...,...,...,...,...,...
77.72,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.13,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.47,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.01,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO1):'

,2019,2020,2021,2022,2023,2024
99.25,24114 (24.6%),10044 (15.5%),8942 (13.2%),9068 (11.6%),10314 (11.4%),11617 (11.7%)
86.07,2583 (2.6%),1683 (2.6%),2435 (3.6%),3162 (4.1%),4354 (4.8%),4513 (4.6%)
88.01,2457 (2.5%),2035 (3.1%),2138 (3.1%),2533 (3.2%),3302 (3.6%),3817 (3.8%)
85.23,2278 (2.3%),1824 (2.8%),2187 (3.2%),2967 (3.8%),3410 (3.8%),3436 (3.5%)
87.41,1824 (1.9%),1932 (3.0%),1975 (2.9%),2519 (3.2%),2792 (3.1%),3155 (3.2%)
...,...,...,...,...,...,...
0.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.58,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.21,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.24,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
60.99,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO1):'

,2019,2020,2021,2022,2023,2024
73.59,68061 (6.5%),57636 (8.0%),50043 (6.7%),57516 (6.7%),55173 (5.8%),48498 (4.9%)
74.1,53657 (5.1%),45208 (6.3%),40680 (5.4%),46501 (5.4%),45899 (4.8%),42896 (4.3%)
51.23,41461 (3.9%),27225 (3.8%),29529 (3.9%),36939 (4.3%),41425 (4.4%),42801 (4.3%)
13.41,41309 (3.9%),20007 (2.8%),24981 (3.3%),36551 (4.3%),47340 (5.0%),48064 (4.9%)
87.03,33778 (3.2%),23769 (3.3%),23721 (3.2%),26464 (3.1%),27696 (2.9%),30819 (3.1%)
...,...,...,...,...,...,...
42.19,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.35,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
5.19,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
42.1,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
78.87,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO2] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO2: 3969 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO2):'

,2019,2020,2021,2022,2023,2024
NULOS,132502 (11.5%),55347 (7.1%),51631 (6.3%),67978 (7.3%),83626 (8.0%),94931 (8.7%)
99.29,102621 (8.9%),54600 (7.0%),53019 (6.5%),65742 (7.0%),71470 (6.9%),72809 (6.7%)
99.21,64988 (5.6%),42169 (5.4%),39519 (4.8%),43777 (4.7%),46987 (4.5%),48289 (4.4%)
90.59,52427 (4.6%),35276 (4.5%),33450 (4.1%),35040 (3.8%),37576 (3.6%),36018 (3.3%)
13.71,41858 (3.6%),20455 (2.6%),25591 (3.1%),38303 (4.1%),49688 (4.8%),49933 (4.6%)
...,...,...,...,...,...,...
00.02,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
57.98,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.84,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
8.49,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.54,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO2):'

,2019,2020,2021,2022,2023,2024
99.29,10650 (10.9%),5924 (9.1%),5710 (8.4%),6199 (7.9%),7074 (7.8%),8183 (8.3%)
NULOS,16148 (16.5%),5031 (7.7%),4437 (6.5%),4816 (6.2%),6163 (6.8%),6904 (7.0%)
99.23,6578 (6.7%),2706 (4.2%),2433 (3.6%),2577 (3.3%),2840 (3.1%),3263 (3.3%)
99.21,3850 (3.9%),2642 (4.1%),2556 (3.8%),3093 (4.0%),3400 (3.7%),3647 (3.7%)
88.01,2482 (2.5%),2215 (3.4%),2385 (3.5%),3008 (3.9%),3620 (4.0%),4012 (4.0%)
...,...,...,...,...,...,...
4.42,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
40.61,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.27,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.42,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.32,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO2):'

,2019,2020,2021,2022,2023,2024
NULOS,116354 (11.0%),50316 (7.0%),47194 (6.3%),63162 (7.4%),77463 (8.2%),88027 (8.9%)
99.29,91971 (8.7%),48676 (6.8%),47309 (6.3%),59543 (7.0%),64396 (6.8%),64626 (6.5%)
99.21,61138 (5.8%),39527 (5.5%),36963 (4.9%),40684 (4.8%),43587 (4.6%),44642 (4.5%)
13.71,41533 (3.9%),20289 (2.8%),25352 (3.4%),37823 (4.4%),49119 (5.2%),49341 (5.0%)
90.59,49390 (4.7%),33103 (4.6%),31318 (4.2%),32660 (3.8%),34763 (3.7%),33169 (3.4%)
...,...,...,...,...,...,...
25.09,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
26.41,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.57,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.54,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
00.02,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO3] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO3: 3726 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO3):'

,2019,2020,2021,2022,2023,2024
NULOS,247157 (21.5%),109200 (14.0%),105742 (12.9%),142643 (15.3%),174470 (16.8%),190110 (17.5%)
99.29,122029 (10.6%),76103 (9.7%),76442 (9.4%),91772 (9.8%),105199 (10.1%),106092 (9.8%)
99.21,71368 (6.2%),50226 (6.4%),47963 (5.9%),54233 (5.8%),61660 (5.9%),65584 (6.0%)
90.59,78171 (6.8%),54419 (7.0%),50818 (6.2%),52594 (5.6%),56563 (5.4%),56075 (5.2%)
75.34,26404 (2.3%),22348 (2.9%),20026 (2.5%),24600 (2.6%),24070 (2.3%),21505 (2.0%)
...,...,...,...,...,...,...
5.81,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
39.81,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.46,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.45,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.43,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO3):'

,2019,2020,2021,2022,2023,2024
NULOS,25391 (26.0%),9568 (14.7%),8818 (13.0%),10450 (13.4%),13019 (14.4%),14143 (14.3%)
99.29,12010 (12.3%),7647 (11.8%),7508 (11.1%),8739 (11.2%),10091 (11.1%),11065 (11.2%)
99.21,4504 (4.6%),3240 (5.0%),3488 (5.1%),4295 (5.5%),5075 (5.6%),5516 (5.6%)
90.59,4365 (4.5%),3377 (5.2%),3300 (4.9%),3396 (4.3%),3957 (4.4%),4308 (4.3%)
88.01,2097 (2.1%),2024 (3.1%),2132 (3.1%),2721 (3.5%),3167 (3.5%),3472 (3.5%)
...,...,...,...,...,...,...
87.07,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.24,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.97,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.85,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.83,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO3):'

,2019,2020,2021,2022,2023,2024
NULOS,221766 (21.0%),99632 (13.9%),96924 (12.9%),132193 (15.5%),161451 (17.0%),175967 (17.8%)
99.29,110019 (10.4%),68456 (9.5%),68934 (9.2%),83033 (9.7%),95108 (10.0%),95027 (9.6%)
90.59,73806 (7.0%),51042 (7.1%),47518 (6.3%),49198 (5.8%),52606 (5.5%),51767 (5.2%)
99.21,66864 (6.3%),46986 (6.6%),44475 (5.9%),49938 (5.8%),56585 (6.0%),60068 (6.1%)
75.34,26385 (2.5%),22325 (3.1%),20009 (2.7%),24570 (2.9%),24045 (2.5%),21478 (2.2%)
...,...,...,...,...,...,...
10.29,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
1.51,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.97,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.49,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.45,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO4] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO4: 3437 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO4):'

,2019,2020,2021,2022,2023,2024
NULOS,349721 (30.4%),163688 (20.9%),158830 (19.4%),213064 (22.8%),257942 (24.8%),282100 (26.0%)
99.29,106155 (9.2%),73417 (9.4%),72695 (8.9%),81969 (8.8%),94180 (9.1%),98643 (9.1%)
90.59,80990 (7.0%),60403 (7.7%),57994 (7.1%),61693 (6.6%),64735 (6.2%),64299 (5.9%)
99.21,58115 (5.0%),44730 (5.7%),42880 (5.2%),48003 (5.1%),56849 (5.5%),61326 (5.6%)
99.19,27625 (2.4%),20478 (2.6%),22130 (2.7%),24494 (2.6%),27576 (2.7%),28232 (2.6%)
...,...,...,...,...,...,...
59.19,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
12.40,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
33.71,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
44.03,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
44.01,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO4):'

,2019,2020,2021,2022,2023,2024
NULOS,37131 (38.0%),15420 (23.8%),14460 (21.3%),16633 (21.3%),19896 (21.9%),21981 (22.2%)
99.29,8881 (9.1%),6366 (9.8%),6794 (10.0%),7784 (10.0%),9457 (10.4%),10068 (10.2%)
90.59,5273 (5.4%),3932 (6.1%),3799 (5.6%),4181 (5.4%),4775 (5.3%),5142 (5.2%)
99.21,3816 (3.9%),3094 (4.8%),3273 (4.8%),4028 (5.2%),4914 (5.4%),5488 (5.5%)
99.19,2839 (2.9%),2213 (3.4%),2601 (3.8%),2990 (3.8%),3519 (3.9%),3648 (3.7%)
...,...,...,...,...,...,...
42.68,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
42.63,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
42.59,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
42.58,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
00.25,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO4):'

,2019,2020,2021,2022,2023,2024
NULOS,312590 (29.7%),148268 (20.7%),144370 (19.3%),196431 (23.0%),238046 (25.1%),260119 (26.4%)
99.29,97274 (9.2%),67051 (9.4%),65901 (8.8%),74185 (8.7%),84723 (8.9%),88575 (9.0%)
90.59,75717 (7.2%),56471 (7.9%),54195 (7.2%),57512 (6.7%),59960 (6.3%),59157 (6.0%)
99.21,54299 (5.2%),41636 (5.8%),39607 (5.3%),43975 (5.1%),51935 (5.5%),55838 (5.7%)
99.19,24786 (2.4%),18265 (2.5%),19529 (2.6%),21504 (2.5%),24057 (2.5%),24584 (2.5%)
...,...,...,...,...,...,...
2.33,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
2.32,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
2.03,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.84,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
56.75,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO5] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO5: 3119 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO5):'

,2019,2020,2021,2022,2023,2024
NULOS,455085 (39.5%),221286 (28.3%),212568 (26.0%),282085 (30.2%),336208 (32.3%),364832 (33.6%)
99.29,88177 (7.7%),64232 (8.2%),65160 (8.0%),71411 (7.7%),80377 (7.7%),82034 (7.6%)
90.59,72365 (6.3%),56481 (7.2%),56159 (6.9%),59674 (6.4%),64267 (6.2%),64941 (6.0%)
99.21,46359 (4.0%),38730 (5.0%),36682 (4.5%),40469 (4.3%),46529 (4.5%),48724 (4.5%)
99.19,27174 (2.4%),21930 (2.8%),24277 (3.0%),25804 (2.8%),29308 (2.8%),30522 (2.8%)
...,...,...,...,...,...,...
55.54,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
55.7,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
8.51,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
55.83,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
06.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO5):'

,2019,2020,2021,2022,2023,2024
NULOS,45907 (46.9%),20729 (31.9%),19715 (29.0%),23123 (29.6%),27694 (30.5%),30096 (30.4%)
99.29,6182 (6.3%),4944 (7.6%),5362 (7.9%),6040 (7.7%),7190 (7.9%),7915 (8.0%)
90.59,4589 (4.7%),3908 (6.0%),3746 (5.5%),4308 (5.5%),4925 (5.4%),5133 (5.2%)
99.21,3137 (3.2%),2689 (4.1%),2833 (4.2%),3165 (4.1%),3862 (4.3%),4293 (4.3%)
99.19,2662 (2.7%),2308 (3.6%),2769 (4.1%),3137 (4.0%),3591 (4.0%),3756 (3.8%)
...,...,...,...,...,...,...
85.24,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
85.23,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
85.22,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
85.93,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
85.91,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO5):'

,2019,2020,2021,2022,2023,2024
NULOS,409178 (38.8%),200557 (28.0%),192853 (25.7%),258962 (30.3%),308514 (32.5%),334736 (33.9%)
99.29,81995 (7.8%),59288 (8.3%),59798 (8.0%),65371 (7.6%),73187 (7.7%),74119 (7.5%)
90.59,67776 (6.4%),52573 (7.3%),52413 (7.0%),55366 (6.5%),59342 (6.3%),59808 (6.1%)
99.21,43222 (4.1%),36041 (5.0%),33849 (4.5%),37304 (4.4%),42667 (4.5%),44431 (4.5%)
99.19,24512 (2.3%),19622 (2.7%),21508 (2.9%),22667 (2.7%),25717 (2.7%),26766 (2.7%)
...,...,...,...,...,...,...
34.23,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.52,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.92,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.7,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.64,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO6] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO6: 2799 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO6):'

,2019,2020,2021,2022,2023,2024
NULOS,558118 (48.5%),282842 (36.2%),270342 (33.1%),350638 (37.6%),413437 (39.8%),446118 (41.1%)
99.29,68106 (5.9%),53226 (6.8%),54966 (6.7%),59735 (6.4%),66800 (6.4%),67119 (6.2%)
90.59,59160 (5.1%),47938 (6.1%),47973 (5.9%),50939 (5.5%),55261 (5.3%),57037 (5.3%)
99.21,36644 (3.2%),30942 (4.0%),31041 (3.8%),34564 (3.7%),38038 (3.7%),39520 (3.6%)
99.19,23136 (2.0%),21099 (2.7%),23571 (2.9%),23855 (2.6%),27249 (2.6%),29435 (2.7%)
...,...,...,...,...,...,...
0.16,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
53.1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
00.80,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
99.43,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.46,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO6):'

,2019,2020,2021,2022,2023,2024
NULOS,52993 (54.2%),25550 (39.4%),24657 (36.3%),29061 (37.2%),34603 (38.1%),37880 (38.2%)
99.29,4769 (4.9%),4030 (6.2%),4407 (6.5%),4883 (6.3%),5677 (6.3%),6224 (6.3%)
90.59,3905 (4.0%),3324 (5.1%),3251 (4.8%),3635 (4.7%),4263 (4.7%),4573 (4.6%)
99.21,2566 (2.6%),2237 (3.4%),2391 (3.5%),2643 (3.4%),3210 (3.5%),3664 (3.7%)
99.19,2331 (2.4%),2138 (3.3%),2438 (3.6%),2738 (3.5%),3286 (3.6%),3631 (3.7%)
...,...,...,...,...,...,...
0.59,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.49,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
36.99,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
36.12,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
36.11,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO6):'

,2019,2020,2021,2022,2023,2024
NULOS,505125 (47.9%),257292 (35.9%),245685 (32.8%),321577 (37.6%),378834 (39.9%),408238 (41.4%)
99.29,63337 (6.0%),49196 (6.9%),50559 (6.8%),54852 (6.4%),61123 (6.4%),60895 (6.2%)
90.59,55255 (5.2%),44614 (6.2%),44722 (6.0%),47304 (5.5%),50998 (5.4%),52464 (5.3%)
99.21,34078 (3.2%),28705 (4.0%),28650 (3.8%),31921 (3.7%),34828 (3.7%),35856 (3.6%)
99.19,20805 (2.0%),18961 (2.6%),21133 (2.8%),21117 (2.5%),23963 (2.5%),25804 (2.6%)
...,...,...,...,...,...,...
35.23,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
36.10,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
35.7,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
36.1,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
35.24,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[PROCEDIMIENTO7] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO7: 2470 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO7):'

,2019,2020,2021,2022,2023,2024
NULOS,655550 (56.9%),347420 (44.4%),331853 (40.6%),420493 (45.1%),490978 (47.2%),526241 (48.5%)
99.29,51758 (4.5%),42952 (5.5%),44290 (5.4%),48194 (5.2%),53605 (5.2%),53918 (5.0%)
90.59,47133 (4.1%),39790 (5.1%),40479 (5.0%),43370 (4.6%),47607 (4.6%),50012 (4.6%)
99.21,28420 (2.5%),24780 (3.2%),27028 (3.3%),28414 (3.0%),31016 (3.0%),31616 (2.9%)
99.19,19313 (1.7%),18564 (2.4%),21204 (2.6%),21079 (2.3%),23416 (2.3%),25202 (2.3%)
...,...,...,...,...,...,...
77.80,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
77.34,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
77.4,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
77.41,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.86,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO7):'

,2019,2020,2021,2022,2023,2024
NULOS,59169 (60.5%),30194 (46.5%),29425 (43.3%),34734 (44.5%),41133 (45.3%),44720 (45.1%)
99.29,3710 (3.8%),3203 (4.9%),3329 (4.9%),3616 (4.6%),4420 (4.9%),4792 (4.8%)
90.59,3221 (3.3%),2750 (4.2%),2976 (4.4%),3158 (4.0%),3662 (4.0%),4067 (4.1%)
99.19,1992 (2.0%),1927 (3.0%),2041 (3.0%),2299 (2.9%),2812 (3.1%),3072 (3.1%)
99.21,2039 (2.1%),1835 (2.8%),2062 (3.0%),2326 (3.0%),2700 (3.0%),2945 (3.0%)
...,...,...,...,...,...,...
0.59,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
82.85,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
81.96,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
81.92,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.12,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO7):'

,2019,2020,2021,2022,2023,2024
NULOS,596381 (56.6%),317226 (44.2%),302428 (40.4%),385759 (45.1%),449845 (47.4%),481521 (48.8%)
99.29,48048 (4.6%),39749 (5.5%),40961 (5.5%),44578 (5.2%),49185 (5.2%),49126 (5.0%)
90.59,43912 (4.2%),37040 (5.2%),37503 (5.0%),40212 (4.7%),43945 (4.6%),45945 (4.7%)
99.21,26381 (2.5%),22945 (3.2%),24966 (3.3%),26088 (3.1%),28316 (3.0%),28671 (2.9%)
99.19,17321 (1.6%),16637 (2.3%),19163 (2.6%),18780 (2.2%),20604 (2.2%),22130 (2.2%)
...,...,...,...,...,...,...
53.71,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
54.73,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
54.71,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
54.29,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.86,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO8] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO8: 2225 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO8):'

,2019,2020,2021,2022,2023,2024
NULOS,747426 (64.9%),411584 (52.6%),393631 (48.2%),490897 (52.6%),567312 (54.6%),603624 (55.6%)
99.29,37658 (3.3%),33102 (4.2%),36156 (4.4%),38310 (4.1%),41748 (4.0%),42148 (3.9%)
90.59,37077 (3.2%),31606 (4.0%),33416 (4.1%),35005 (3.8%),39248 (3.8%),42079 (3.9%)
99.21,21258 (1.8%),19006 (2.4%),21665 (2.7%),22549 (2.4%),24152 (2.3%),25108 (2.3%)
99.19,15767 (1.4%),15985 (2.0%),19177 (2.3%),18446 (2.0%),20115 (1.9%),21307 (2.0%)
...,...,...,...,...,...,...
65.23,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
38.69,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
38.68,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
81.83,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
81.81,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO8):'

,2019,2020,2021,2022,2023,2024
NULOS,64634 (66.1%),34456 (53.1%),33683 (49.6%),39680 (50.8%),46874 (51.7%),50978 (51.4%)
99.29,2683 (2.7%),2517 (3.9%),2794 (4.1%),3024 (3.9%),3659 (4.0%),3833 (3.9%)
90.59,2637 (2.7%),2212 (3.4%),2408 (3.5%),2607 (3.3%),3156 (3.5%),3443 (3.5%)
99.19,1622 (1.7%),1473 (2.3%),1769 (2.6%),1944 (2.5%),2335 (2.6%),2621 (2.6%)
99.21,1647 (1.7%),1528 (2.4%),1645 (2.4%),1902 (2.4%),2184 (2.4%),2511 (2.5%)
...,...,...,...,...,...,...
01.31,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.32,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.29,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.24,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.01,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO8):'

,2019,2020,2021,2022,2023,2024
NULOS,682792 (64.8%),377128 (52.6%),359948 (48.1%),451217 (52.8%),520438 (54.8%),552646 (56.0%)
99.29,34975 (3.3%),30585 (4.3%),33362 (4.5%),35286 (4.1%),38089 (4.0%),38315 (3.9%)
90.59,34440 (3.3%),29394 (4.1%),31008 (4.1%),32398 (3.8%),36092 (3.8%),38636 (3.9%)
99.21,19611 (1.9%),17478 (2.4%),20020 (2.7%),20647 (2.4%),21968 (2.3%),22597 (2.3%)
99.19,14145 (1.3%),14512 (2.0%),17408 (2.3%),16502 (1.9%),17780 (1.9%),18686 (1.9%)
...,...,...,...,...,...,...
83.62,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
83.61,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
83.31,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
83.19,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
82.85,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[PROCEDIMIENTO9] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO9: 2044 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO9):'

,2019,2020,2021,2022,2023,2024
NULOS,827416 (71.9%),470898 (60.2%),452415 (55.4%),557805 (59.8%),640062 (61.6%),676906 (62.3%)
99.29,27246 (2.4%),24516 (3.1%),27847 (3.4%),29071 (3.1%),31263 (3.0%),31945 (2.9%)
90.59,26862 (2.3%),24155 (3.1%),27063 (3.3%),28207 (3.0%),31644 (3.0%),33341 (3.1%)
99.21,15869 (1.4%),15072 (1.9%),17190 (2.1%),17564 (1.9%),18481 (1.8%),19478 (1.8%)
99.19,12678 (1.1%),13138 (1.7%),16014 (2.0%),15296 (1.6%),16325 (1.6%),17170 (1.6%)
...,...,...,...,...,...,...
99.53,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.51,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.45,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.56,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.52,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO9):'

,2019,2020,2021,2022,2023,2024
NULOS,69368 (70.9%),38361 (59.1%),37603 (55.4%),44045 (56.4%),52097 (57.4%),56763 (57.2%)
99.29,2194 (2.2%),1956 (3.0%),2237 (3.3%),2440 (3.1%),2837 (3.1%),3085 (3.1%)
90.59,1967 (2.0%),1848 (2.8%),1984 (2.9%),2163 (2.8%),2583 (2.8%),2982 (3.0%)
99.19,1387 (1.4%),1383 (2.1%),1482 (2.2%),1647 (2.1%),1815 (2.0%),2148 (2.2%)
99.21,1366 (1.4%),1224 (1.9%),1486 (2.2%),1632 (2.1%),1783 (2.0%),2124 (2.1%)
...,...,...,...,...,...,...
52.21,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
51.99,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
00.32,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
00.29,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
00.09,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO9):'

,2019,2020,2021,2022,2023,2024
NULOS,758048 (72.0%),432537 (60.3%),414812 (55.4%),513760 (60.1%),587965 (62.0%),620143 (62.9%)
90.59,24895 (2.4%),22307 (3.1%),25079 (3.3%),26044 (3.0%),29061 (3.1%),30359 (3.1%)
99.29,25052 (2.4%),22560 (3.1%),25610 (3.4%),26631 (3.1%),28426 (3.0%),28860 (2.9%)
99.21,14503 (1.4%),13848 (1.9%),15704 (2.1%),15932 (1.9%),16698 (1.8%),17354 (1.8%)
99.19,11291 (1.1%),11755 (1.6%),14532 (1.9%),13649 (1.6%),14510 (1.5%),15022 (1.5%)
...,...,...,...,...,...,...
87.34,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
87.33,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
88.12,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
87.91,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
88.46,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO10] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO10: 1925 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO10):'

,2019,2020,2021,2022,2023,2024
NULOS,894425 (77.7%),523950 (67.0%),507623 (62.1%),619643 (66.4%),705976 (67.9%),743686 (68.5%)
90.59,18692 (1.6%),18334 (2.3%),20980 (2.6%),21566 (2.3%),24396 (2.3%),26111 (2.4%)
99.29,19229 (1.7%),18349 (2.3%),20990 (2.6%),21550 (2.3%),22928 (2.2%),23638 (2.2%)
99.21,11232 (1.0%),11033 (1.4%),13121 (1.6%),13396 (1.4%),14093 (1.4%),14933 (1.4%)
99.19,9599 (0.8%),10678 (1.4%),13162 (1.6%),12159 (1.3%),12892 (1.2%),13853 (1.3%)
...,...,...,...,...,...,...
87.59,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
87.99,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
87.89,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
88.15,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
88.36,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO10):'

,2019,2020,2021,2022,2023,2024
NULOS,73489 (75.1%),41745 (64.3%),41246 (60.7%),48114 (61.6%),56798 (62.6%),62120 (62.7%)
99.29,1716 (1.8%),1610 (2.5%),1802 (2.7%),2008 (2.6%),2302 (2.5%),2516 (2.5%)
90.59,1534 (1.6%),1467 (2.3%),1682 (2.5%),1767 (2.3%),2134 (2.4%),2432 (2.5%)
99.19,1162 (1.2%),1129 (1.7%),1261 (1.9%),1411 (1.8%),1609 (1.8%),1747 (1.8%)
99.21,1077 (1.1%),1018 (1.6%),1160 (1.7%),1299 (1.7%),1547 (1.7%),1673 (1.7%)
...,...,...,...,...,...,...
90.22,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.76,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.74,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.54,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
00.13,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO10):'

,2019,2020,2021,2022,2023,2024
NULOS,820936 (77.9%),482205 (67.3%),466377 (62.3%),571529 (66.9%),649178 (68.4%),681566 (69.1%)
90.59,17158 (1.6%),16867 (2.4%),19298 (2.6%),19799 (2.3%),22262 (2.3%),23679 (2.4%)
99.29,17513 (1.7%),16739 (2.3%),19188 (2.6%),19542 (2.3%),20626 (2.2%),21122 (2.1%)
99.21,10155 (1.0%),10015 (1.4%),11961 (1.6%),12097 (1.4%),12546 (1.3%),13260 (1.3%)
99.19,8437 (0.8%),9549 (1.3%),11901 (1.6%),10748 (1.3%),11283 (1.2%),12106 (1.2%)
...,...,...,...,...,...,...
99.85,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.64,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.32,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.31,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.97,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[PROCEDIMIENTO11] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO11: 1759 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO11):'

,2019,2020,2021,2022,2023,2024
NULOS,947996 (82.3%),569395 (72.8%),556980 (68.2%),673719 (72.2%),763340 (73.4%),801067 (73.8%)
90.59,12969 (1.1%),13083 (1.7%),15685 (1.9%),16253 (1.7%),18604 (1.8%),19823 (1.8%)
99.29,13394 (1.2%),13282 (1.7%),15740 (1.9%),15939 (1.7%),17039 (1.6%),17827 (1.6%)
99.21,8194 (0.7%),8499 (1.1%),10478 (1.3%),10530 (1.1%),10946 (1.1%),11820 (1.1%)
99.19,7020 (0.6%),8305 (1.1%),10452 (1.3%),9714 (1.0%),10085 (1.0%),10835 (1.0%)
...,...,...,...,...,...,...
0.15,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.74,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.97,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
03.59,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
03.71,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO11):'

,2019,2020,2021,2022,2023,2024
NULOS,76989 (78.7%),44776 (69.0%),44520 (65.5%),51864 (66.4%),61109 (67.4%),66724 (67.3%)
99.29,1387 (1.4%),1311 (2.0%),1487 (2.2%),1610 (2.1%),1810 (2.0%),1963 (2.0%)
90.59,1271 (1.3%),1197 (1.8%),1341 (2.0%),1500 (1.9%),1755 (1.9%),2084 (2.1%)
99.19,879 (0.9%),881 (1.4%),1005 (1.5%),1103 (1.4%),1271 (1.4%),1451 (1.5%)
99.21,881 (0.9%),843 (1.3%),994 (1.5%),1133 (1.5%),1243 (1.4%),1459 (1.5%)
...,...,...,...,...,...,...
40.5,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
90.16,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
90.19,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.74,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.76,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO11):'

,2019,2020,2021,2022,2023,2024
NULOS,871007 (82.7%),524619 (73.2%),512460 (68.4%),621855 (72.8%),702231 (74.0%),734343 (74.4%)
90.59,11698 (1.1%),11886 (1.7%),14344 (1.9%),14753 (1.7%),16849 (1.8%),17739 (1.8%)
99.29,12007 (1.1%),11971 (1.7%),14253 (1.9%),14329 (1.7%),15229 (1.6%),15864 (1.6%)
99.21,7313 (0.7%),7656 (1.1%),9484 (1.3%),9397 (1.1%),9703 (1.0%),10361 (1.1%)
99.19,6141 (0.6%),7424 (1.0%),9447 (1.3%),8611 (1.0%),8814 (0.9%),9384 (1.0%)
...,...,...,...,...,...,...
40.23,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
40.22,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.77,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
99.57,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.48,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO12] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO12: 1565 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO12):'

,2019,2020,2021,2022,2023,2024
NULOS,989556 (85.9%),607234 (77.7%),599257 (73.4%),718564 (77.0%),810767 (78.0%),849464 (78.2%)
90.59,9056 (0.8%),9604 (1.2%),11795 (1.4%),11812 (1.3%),13551 (1.3%),14989 (1.4%)
99.29,9550 (0.8%),9721 (1.2%),11878 (1.5%),11927 (1.3%),12596 (1.2%),13629 (1.3%)
99.21,6087 (0.5%),6704 (0.9%),8467 (1.0%),8148 (0.9%),8688 (0.8%),9041 (0.8%)
93.18,5508 (0.5%),6348 (0.8%),8061 (1.0%),8086 (0.9%),8995 (0.9%),9097 (0.8%)
...,...,...,...,...,...,...
38.09,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
38.22,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
90.12,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.64,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
51.83,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO12):'

,2019,2020,2021,2022,2023,2024
NULOS,79981 (81.8%),47327 (72.9%),47462 (69.9%),55192 (70.7%),64863 (71.5%),70879 (71.5%)
99.29,1079 (1.1%),1049 (1.6%),1152 (1.7%),1343 (1.7%),1585 (1.7%),1689 (1.7%)
90.59,1016 (1.0%),972 (1.5%),1119 (1.6%),1213 (1.6%),1443 (1.6%),1697 (1.7%)
93.18,686 (0.7%),687 (1.1%),828 (1.2%),1012 (1.3%),1173 (1.3%),1242 (1.3%)
99.21,700 (0.7%),688 (1.1%),904 (1.3%),979 (1.3%),1101 (1.2%),1190 (1.2%)
...,...,...,...,...,...,...
24.8,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.74,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.76,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
1.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
1.25,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO12):'

,2019,2020,2021,2022,2023,2024
NULOS,909575 (86.3%),559907 (78.1%),551795 (73.7%),663372 (77.6%),745904 (78.6%),778585 (78.9%)
90.59,8040 (0.8%),8632 (1.2%),10676 (1.4%),10599 (1.2%),12108 (1.3%),13292 (1.3%)
99.29,8471 (0.8%),8672 (1.2%),10726 (1.4%),10584 (1.2%),11011 (1.2%),11940 (1.2%)
99.21,5387 (0.5%),6016 (0.8%),7563 (1.0%),7169 (0.8%),7587 (0.8%),7851 (0.8%)
93.18,4822 (0.5%),5661 (0.8%),7233 (1.0%),7074 (0.8%),7822 (0.8%),7855 (0.8%)
...,...,...,...,...,...,...
70.12,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
7.82,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
7.22,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
69.99,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.85,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO13] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO13: 1482 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO13):'

,2019,2020,2021,2022,2023,2024
NULOS,1021771 (88.7%),637896 (81.6%),635043 (77.7%),755457 (81.0%),849814 (81.7%),889733 (81.9%)
90.59,6534 (0.6%),7403 (0.9%),8950 (1.1%),8802 (0.9%),10397 (1.0%),11587 (1.1%)
99.29,7098 (0.6%),7397 (0.9%),9238 (1.1%),9349 (1.0%),10002 (1.0%),10391 (1.0%)
93.18,4640 (0.4%),5335 (0.7%),6945 (0.9%),6932 (0.7%),7411 (0.7%),7567 (0.7%)
99.21,4575 (0.4%),5200 (0.7%),6647 (0.8%),6643 (0.7%),6858 (0.7%),7303 (0.7%)
...,...,...,...,...,...,...
99.47,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.56,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.53,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
1.18,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
1.14,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO13):'

,2019,2020,2021,2022,2023,2024
NULOS,82627 (84.5%),49614 (76.4%),50148 (73.8%),58179 (74.5%),67991 (75.0%),74586 (75.2%)
99.29,860 (0.9%),816 (1.3%),947 (1.4%),1193 (1.5%),1219 (1.3%),1351 (1.4%)
90.59,764 (0.8%),809 (1.2%),920 (1.4%),935 (1.2%),1266 (1.4%),1418 (1.4%)
93.18,618 (0.6%),592 (0.9%),775 (1.1%),872 (1.1%),1011 (1.1%),1015 (1.0%)
99.21,532 (0.5%),597 (0.9%),691 (1.0%),798 (1.0%),884 (1.0%),1064 (1.1%)
...,...,...,...,...,...,...
1.23,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.56,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.44,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.39,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.38,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO13):'

,2019,2020,2021,2022,2023,2024
NULOS,939144 (89.1%),588282 (82.0%),584895 (78.1%),697278 (81.6%),781823 (82.4%),815147 (82.6%)
90.59,5770 (0.5%),6594 (0.9%),8030 (1.1%),7867 (0.9%),9131 (1.0%),10169 (1.0%)
99.29,6238 (0.6%),6581 (0.9%),8291 (1.1%),8156 (1.0%),8783 (0.9%),9040 (0.9%)
93.18,4022 (0.4%),4743 (0.7%),6170 (0.8%),6060 (0.7%),6400 (0.7%),6552 (0.7%)
99.21,4043 (0.4%),4603 (0.6%),5956 (0.8%),5845 (0.7%),5974 (0.6%),6239 (0.6%)
...,...,...,...,...,...,...
44.66,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.53,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.47,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.53,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.31,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO14] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO14: 1422 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO14):'

,2019,2020,2021,2022,2023,2024
NULOS,1046447 (90.9%),662497 (84.7%),663785 (81.3%),784735 (84.1%),881286 (84.8%),922412 (85.0%)
99.29,5143 (0.4%),5733 (0.7%),7349 (0.9%),7347 (0.8%),7784 (0.7%),8336 (0.8%)
90.59,4883 (0.4%),5518 (0.7%),6979 (0.9%),6586 (0.7%),7925 (0.8%),9017 (0.8%)
93.18,3947 (0.3%),4720 (0.6%),5956 (0.7%),6034 (0.6%),6362 (0.6%),6652 (0.6%)
99.21,3568 (0.3%),4123 (0.5%),5434 (0.7%),5419 (0.6%),5478 (0.5%),6061 (0.6%)
...,...,...,...,...,...,...
89.55,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
89.53,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
89.43,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
34.71,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
34.52,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO14):'

,2019,2020,2021,2022,2023,2024
NULOS,84896 (86.8%),51799 (79.8%),52581 (77.4%),60776 (77.8%),70951 (78.2%),77765 (78.4%)
99.29,624 (0.6%),652 (1.0%),845 (1.2%),910 (1.2%),974 (1.1%),1151 (1.2%)
90.59,719 (0.7%),648 (1.0%),706 (1.0%),778 (1.0%),953 (1.1%),1166 (1.2%)
93.18,534 (0.5%),497 (0.8%),635 (0.9%),750 (1.0%),862 (1.0%),974 (1.0%)
99.21,470 (0.5%),526 (0.8%),585 (0.9%),718 (0.9%),718 (0.8%),829 (0.8%)
...,...,...,...,...,...,...
87.65,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
87.66,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
97.54,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
97.55,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
97.61,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO14):'

,2019,2020,2021,2022,2023,2024
NULOS,961551 (91.3%),610698 (85.2%),611204 (81.6%),723959 (84.7%),810335 (85.4%),844647 (85.6%)
99.29,4519 (0.4%),5081 (0.7%),6504 (0.9%),6437 (0.8%),6810 (0.7%),7185 (0.7%)
90.59,4164 (0.4%),4870 (0.7%),6273 (0.8%),5808 (0.7%),6972 (0.7%),7851 (0.8%)
93.18,3413 (0.3%),4223 (0.6%),5321 (0.7%),5284 (0.6%),5500 (0.6%),5678 (0.6%)
99.21,3098 (0.3%),3597 (0.5%),4849 (0.6%),4701 (0.5%),4760 (0.5%),5232 (0.5%)
...,...,...,...,...,...,...
87.35,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
87.75,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
87.66,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
87.65,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
87.64,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO15] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO15: 1281 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO15):'

,2019,2020,2021,2022,2023,2024
NULOS,1065510 (92.5%),682086 (87.2%),686976 (84.1%),808255 (86.6%),906292 (87.2%),948491 (87.4%)
99.29,4031 (0.4%),4499 (0.6%),5928 (0.7%),5893 (0.6%),6291 (0.6%),6550 (0.6%)
90.59,3617 (0.3%),4318 (0.6%),5605 (0.7%),5273 (0.6%),6219 (0.6%),7120 (0.7%)
93.18,3308 (0.3%),4056 (0.5%),5233 (0.6%),5177 (0.6%),5444 (0.5%),5493 (0.5%)
99.21,2930 (0.3%),3246 (0.4%),4242 (0.5%),4228 (0.5%),4602 (0.4%),4790 (0.4%)
...,...,...,...,...,...,...
90.84,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.43,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.53,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.56,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.62,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO15):'

,2019,2020,2021,2022,2023,2024
NULOS,86787 (88.7%),53693 (82.7%),54643 (80.4%),63066 (80.8%),73523 (81.0%),80636 (81.3%)
99.29,544 (0.6%),534 (0.8%),675 (1.0%),764 (1.0%),840 (0.9%),904 (0.9%)
90.59,537 (0.5%),562 (0.9%),583 (0.9%),661 (0.8%),844 (0.9%),917 (0.9%)
93.18,486 (0.5%),449 (0.7%),569 (0.8%),614 (0.8%),741 (0.8%),798 (0.8%)
99.21,412 (0.4%),394 (0.6%),455 (0.7%),521 (0.7%),606 (0.7%),700 (0.7%)
...,...,...,...,...,...,...
2.06,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.47,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.41,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.22,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO15):'

,2019,2020,2021,2022,2023,2024
NULOS,978723 (92.9%),628393 (87.6%),632333 (84.4%),745189 (87.2%),832769 (87.8%),867855 (88.0%)
99.29,3487 (0.3%),3965 (0.6%),5253 (0.7%),5129 (0.6%),5451 (0.6%),5646 (0.6%)
90.59,3080 (0.3%),3756 (0.5%),5022 (0.7%),4612 (0.5%),5375 (0.6%),6203 (0.6%)
93.18,2822 (0.3%),3607 (0.5%),4664 (0.6%),4563 (0.5%),4703 (0.5%),4695 (0.5%)
99.21,2518 (0.2%),2852 (0.4%),3787 (0.5%),3707 (0.4%),3996 (0.4%),4090 (0.4%)
...,...,...,...,...,...,...
1.12,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
1.11,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
1.02,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.76,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
87.07,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO16] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO16: 1269 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO16):'

,2019,2020,2021,2022,2023,2024
NULOS,1080305 (93.8%),697918 (89.3%),706058 (86.4%),827316 (88.7%),926712 (89.1%),969543 (89.3%)
99.29,3118 (0.3%),3577 (0.5%),4886 (0.6%),4779 (0.5%),5140 (0.5%),5049 (0.5%)
90.59,2927 (0.3%),3422 (0.4%),4456 (0.5%),4238 (0.5%),5112 (0.5%),5620 (0.5%)
93.18,2827 (0.2%),3409 (0.4%),4456 (0.5%),4430 (0.5%),4643 (0.4%),4628 (0.4%)
99.21,2286 (0.2%),2701 (0.3%),3881 (0.5%),3680 (0.4%),3843 (0.4%),3911 (0.4%)
...,...,...,...,...,...,...
00.19,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
84.17,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.94,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.93,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.91,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO16):'

,2019,2020,2021,2022,2023,2024
NULOS,88442 (90.4%),55313 (85.2%),56498 (83.2%),65076 (83.4%),75736 (83.5%),83096 (83.8%)
99.29,448 (0.5%),467 (0.7%),533 (0.8%),599 (0.8%),692 (0.8%),705 (0.7%)
90.59,411 (0.4%),437 (0.7%),464 (0.7%),534 (0.7%),756 (0.8%),736 (0.7%)
93.18,383 (0.4%),393 (0.6%),447 (0.7%),590 (0.8%),630 (0.7%),669 (0.7%)
99.21,319 (0.3%),315 (0.5%),423 (0.6%),491 (0.6%),521 (0.6%),556 (0.6%)
...,...,...,...,...,...,...
99.94,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.83,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
99.78,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
00.45,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
00.40,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO16):'

,2019,2020,2021,2022,2023,2024
NULOS,991863 (94.1%),642605 (89.6%),649560 (86.7%),762240 (89.2%),850976 (89.7%),886447 (89.8%)
99.29,2670 (0.3%),3110 (0.4%),4353 (0.6%),4180 (0.5%),4448 (0.5%),4344 (0.4%)
90.59,2516 (0.2%),2985 (0.4%),3992 (0.5%),3704 (0.4%),4356 (0.5%),4884 (0.5%)
93.18,2444 (0.2%),3016 (0.4%),4009 (0.5%),3840 (0.4%),4013 (0.4%),3959 (0.4%)
99.21,1967 (0.2%),2386 (0.3%),3458 (0.5%),3189 (0.4%),3322 (0.4%),3355 (0.3%)
...,...,...,...,...,...,...
0.22,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
59.94,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
99.31,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
00.19,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
00.12,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[PROCEDIMIENTO17] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO17: 1175 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO17):'

,2019,2020,2021,2022,2023,2024
NULOS,1091848 (94.8%),710760 (90.9%),721740 (88.4%),843145 (90.4%),943480 (90.8%),986638 (90.9%)
99.29,2469 (0.2%),2784 (0.4%),3844 (0.5%),3791 (0.4%),4242 (0.4%),4271 (0.4%)
93.18,2404 (0.2%),2870 (0.4%),3979 (0.5%),3868 (0.4%),3923 (0.4%),3839 (0.4%)
90.59,2196 (0.2%),2563 (0.3%),3459 (0.4%),3496 (0.4%),4053 (0.4%),4572 (0.4%)
99.21,1833 (0.2%),2218 (0.3%),3275 (0.4%),2991 (0.3%),3041 (0.3%),3312 (0.3%)
...,...,...,...,...,...,...
86.99,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.61,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.64,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.65,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.74,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO17):'

,2019,2020,2021,2022,2023,2024
NULOS,89821 (91.8%),56653 (87.3%),58128 (85.6%),66779 (85.5%),77726 (85.7%),85186 (85.9%)
93.18,310 (0.3%),362 (0.6%),415 (0.6%),503 (0.6%),573 (0.6%),564 (0.6%)
99.29,321 (0.3%),320 (0.5%),366 (0.5%),484 (0.6%),552 (0.6%),621 (0.6%)
90.59,335 (0.3%),325 (0.5%),360 (0.5%),432 (0.6%),580 (0.6%),619 (0.6%)
99.21,250 (0.3%),224 (0.3%),325 (0.5%),359 (0.5%),430 (0.5%),472 (0.5%)
...,...,...,...,...,...,...
39.98,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.74,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
86.7,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.48,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.46,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO17):'

,2019,2020,2021,2022,2023,2024
NULOS,1002027 (95.1%),654107 (91.2%),663612 (88.6%),776366 (90.8%),865754 (91.2%),901452 (91.4%)
99.29,2148 (0.2%),2464 (0.3%),3478 (0.5%),3307 (0.4%),3690 (0.4%),3650 (0.4%)
93.18,2094 (0.2%),2508 (0.3%),3564 (0.5%),3365 (0.4%),3350 (0.4%),3275 (0.3%)
90.59,1861 (0.2%),2238 (0.3%),3099 (0.4%),3064 (0.4%),3473 (0.4%),3953 (0.4%)
99.21,1583 (0.2%),1994 (0.3%),2950 (0.4%),2632 (0.3%),2611 (0.3%),2840 (0.3%)
...,...,...,...,...,...,...
2.06,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
90.73,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
90.86,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
2.42,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
2.41,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO18] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO18: 1177 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO18):'

,2019,2020,2021,2022,2023,2024
NULOS,1101101 (95.6%),721080 (92.2%),734294 (89.9%),856279 (91.8%),957010 (92.1%),1000565 (92.1%)
93.18,1985 (0.2%),2503 (0.3%),3362 (0.4%),3279 (0.4%),3474 (0.3%),3394 (0.3%)
99.29,2024 (0.2%),2293 (0.3%),3230 (0.4%),3147 (0.3%),3386 (0.3%),3458 (0.3%)
90.59,1793 (0.2%),2128 (0.3%),2924 (0.4%),2837 (0.3%),3391 (0.3%),3766 (0.3%)
99.21,1447 (0.1%),1916 (0.2%),2656 (0.3%),2494 (0.3%),2620 (0.3%),2777 (0.3%)
...,...,...,...,...,...,...
90.76,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.94,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.93,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.49,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.48,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO18):'

,2019,2020,2021,2022,2023,2024
NULOS,90958 (93.0%),57837 (89.1%),59385 (87.4%),68335 (87.5%),79393 (87.5%),86959 (87.7%)
93.18,256 (0.3%),308 (0.5%),351 (0.5%),452 (0.6%),508 (0.6%),508 (0.5%)
90.59,292 (0.3%),248 (0.4%),315 (0.5%),378 (0.5%),500 (0.6%),524 (0.5%)
99.29,267 (0.3%),262 (0.4%),310 (0.5%),392 (0.5%),473 (0.5%),488 (0.5%)
99.21,209 (0.2%),242 (0.4%),280 (0.4%),330 (0.4%),364 (0.4%),402 (0.4%)
...,...,...,...,...,...,...
00.19,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
00.29,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
00.33,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
00.40,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
00.66,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO18):'

,2019,2020,2021,2022,2023,2024
NULOS,1010143 (95.9%),663243 (92.5%),674909 (90.1%),787944 (92.2%),877617 (92.5%),913606 (92.6%)
93.18,1729 (0.2%),2195 (0.3%),3011 (0.4%),2827 (0.3%),2966 (0.3%),2886 (0.3%)
99.29,1757 (0.2%),2031 (0.3%),2920 (0.4%),2755 (0.3%),2913 (0.3%),2970 (0.3%)
90.59,1501 (0.1%),1880 (0.3%),2609 (0.3%),2459 (0.3%),2891 (0.3%),3242 (0.3%)
99.21,1238 (0.1%),1674 (0.2%),2376 (0.3%),2164 (0.3%),2256 (0.2%),2375 (0.2%)
...,...,...,...,...,...,...
0.64,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.74,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
00.22,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.55,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.56,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO19] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO19: 1139 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO19):'

,2019,2020,2021,2022,2023,2024
NULOS,1108489 (96.3%),729627 (93.3%),744731 (91.2%),867027 (92.9%),968399 (93.2%),1012263 (93.2%)
93.18,1714 (0.1%),2090 (0.3%),2894 (0.4%),2729 (0.3%),2815 (0.3%),2891 (0.3%)
99.29,1623 (0.1%),1827 (0.2%),2748 (0.3%),2595 (0.3%),2790 (0.3%),2939 (0.3%)
90.59,1516 (0.1%),1835 (0.2%),2462 (0.3%),2425 (0.3%),2709 (0.3%),3141 (0.3%)
99.21,1208 (0.1%),1474 (0.2%),2174 (0.3%),2025 (0.2%),2155 (0.2%),2207 (0.2%)
...,...,...,...,...,...,...
DESCONOCIDO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.57,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.54,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.51,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.6,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO19):'

,2019,2020,2021,2022,2023,2024
NULOS,91961 (94.0%),58868 (90.7%),60508 (89.1%),69634 (89.2%),80875 (89.2%),88498 (89.3%)
93.18,246 (0.3%),216 (0.3%),295 (0.4%),385 (0.5%),395 (0.4%),454 (0.5%)
99.29,238 (0.2%),229 (0.4%),310 (0.5%),353 (0.5%),378 (0.4%),426 (0.4%)
90.59,216 (0.2%),214 (0.3%),255 (0.4%),299 (0.4%),404 (0.4%),491 (0.5%)
99.21,181 (0.2%),180 (0.3%),251 (0.4%),273 (0.3%),329 (0.4%),333 (0.3%)
...,...,...,...,...,...,...
0.28,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.16,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.10,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
12.73,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.29,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO19):'

,2019,2020,2021,2022,2023,2024
NULOS,1016528 (96.5%),670759 (93.6%),684223 (91.4%),797393 (93.3%),887524 (93.5%),923765 (93.6%)
93.18,1468 (0.1%),1874 (0.3%),2599 (0.3%),2344 (0.3%),2420 (0.3%),2437 (0.2%)
99.29,1385 (0.1%),1598 (0.2%),2438 (0.3%),2242 (0.3%),2412 (0.3%),2513 (0.3%)
90.59,1300 (0.1%),1621 (0.2%),2207 (0.3%),2126 (0.2%),2305 (0.2%),2650 (0.3%)
99.21,1027 (0.1%),1294 (0.2%),1923 (0.3%),1752 (0.2%),1826 (0.2%),1874 (0.2%)
...,...,...,...,...,...,...
46.03,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
45.94,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
45.79,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
45.76,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
84.56,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO20] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO20: 1042 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO20):'

,2019,2020,2021,2022,2023,2024
NULOS,1114667 (96.8%),736639 (94.2%),753638 (92.3%),875735 (93.9%),977905 (94.1%),1022139 (94.1%)
93.18,1452 (0.1%),1893 (0.2%),2599 (0.3%),2367 (0.3%),2447 (0.2%),2495 (0.2%)
99.29,1276 (0.1%),1526 (0.2%),2211 (0.3%),2119 (0.2%),2396 (0.2%),2333 (0.2%)
90.59,1249 (0.1%),1556 (0.2%),2121 (0.3%),1929 (0.2%),2391 (0.2%),2563 (0.2%)
99.21,1047 (0.1%),1273 (0.2%),1847 (0.2%),1727 (0.2%),1826 (0.2%),2012 (0.2%)
...,...,...,...,...,...,...
99.47,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.91,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.92,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.95,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
79.75,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO20):'

,2019,2020,2021,2022,2023,2024
NULOS,92753 (94.8%),59718 (92.0%),61488 (90.5%),70761 (90.6%),82138 (90.5%),89860 (90.6%)
93.18,227 (0.2%),210 (0.3%),252 (0.4%),278 (0.4%),349 (0.4%),383 (0.4%)
99.29,177 (0.2%),191 (0.3%),228 (0.3%),298 (0.4%),368 (0.4%),324 (0.3%)
90.59,203 (0.2%),179 (0.3%),210 (0.3%),231 (0.3%),337 (0.4%),391 (0.4%)
99.21,135 (0.1%),145 (0.2%),171 (0.3%),215 (0.3%),249 (0.3%),274 (0.3%)
...,...,...,...,...,...,...
23.2,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
22.0,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.31,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
21.03,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.39,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO20):'

,2019,2020,2021,2022,2023,2024
NULOS,1021914 (97.0%),676921 (94.4%),692150 (92.4%),804974 (94.2%),895767 (94.4%),932279 (94.5%)
93.18,1225 (0.1%),1683 (0.2%),2347 (0.3%),2089 (0.2%),2098 (0.2%),2112 (0.2%)
99.29,1099 (0.1%),1335 (0.2%),1983 (0.3%),1821 (0.2%),2028 (0.2%),2009 (0.2%)
90.59,1046 (0.1%),1377 (0.2%),1911 (0.3%),1698 (0.2%),2054 (0.2%),2172 (0.2%)
99.21,912 (0.1%),1128 (0.2%),1676 (0.2%),1512 (0.2%),1577 (0.2%),1738 (0.2%)
...,...,...,...,...,...,...
88.35,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
87.77,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
87.91,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
87.94,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
88.03,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[PROCEDIMIENTO21] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO21: 996 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO21):'

,2019,2020,2021,2022,2023,2024
NULOS,1120005 (97.3%),742594 (95.0%),761216 (93.2%),883265 (94.7%),985904 (94.8%),1030516 (94.9%)
93.18,1203 (0.1%),1534 (0.2%),2154 (0.3%),2043 (0.2%),2111 (0.2%),2202 (0.2%)
90.59,1052 (0.1%),1279 (0.2%),1855 (0.2%),1761 (0.2%),2029 (0.2%),2163 (0.2%)
99.29,1106 (0.1%),1233 (0.2%),1818 (0.2%),1768 (0.2%),1960 (0.2%),2012 (0.2%)
99.21,834 (0.1%),1127 (0.1%),1535 (0.2%),1490 (0.2%),1564 (0.2%),1650 (0.2%)
...,...,...,...,...,...,...
75.38,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.53,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.22,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
87.75,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
43.0,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO21):'

,2019,2020,2021,2022,2023,2024
NULOS,93514 (95.6%),60469 (93.1%),62326 (91.8%),71677 (91.8%),83175 (91.7%),91081 (91.9%)
93.18,168 (0.2%),167 (0.3%),217 (0.3%),293 (0.4%),323 (0.4%),314 (0.3%)
90.59,176 (0.2%),148 (0.2%),181 (0.3%),239 (0.3%),299 (0.3%),318 (0.3%)
99.29,150 (0.2%),173 (0.3%),210 (0.3%),242 (0.3%),281 (0.3%),303 (0.3%)
99.21,117 (0.1%),135 (0.2%),138 (0.2%),203 (0.3%),236 (0.3%),223 (0.2%)
...,...,...,...,...,...,...
0.31,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.13,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.24,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.94,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.13,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO21):'

,2019,2020,2021,2022,2023,2024
NULOS,1026491 (97.4%),682125 (95.1%),698890 (93.3%),811588 (94.9%),902729 (95.1%),939435 (95.2%)
93.18,1035 (0.1%),1367 (0.2%),1937 (0.3%),1750 (0.2%),1788 (0.2%),1888 (0.2%)
90.59,876 (0.1%),1131 (0.2%),1674 (0.2%),1522 (0.2%),1730 (0.2%),1845 (0.2%)
99.29,956 (0.1%),1060 (0.1%),1608 (0.2%),1526 (0.2%),1679 (0.2%),1709 (0.2%)
99.21,717 (0.1%),992 (0.1%),1397 (0.2%),1287 (0.2%),1328 (0.1%),1427 (0.1%)
...,...,...,...,...,...,...
1.31,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
1.13,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
1.09,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.93,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.69,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[PROCEDIMIENTO22] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO22: 965 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO22):'

,2019,2020,2021,2022,2023,2024
NULOS,1124371 (97.7%),747495 (95.6%),767678 (94.0%),889545 (95.4%),992761 (95.5%),1037489 (95.5%)
93.18,990 (0.1%),1332 (0.2%),1959 (0.2%),1730 (0.2%),1813 (0.2%),1917 (0.2%)
90.59,902 (0.1%),1131 (0.1%),1669 (0.2%),1473 (0.2%),1700 (0.2%),1963 (0.2%)
99.29,871 (0.1%),1058 (0.1%),1561 (0.2%),1508 (0.2%),1663 (0.2%),1583 (0.1%)
99.21,714 (0.1%),943 (0.1%),1293 (0.2%),1268 (0.1%),1357 (0.1%),1438 (0.1%)
...,...,...,...,...,...,...
4.11,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
40.11,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
41.32,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
42.25,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
42.92,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO22):'

,2019,2020,2021,2022,2023,2024
NULOS,94167 (96.3%),61049 (94.0%),63031 (92.8%),72545 (92.9%),84137 (92.7%),92132 (92.9%)
93.18,148 (0.2%),166 (0.3%),197 (0.3%),219 (0.3%),251 (0.3%),291 (0.3%)
99.29,129 (0.1%),143 (0.2%),184 (0.3%),206 (0.3%),239 (0.3%),270 (0.3%)
90.59,129 (0.1%),114 (0.2%),179 (0.3%),171 (0.2%),220 (0.2%),293 (0.3%)
99.21,96 (0.1%),133 (0.2%),130 (0.2%),170 (0.2%),172 (0.2%),206 (0.2%)
...,...,...,...,...,...,...
99.31,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
21.02,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.09,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
2.42,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
2.05,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO22):'

,2019,2020,2021,2022,2023,2024
NULOS,1030204 (97.8%),686446 (95.7%),704647 (94.1%),817000 (95.6%),908624 (95.8%),945357 (95.8%)
93.18,842 (0.1%),1166 (0.2%),1762 (0.2%),1511 (0.2%),1562 (0.2%),1626 (0.2%)
90.59,773 (0.1%),1017 (0.1%),1490 (0.2%),1302 (0.2%),1480 (0.2%),1670 (0.2%)
99.29,742 (0.1%),915 (0.1%),1377 (0.2%),1302 (0.2%),1424 (0.2%),1313 (0.1%)
99.21,618 (0.1%),810 (0.1%),1163 (0.2%),1098 (0.1%),1185 (0.1%),1232 (0.1%)
...,...,...,...,...,...,...
90.05,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
89.69,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
90.44,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
90.35,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
90.76,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[PROCEDIMIENTO23] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO23: 935 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO23):'

,2019,2020,2021,2022,2023,2024
NULOS,1128075 (98.0%),751892 (96.2%),773283 (94.7%),894899 (95.9%),998579 (96.1%),1043581 (96.1%)
93.18,849 (0.1%),1167 (0.1%),1600 (0.2%),1479 (0.2%),1600 (0.2%),1631 (0.2%)
90.59,766 (0.1%),1012 (0.1%),1465 (0.2%),1306 (0.1%),1586 (0.2%),1609 (0.1%)
99.29,707 (0.1%),953 (0.1%),1371 (0.2%),1218 (0.1%),1363 (0.1%),1400 (0.1%)
99.21,560 (0.0%),727 (0.1%),1133 (0.1%),1070 (0.1%),1180 (0.1%),1212 (0.1%)
...,...,...,...,...,...,...
0.43,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
38.85,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
38.31,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
38.16,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.09,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO23):'

,2019,2020,2021,2022,2023,2024
NULOS,94664 (96.8%),61598 (94.9%),63645 (93.7%),73254 (93.8%),84952 (93.6%),93061 (93.9%)
93.18,120 (0.1%),131 (0.2%),175 (0.3%),199 (0.3%),240 (0.3%),225 (0.2%)
90.59,107 (0.1%),119 (0.2%),146 (0.2%),167 (0.2%),222 (0.2%),211 (0.2%)
99.29,110 (0.1%),109 (0.2%),127 (0.2%),177 (0.2%),196 (0.2%),206 (0.2%)
99.21,71 (0.1%),97 (0.1%),114 (0.2%),142 (0.2%),150 (0.2%),151 (0.2%)
...,...,...,...,...,...,...
96.7,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
97.62,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
31.29,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
31.41,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
31.79,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO23):'

,2019,2020,2021,2022,2023,2024
NULOS,1033411 (98.1%),690294 (96.3%),709638 (94.7%),821645 (96.1%),913627 (96.3%),950520 (96.3%)
93.18,729 (0.1%),1036 (0.1%),1425 (0.2%),1280 (0.1%),1360 (0.1%),1406 (0.1%)
90.59,659 (0.1%),893 (0.1%),1319 (0.2%),1139 (0.1%),1364 (0.1%),1398 (0.1%)
99.29,597 (0.1%),844 (0.1%),1244 (0.2%),1041 (0.1%),1167 (0.1%),1194 (0.1%)
99.21,489 (0.0%),630 (0.1%),1019 (0.1%),928 (0.1%),1030 (0.1%),1061 (0.1%)
...,...,...,...,...,...,...
0.48,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
89.56,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
54.51,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.43,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
87.15,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO24] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO24: 898 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO24):'

,2019,2020,2021,2022,2023,2024
NULOS,1131188 (98.2%),755763 (96.7%),778489 (95.3%),899686 (96.4%),1003712 (96.5%),1048870 (96.6%)
93.18,737 (0.1%),1000 (0.1%),1272 (0.2%),1221 (0.1%),1329 (0.1%),1432 (0.1%)
90.59,645 (0.1%),825 (0.1%),1199 (0.1%),1033 (0.1%),1234 (0.1%),1382 (0.1%)
99.29,592 (0.1%),721 (0.1%),1134 (0.1%),1036 (0.1%),1110 (0.1%),1202 (0.1%)
89.65,639 (0.1%),732 (0.1%),1050 (0.1%),836 (0.1%),925 (0.1%),889 (0.1%)
...,...,...,...,...,...,...
1.23,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.35,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.32,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.31,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.15,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO24):'

,2019,2020,2021,2022,2023,2024
NULOS,95123 (97.2%),62064 (95.6%),64229 (94.6%),73872 (94.6%),85715 (94.5%),93820 (94.6%)
93.18,99 (0.1%),126 (0.2%),122 (0.2%),176 (0.2%),188 (0.2%),213 (0.2%)
90.59,93 (0.1%),103 (0.2%),131 (0.2%),122 (0.2%),148 (0.2%),204 (0.2%)
99.29,81 (0.1%),81 (0.1%),119 (0.2%),125 (0.2%),140 (0.2%),158 (0.2%)
99.21,65 (0.1%),65 (0.1%),80 (0.1%),114 (0.1%),132 (0.1%),141 (0.1%)
...,...,...,...,...,...,...
23.01,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
24.19,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
27.21,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
29.11,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.23,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO24):'

,2019,2020,2021,2022,2023,2024
NULOS,1036065 (98.3%),693699 (96.8%),714260 (95.4%),825814 (96.6%),917997 (96.7%),955050 (96.8%)
93.18,638 (0.1%),874 (0.1%),1150 (0.2%),1045 (0.1%),1141 (0.1%),1219 (0.1%)
90.59,552 (0.1%),722 (0.1%),1068 (0.1%),911 (0.1%),1086 (0.1%),1178 (0.1%)
99.29,511 (0.0%),640 (0.1%),1015 (0.1%),911 (0.1%),970 (0.1%),1044 (0.1%)
89.65,549 (0.1%),678 (0.1%),969 (0.1%),764 (0.1%),815 (0.1%),800 (0.1%)
...,...,...,...,...,...,...
1.23,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
1.31,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
10.91,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.31,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.01,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO25] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO25: 879 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO25):'

,2019,2020,2021,2022,2023,2024
NULOS,1133940 (98.5%),759104 (97.1%),782935 (95.8%),903863 (96.9%),1008267 (97.0%),1053402 (97.0%)
93.18,652 (0.1%),788 (0.1%),1079 (0.1%),1039 (0.1%),1175 (0.1%),1191 (0.1%)
90.59,539 (0.0%),691 (0.1%),1005 (0.1%),875 (0.1%),1085 (0.1%),1211 (0.1%)
99.29,472 (0.0%),611 (0.1%),1001 (0.1%),858 (0.1%),1012 (0.1%),1049 (0.1%)
57.94,472 (0.0%),614 (0.1%),890 (0.1%),816 (0.1%),737 (0.1%),801 (0.1%)
...,...,...,...,...,...,...
89.67,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
90.35,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
90.16,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
90.61,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
90.54,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO25):'

,2019,2020,2021,2022,2023,2024
NULOS,95498 (97.6%),62453 (96.2%),64715 (95.3%),74435 (95.3%),86374 (95.2%),94495 (95.3%)
93.18,80 (0.1%),87 (0.1%),120 (0.2%),148 (0.2%),154 (0.2%),168 (0.2%)
90.59,90 (0.1%),71 (0.1%),101 (0.1%),86 (0.1%),153 (0.2%),155 (0.2%)
99.29,63 (0.1%),78 (0.1%),94 (0.1%),108 (0.1%),133 (0.1%),145 (0.1%)
57.94,58 (0.1%),58 (0.1%),92 (0.1%),109 (0.1%),92 (0.1%),131 (0.1%)
...,...,...,...,...,...,...
99.11,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.39,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
57.18,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
57.33,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.94,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO25):'

,2019,2020,2021,2022,2023,2024
NULOS,1038442 (98.6%),696651 (97.2%),718220 (95.9%),829428 (97.0%),921893 (97.2%),958907 (97.2%)
93.18,572 (0.1%),701 (0.1%),959 (0.1%),891 (0.1%),1021 (0.1%),1023 (0.1%)
90.59,449 (0.0%),620 (0.1%),904 (0.1%),789 (0.1%),932 (0.1%),1056 (0.1%)
99.29,409 (0.0%),533 (0.1%),907 (0.1%),750 (0.1%),879 (0.1%),904 (0.1%)
89.65,454 (0.0%),513 (0.1%),800 (0.1%),667 (0.1%),701 (0.1%),685 (0.1%)
...,...,...,...,...,...,...
0.22,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.11,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.72,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.64,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.48,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO26] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO26: 869 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO26):'

,2019,2020,2021,2022,2023,2024
NULOS,1136258 (98.7%),762110 (97.5%),786959 (96.3%),907397 (97.3%),1012080 (97.4%),1057515 (97.4%)
93.18,577 (0.1%),682 (0.1%),1055 (0.1%),878 (0.1%),1026 (0.1%),985 (0.1%)
90.59,487 (0.0%),611 (0.1%),878 (0.1%),758 (0.1%),924 (0.1%),1012 (0.1%)
99.29,399 (0.0%),466 (0.1%),782 (0.1%),763 (0.1%),806 (0.1%),837 (0.1%)
57.94,368 (0.0%),496 (0.1%),838 (0.1%),630 (0.1%),636 (0.1%),666 (0.1%)
...,...,...,...,...,...,...
02.39,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
01.24,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
01.23,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
00.94,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
DESCONOCIDO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO26):'

,2019,2020,2021,2022,2023,2024
NULOS,95830 (98.0%),62820 (96.8%),65115 (95.9%),74914 (96.0%),86905 (95.8%),95088 (95.9%)
93.18,91 (0.1%),70 (0.1%),103 (0.2%),102 (0.1%),155 (0.2%),135 (0.1%)
90.59,65 (0.1%),62 (0.1%),80 (0.1%),99 (0.1%),99 (0.1%),134 (0.1%)
99.29,67 (0.1%),48 (0.1%),79 (0.1%),88 (0.1%),97 (0.1%),117 (0.1%)
99.21,45 (0.0%),45 (0.1%),60 (0.1%),89 (0.1%),88 (0.1%),104 (0.1%)
...,...,...,...,...,...,...
99.78,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
99.79,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
00.14,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.48,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.12,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO26):'

,2019,2020,2021,2022,2023,2024
NULOS,1040428 (98.8%),699290 (97.5%),721844 (96.4%),832483 (97.4%),925175 (97.5%),962427 (97.5%)
93.18,486 (0.0%),612 (0.1%),952 (0.1%),776 (0.1%),871 (0.1%),850 (0.1%)
90.59,422 (0.0%),549 (0.1%),798 (0.1%),659 (0.1%),825 (0.1%),878 (0.1%)
99.29,332 (0.0%),418 (0.1%),703 (0.1%),675 (0.1%),709 (0.1%),720 (0.1%)
89.65,364 (0.0%),465 (0.1%),716 (0.1%),546 (0.1%),588 (0.1%),562 (0.1%)
...,...,...,...,...,...,...
88.5,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
01.24,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
02.39,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.2,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.22,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO27] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO27: 856 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO27):'

,2019,2020,2021,2022,2023,2024
NULOS,1138209 (98.9%),764681 (97.8%),790667 (96.8%),910562 (97.6%),1015557 (97.7%),1061000 (97.7%)
93.18,467 (0.0%),583 (0.1%),818 (0.1%),808 (0.1%),847 (0.1%),896 (0.1%)
90.59,406 (0.0%),525 (0.1%),724 (0.1%),644 (0.1%),826 (0.1%),867 (0.1%)
99.29,311 (0.0%),444 (0.1%),625 (0.1%),599 (0.1%),709 (0.1%),761 (0.1%)
89.65,380 (0.0%),440 (0.1%),694 (0.1%),514 (0.1%),579 (0.1%),567 (0.1%)
...,...,...,...,...,...,...
0.31,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.19,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.25,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
86.91,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
86.89,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO27):'

,2019,2020,2021,2022,2023,2024
NULOS,96117 (98.3%),63090 (97.2%),65492 (96.4%),75332 (96.5%),87373 (96.3%),95601 (96.4%)
93.18,62 (0.1%),69 (0.1%),79 (0.1%),112 (0.1%),144 (0.2%),141 (0.1%)
90.59,59 (0.1%),54 (0.1%),66 (0.1%),72 (0.1%),116 (0.1%),131 (0.1%)
99.29,36 (0.0%),46 (0.1%),65 (0.1%),74 (0.1%),98 (0.1%),105 (0.1%)
57.94,41 (0.0%),59 (0.1%),60 (0.1%),72 (0.1%),91 (0.1%),80 (0.1%)
...,...,...,...,...,...,...
31.74,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
31.94,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.81,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.18,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.13,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO27):'

,2019,2020,2021,2022,2023,2024
NULOS,1042092 (98.9%),701591 (97.9%),725175 (96.8%),835230 (97.7%),928184 (97.8%),965399 (97.8%)
93.18,405 (0.0%),514 (0.1%),739 (0.1%),696 (0.1%),703 (0.1%),755 (0.1%)
90.59,347 (0.0%),471 (0.1%),658 (0.1%),572 (0.1%),710 (0.1%),736 (0.1%)
99.29,275 (0.0%),398 (0.1%),560 (0.1%),525 (0.1%),611 (0.1%),656 (0.1%)
89.65,342 (0.0%),393 (0.1%),635 (0.1%),463 (0.1%),514 (0.1%),508 (0.1%)
...,...,...,...,...,...,...
0.43,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.48,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.51,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.72,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.51,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

[PROCEDIMIENTO28] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO28: 803 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO28):'

,2019,2020,2021,2022,2023,2024
NULOS,1140018 (99.0%),766859 (98.1%),793861 (97.2%),913319 (97.9%),1018545 (98.0%),1064079 (98.0%)
93.18,360 (0.0%),530 (0.1%),660 (0.1%),660 (0.1%),729 (0.1%),745 (0.1%)
90.59,324 (0.0%),423 (0.1%),636 (0.1%),537 (0.1%),718 (0.1%),755 (0.1%)
99.29,310 (0.0%),342 (0.0%),570 (0.1%),552 (0.1%),542 (0.1%),598 (0.1%)
89.65,288 (0.0%),372 (0.0%),556 (0.1%),413 (0.0%),480 (0.0%),514 (0.0%)
...,...,...,...,...,...,...
1.13,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.46,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.54,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.57,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.02,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO28):'

,2019,2020,2021,2022,2023,2024
NULOS,96331 (98.5%),63324 (97.5%),65828 (96.9%),75689 (97.0%),87812 (96.8%),96029 (96.8%)
93.18,56 (0.1%),64 (0.1%),76 (0.1%),86 (0.1%),97 (0.1%),106 (0.1%)
90.59,40 (0.0%),44 (0.1%),67 (0.1%),58 (0.1%),87 (0.1%),113 (0.1%)
99.29,38 (0.0%),34 (0.1%),61 (0.1%),65 (0.1%),75 (0.1%),66 (0.1%)
57.94,40 (0.0%),28 (0.0%),52 (0.1%),54 (0.1%),78 (0.1%),58 (0.1%)
...,...,...,...,...,...,...
99.79,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.11,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.1,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
36.07,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.47,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO28):'

,2019,2020,2021,2022,2023,2024
NULOS,1043687 (99.1%),703535 (98.1%),728033 (97.2%),837630 (98.0%),930733 (98.1%),968050 (98.1%)
93.18,304 (0.0%),466 (0.1%),584 (0.1%),574 (0.1%),632 (0.1%),639 (0.1%)
90.59,284 (0.0%),379 (0.1%),569 (0.1%),479 (0.1%),631 (0.1%),642 (0.1%)
99.29,272 (0.0%),308 (0.0%),509 (0.1%),487 (0.1%),467 (0.0%),532 (0.1%)
89.65,256 (0.0%),339 (0.0%),517 (0.1%),361 (0.0%),437 (0.0%),445 (0.0%)
...,...,...,...,...,...,...
0.94,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.46,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.54,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.57,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.02,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

[PROCEDIMIENTO29] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO29: 772 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO29):'

,2019,2020,2021,2022,2023,2024
NULOS,1141521 (99.1%),768780 (98.3%),796738 (97.5%),915711 (98.2%),1021161 (98.2%),1066926 (98.3%)
93.18,395 (0.0%),444 (0.1%),618 (0.1%),556 (0.1%),613 (0.1%),644 (0.1%)
90.59,286 (0.0%),348 (0.0%),561 (0.1%),493 (0.1%),559 (0.1%),673 (0.1%)
99.29,219 (0.0%),296 (0.0%),459 (0.1%),446 (0.0%),486 (0.0%),486 (0.0%)
91.39,233 (0.0%),303 (0.0%),521 (0.1%),364 (0.0%),420 (0.0%),399 (0.0%)
...,...,...,...,...,...,...
34.03,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
34.06,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
34.1,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
99.99,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.03,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO29):'

,2019,2020,2021,2022,2023,2024
NULOS,96531 (98.7%),63548 (97.9%),66137 (97.4%),75982 (97.3%),88201 (97.2%),96453 (97.3%)
93.18,45 (0.0%),47 (0.1%),49 (0.1%),71 (0.1%),96 (0.1%),98 (0.1%)
90.59,32 (0.0%),41 (0.1%),50 (0.1%),48 (0.1%),75 (0.1%),95 (0.1%)
99.29,33 (0.0%),46 (0.1%),45 (0.1%),57 (0.1%),76 (0.1%),59 (0.1%)
91.39,31 (0.0%),40 (0.1%),50 (0.1%),27 (0.0%),68 (0.1%),63 (0.1%)
...,...,...,...,...,...,...
23.19,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
24.12,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
27.56,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.39,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.23,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO29):'

,2019,2020,2021,2022,2023,2024
NULOS,1044990 (99.2%),705232 (98.4%),730601 (97.5%),839729 (98.2%),932960 (98.3%),970473 (98.4%)
93.18,350 (0.0%),397 (0.1%),569 (0.1%),485 (0.1%),517 (0.1%),546 (0.1%)
90.59,254 (0.0%),307 (0.0%),511 (0.1%),445 (0.1%),484 (0.1%),578 (0.1%)
99.29,186 (0.0%),250 (0.0%),414 (0.1%),389 (0.0%),410 (0.0%),427 (0.0%)
89.65,230 (0.0%),270 (0.0%),390 (0.1%),347 (0.0%),369 (0.0%),360 (0.0%)
...,...,...,...,...,...,...
99.82,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
99.44,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
99.35,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
2.39,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
16.91,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

[PROCEDIMIENTO30] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad PROCEDIMIENTO30: 762 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (PROCEDIMIENTO30):'

,2019,2020,2021,2022,2023,2024
NULOS,1142853 (99.3%),770463 (98.5%),799219 (97.8%),917832 (98.4%),1023576 (98.5%),1069260 (98.5%)
93.18,288 (0.0%),358 (0.0%),534 (0.1%),524 (0.1%),517 (0.0%),575 (0.1%)
90.59,277 (0.0%),290 (0.0%),478 (0.1%),457 (0.0%),527 (0.1%),571 (0.1%)
99.29,180 (0.0%),223 (0.0%),407 (0.0%),378 (0.0%),403 (0.0%),438 (0.0%)
89.65,231 (0.0%),282 (0.0%),464 (0.1%),336 (0.0%),340 (0.0%),366 (0.0%)
...,...,...,...,...,...,...
2.31,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.5,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.42,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.39,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
0.01,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (PROCEDIMIENTO30):'

,2019,2020,2021,2022,2023,2024
NULOS,96720 (98.9%),63727 (98.2%),66341 (97.7%),76237 (97.7%),88511 (97.6%),96818 (97.6%)
93.18,42 (0.0%),41 (0.1%),45 (0.1%),66 (0.1%),77 (0.1%),90 (0.1%)
90.59,34 (0.0%),30 (0.0%),45 (0.1%),54 (0.1%),72 (0.1%),72 (0.1%)
99.29,28 (0.0%),16 (0.0%),47 (0.1%),54 (0.1%),46 (0.1%),61 (0.1%)
57.94,28 (0.0%),34 (0.1%),36 (0.1%),39 (0.0%),45 (0.0%),59 (0.1%)
...,...,...,...,...,...,...
97.88,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
0.4,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
99.78,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
99.83,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
0.39,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'3. Frecuencia para cohorte control (PROCEDIMIENTO30):'

,2019,2020,2021,2022,2023,2024
NULOS,1046133 (99.3%),706736 (98.6%),732878 (97.8%),841595 (98.5%),935065 (98.5%),972442 (98.6%)
93.18,246 (0.0%),317 (0.0%),489 (0.1%),458 (0.1%),440 (0.0%),485 (0.0%)
90.59,243 (0.0%),260 (0.0%),433 (0.1%),403 (0.0%),455 (0.0%),499 (0.1%)
89.65,202 (0.0%),243 (0.0%),419 (0.1%),301 (0.0%),300 (0.0%),316 (0.0%)
99.29,152 (0.0%),207 (0.0%),360 (0.0%),324 (0.0%),357 (0.0%),377 (0.0%)
...,...,...,...,...,...,...
99.48,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
99.51,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
99.96,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.09,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.01,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **21. Especialidad de Intervención (ESPECIALIDADINTERVENCION)**
- **Tipo de variable**: Hospitalaria.
- **Descripción**: Especialidad médica o quirúrgica del profesional que realizó una intervención específica durante la hospitalización.
- **Cardinalidad**: Alta (104 categorías únicas).
- **Veredicto**: **Descartar**. Aunque en este diseño de caracterización retrospectiva no hay riesgo de fuga de datos, la variable presenta graves problemas de densidad de la información. Entre el 48% y el 63% de los registros en la cohorte oncológica son nulos, lo cual es lógicamente esperado ya que no todos los pacientes ingresados requieren intervención quirúrgica. Mantener una variable tan fragmentada aportará ruido innecesario, sobre todo considerando que la variable estructural `ESPECIALIDAD_MEDICA` ya será retenida, agrupada y mapeada en el modelo.

In [23]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"ESPECIALIDADINTERVENCION")
mostrar_resultados(total, oncologico, control, "ESPECIALIDADINTERVENCION")

[ESPECIALIDADINTERVENCION] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad ESPECIALIDADINTERVENCION: 104 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (ESPECIALIDADINTERVENCION):'

,2019,2020,2021,2022,2023,2024
NULOS,543389 (47.2%),369837 (47.3%),384249 (47.0%),398021 (42.7%),440727 (42.4%),465915 (42.9%)
CIRUGIA GENERAL,139715 (12.1%),97290 (12.4%),102871 (12.6%),122801 (13.2%),133431 (12.8%),140966 (13.0%)
OBSTETRICIA Y GINECOLOGIA,126346 (11.0%),103155 (13.2%),105027 (12.9%),118808 (12.7%),120993 (11.6%),121169 (11.2%)
TRAUMATOLOGIA Y ORTOPEDIA,69895 (6.1%),49030 (6.3%),54794 (6.7%),67386 (7.2%),81827 (7.9%),84729 (7.8%)
OFTALMOLOGIA,63131 (5.5%),30351 (3.9%),37268 (4.6%),53023 (5.7%),66180 (6.4%),67594 (6.2%)
...,...,...,...,...,...,...
ADOLESCENCIA (PEDIATRIA),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
FACOERESIS EXTRACAPSULAR CON I,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
ADOLESCENCIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
MEDICINA NUCLEAR,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
REUMATOLOGIA PEDIATRICA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

'2. Frecuencia para cohorte oncológica (ESPECIALIDADINTERVENCION):'

,2019,2020,2021,2022,2023,2024
NULOS,62502 (63.9%),36922 (56.9%),34855 (51.3%),38064 (48.8%),44062 (48.6%),49513 (49.9%)
CIRUGIA GENERAL,15860 (16.2%),13033 (20.1%),14824 (21.8%),17435 (22.3%),19344 (21.3%),19616 (19.8%)
UROLOGIA,4701 (4.8%),3703 (5.7%),4397 (6.5%),5156 (6.6%),6146 (6.8%),6667 (6.7%)
OBSTETRICIA Y GINECOLOGIA,4475 (4.6%),3558 (5.5%),4121 (6.1%),5126 (6.6%),5806 (6.4%),5967 (6.0%)
"CIRUGIA DE CABEZA, CUELLO Y MAXILOFACIAL",0 (0.0%),774 (1.2%),1026 (1.5%),1553 (2.0%),2006 (2.2%),2553 (2.6%)
...,...,...,...,...,...,...
ENFERNEDADES RESPIRATORIAS PEDIATRICA,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
GENETICA CLINICA,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
GERIATRIA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
NEFROLOGIA PEDIATRICA,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
MEDICINA FAMILIAR,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (ESPECIALIDADINTERVENCION):'

,2019,2020,2021,2022,2023,2024
NULOS,480887 (45.6%),332915 (46.4%),349394 (46.6%),359957 (42.1%),396665 (41.8%),416402 (42.2%)
OBSTETRICIA Y GINECOLOGIA,121871 (11.6%),99597 (13.9%),100906 (13.5%),113682 (13.3%),115187 (12.1%),115202 (11.7%)
CIRUGIA GENERAL,123855 (11.8%),84257 (11.8%),88047 (11.8%),105366 (12.3%),114087 (12.0%),121350 (12.3%)
TRAUMATOLOGIA Y ORTOPEDIA,69024 (6.6%),48283 (6.7%),53863 (7.2%),66273 (7.8%),80315 (8.5%),83069 (8.4%)
OFTALMOLOGIA,62426 (5.9%),30002 (4.2%),36732 (4.9%),52236 (6.1%),65186 (6.9%),66521 (6.7%)
...,...,...,...,...,...,...
ADOLESCENCIA (PEDIATRIA),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
FACOERESIS EXTRACAPSULAR CON I,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
ADOLESCENCIA,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
MEDICINA NUCLEAR,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
REUMATOLOGIA PEDIATRICA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)

### **22. Uso de Pabellón (USOSPABELLON)**
- **Tipo de variable**: Hospitalaria.
- **Descripción**: Indica si el paciente utilizó un quirófano (pabellón) y de qué tipo (central, urgencia, ambulatorio, etc.).
- **Cardinalidad**: Alta y ruidosa (71 categorías únicas, superando ampliamente las 8 esperadas según el diccionario oficial).
- **Veredicto**: **Retener, Limpiar y Binarizar**. En el contexto de un modelo explicativo (donde se descartó el problema de fuga temporal de datos), el uso de pabellón es un proxy fundamental del nivel de invasividad y consumo de recursos del episodio oncológico. No obstante, la columna está contaminada con errores de digitación (ej. códigos alfanuméricos como "7001546-3" o "A?AO") y presenta cerca de un 45-60% de valores nulos. Para evitar dispersión, se transformará en una variable dicotómica `USO_PABELLON` (1 = Sí, 0 = No), colapsando los códigos válidos en la clase positiva y asumiendo los nulos y valores anómalos como ausencia de uso quirúrgico.
##### **Tabla (diccionario de datos extraído del sitio de "Fonasa - Datos abiertos")**:

| ID | Tipo de pabellón                         |
|----|------------------------------------------|
| 1  | Pabellón Central u Obstétrico           |
| 2  | Pabellón ambulatorio                    |
| 3  | Sala de procedimiento                   |
| 4  | Pabellón Hemodinamia                    |
| 5  | Pabellón de Urgencia                    |
| 6  | Pabellón de Urgencia habilitado en UCI  |
| 7  | H. de Campaña                           |
| 8  | Operativos Especiales                   |

## Evaluación y Descarte de Variable Operativa: Uso de Pabellón (USOPABELLON)

### 1. Descripción de la Variable
La variable `USOPABELLON` (teóricamente codificada del 1 al 8 según el estándar MINSAL) buscaba registrar el tipo de quirófano utilizado durante el episodio clínico (ej. Pabellón Central, Ambulatorio, Hemodinamia). 

### 2. Análisis de Calidad de Datos (CRISP-DM: Data Understanding)
Al auditar las frecuencias transversales de la variable para el sexenio 2019-2024, se detectaron fallas estructurales insalvables que inhabilitan su uso en cualquier modelo predictivo:

* **Tasa de Valores Nulos Crítica y Sesgo Temporal:** * Históricamente, la variable presenta un ~40% de datos faltantes (2021-2024).
  * **Falla Catastrófica en 2020:** La variable registra un **100.0% de valores nulos para todo el año 2020**. Esto impide cualquier análisis longitudinal y descarta la hipótesis de que un "nulo" significa "no se usó pabellón" (ya que la actividad quirúrgica, aunque reducida por la pandemia, nunca fue cero).
* **Corrupción Estructural de la Base de Datos:** Los registros de 2019 evidencian un problema de *data leakage* o desplazamiento de columnas desde el sistema origen (MINSAL). La columna contiene RUTs de pacientes (ej. `15851762-0`), fechas (`15/07/2019`) y caracteres corruptos (`A?AO`), demostrando que el campo almacenó basura informática en lugar del código esperado.

### 3. Redundancia de la Información
La pérdida de esta columna no afecta el poder predictivo del modelo, ya que la señal de "complejidad quirúrgica" ya fue capturada exitosamente y con alta calidad a través de tres variables ya procesadas:
1. `TIPO_ACTIVIDAD` (Aísla los casos de Cirugía Mayor Ambulatoria - CMA).
2. `SERVICIOINGRESO` (Aísla los ingresos al Área Quirúrgica).
3. `PROCEDIMIENTO1` (Define anatómicamente la cirugía realizada).

### 4. Veredicto Final
**Variable Descartada.** Se elimina la columna `USOPABELLON` del dataset definitivo por violación de los principios de integridad de datos, exceso de nulos (>40% a 100%) y corrupción de formato. Imputar estos valores introduciría un sesgo inaceptable en el modelo.

In [24]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"USOSPABELLON")
mostrar_resultados(total, oncologico, control, "USOSPABELLON")

[USOSPABELLON] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad USOSPABELLON: 71 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (USOSPABELLON):'

,2019,2020,2021,2022,2023,2024
NULOS,509092 (44.2%),781857 (100.0%),354166 (43.4%),367631 (39.4%),404206 (38.9%),430231 (39.6%)
1.0,0 (0.0%),40 (0.0%),378419 (46.3%),454467 (48.7%),495894 (47.7%),503243 (46.3%)
1,534536 (46.4%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
2.0,0 (0.0%),4 (0.0%),47869 (5.9%),68339 (7.3%),87929 (8.5%),91381 (8.4%)
3.0,0 (0.0%),10 (0.0%),24166 (3.0%),25689 (2.8%),30293 (2.9%),34844 (3.2%)
...,...,...,...,...,...,...
7001546-3,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
7108401-9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
741,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A?AO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A?A¿1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (USOSPABELLON):'

,2019,2020,2021,2022,2023,2024
NULOS,59059 (60.4%),64919 (100.0%),31997 (47.1%),35444 (45.4%),40570 (44.7%),45666 (46.1%)
1.0,0 (0.0%),3 (0.0%),29865 (44.0%),35143 (45.0%),39776 (43.8%),41629 (42.0%)
1,33486 (34.2%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
2.0,0 (0.0%),1 (0.0%),3377 (5.0%),4190 (5.4%),5936 (6.5%),6097 (6.1%)
3.0,0 (0.0%),3 (0.0%),2283 (3.4%),2677 (3.4%),3579 (3.9%),4445 (4.5%)
2,2996 (3.1%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
3,2244 (2.3%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
4.0,0 (0.0%),0 (0.0%),250 (0.4%),409 (0.5%),562 (0.6%),714 (0.7%)
5.0,0 (0.0%),0 (0.0%),148 (0.2%),194 (0.2%),257 (0.3%),364 (0.4%)
6.0,0 (0.0%),0 (0.0%),2 (0.0%),12 (0.0%),28 (0.0%),201 (0.2%)
8.0,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),7 (0.0%),37 (0.0%)
4,27 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0,8 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
0.0,0 (0.0%),0 (0.0%),3 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
5,3 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
8,2 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
249,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
200,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
11,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (USOSPABELLON):'

,2019,2020,2021,2022,2023,2024
NULOS,450033 (42.7%),716938 (100.0%),322169 (43.0%),332187 (38.9%),363636 (38.3%),384565 (39.0%)
1.0,0 (0.0%),37 (0.0%),348554 (46.5%),419324 (49.1%),456118 (48.1%),461614 (46.8%)
1,501050 (47.6%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
2.0,0 (0.0%),3 (0.0%),44492 (5.9%),64149 (7.5%),81993 (8.6%),85284 (8.6%)
3.0,0 (0.0%),7 (0.0%),21883 (2.9%),23012 (2.7%),26714 (2.8%),30399 (3.1%)
...,...,...,...,...,...,...
7001546-3,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
7108401-9,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
741,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A?AO,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
A?A¿1,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **23. Código GRD (IR_29301_COD_GRD)**
- **Tipo de variable**: Hospitalaria / Administrativa.
- **Descripción**: Código final del Grupo Relacionado por el Diagnóstico asignado por el agrupador de FONASA al egreso.
- **Cardinalidad**: Muy Alta (1.671 categorías únicas extraídas).
- **Veredicto**: **Descartar**. Este código es el resultado determinista del algoritmo de facturación, calculado *a posteriori* combinando diagnósticos, procedimientos y edad. Dado que los modelos de aprendizaje automático buscarán caracterizar la severidad y el consumo de recursos (cuyo peso ponderado se extrae directamente de este mismo código), incluirlo generaría una colinealidad perfecta o "circularidad matemática". Sumado a ello, aplicar *One-Hot Encoding* sobre 1.671 categorías colapsaría la capacidad de convergencia y generalización de los selectores de características.

In [25]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"IR_29301_COD_GRD")
mostrar_resultados(total, oncologico, control, "IR_29301_COD_GRD")

[IR_29301_COD_GRD] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad IR_29301_COD_GRD: 1671 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (IR_29301_COD_GRD):'

,2019,2020,2021,2022,2023,2024
022360,42984 (3.7%),0 (0.0%),0 (0.0%),39235 (4.2%),50288 (4.8%),51237 (4.7%)
146101,38970 (3.4%),31185 (4.0%),26192 (3.2%),29000 (3.1%),28342 (2.7%),26664 (2.5%)
146121,26649 (2.3%),22253 (2.8%),19667 (2.4%),22720 (2.4%),23269 (2.2%),19729 (1.8%)
146131,30970 (2.7%),25076 (3.2%),19920 (2.4%),21512 (2.3%),19274 (1.9%),17042 (1.6%)
134161,19176 (1.7%),14583 (1.9%),13550 (1.7%),14214 (1.5%),14927 (1.4%),14689 (1.4%)
...,...,...,...,...,...,...
12110,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
159160,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
23130,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
51011,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
990139,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (IR_29301_COD_GRD):'

,2019,2020,2021,2022,2023,2024
174132,6076 (6.2%),4650 (7.2%),3950 (5.8%),4104 (5.3%),4375 (4.8%),5020 (5.1%)
174133,2620 (2.7%),2310 (3.6%),2163 (3.2%),2030 (2.6%),2453 (2.7%),2566 (2.6%)
174131,3178 (3.2%),2058 (3.2%),1607 (2.4%),1424 (1.8%),1933 (2.1%),2141 (2.2%)
161201,2156 (2.2%),1733 (2.7%),1794 (2.6%),2140 (2.7%),2190 (2.4%),2309 (2.3%)
092420,2137 (2.2%),0 (0.0%),0 (0.0%),2427 (3.1%),3615 (4.0%),3596 (3.6%)
...,...,...,...,...,...,...
051021,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%)
224103,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
11011,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
111011,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%)
990119,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (IR_29301_COD_GRD):'

,2019,2020,2021,2022,2023,2024
022360,42646 (4.0%),0 (0.0%),0 (0.0%),38752 (4.5%),49711 (5.2%),50630 (5.1%)
146101,38951 (3.7%),31158 (4.3%),26168 (3.5%),28974 (3.4%),28313 (3.0%),26636 (2.7%)
146121,26642 (2.5%),22244 (3.1%),19656 (2.6%),22715 (2.7%),23263 (2.5%),19720 (2.0%)
146131,30961 (2.9%),25072 (3.5%),19916 (2.7%),21506 (2.5%),19270 (2.0%),17032 (1.7%)
134161,19164 (1.8%),14571 (2.0%),13538 (1.8%),14194 (1.7%),14916 (1.6%),14672 (1.5%)
...,...,...,...,...,...,...
012110,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
173100,1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
51011,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
990139,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
94113,0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

### **24. Probabilidad de Mortalidad GRD (IR_29301_MORTALIDAD)**
- **Tipo de variable**: Clínica / Calculada.
- **Descripción**: Probabilidad teórica o nivel de riesgo de mortalidad asignado por el software agrupador GRD al finalizar la estadía.
- **Cardinalidad**: Baja (4 categorías).
- **Veredicto**: **Descartar**. Se trata de un índice sintético pre-calculado por un sistema externo. Retenerlo es redundante y contraproducente metodológicamente: el conjunto de datos ya cuenta con la variable objetivo real y definitiva del desenlace del paciente (`TIPOALTA` binarizada en Vivo/Fallecido). En un modelo de *Machine Learning* explicativo, el objetivo es que el propio algoritmo aprenda a ponderar las reglas y factores de riesgo desde las condiciones clínicas basales y operativas, no obligarlo a "leer" la predicción elaborada por un tercero.

##### **Tabla (diccionario de datos extraído del sitio de "Fonasa - Datos abiertos")**:

| ID | Gravedad     |
|----|--------------|
| 0  | Sin gravedad |
| 1  | Menor        |
| 2  | Moderada     |
| 3  | Mayor        |

In [26]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"IR_29301_MORTALIDAD")
mostrar_resultados(total, oncologico, control, "IR_29301_MORTALIDAD")

[IR_29301_MORTALIDAD] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad IR_29301_MORTALIDAD: 4 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (IR_29301_MORTALIDAD):'

,2019,2020,2021,2022,2023,2024
1,658994 (57.2%),443943 (56.8%),424123 (51.9%),476812 (51.1%),510177 (49.1%),509445 (46.9%)
0,202517 (17.6%),79664 (10.2%),102938 (12.6%),154772 (16.6%),193550 (18.6%),212051 (19.5%)
2,165823 (14.4%),137766 (17.6%),137256 (16.8%),155117 (16.6%),166014 (16.0%),180092 (16.6%)
3,124043 (10.8%),120538 (15.4%),152592 (18.7%),146113 (15.7%),169816 (16.3%),184210 (17.0%)
DESCONOCIDO,21 (0.0%),0 (0.0%),0 (0.0%),23 (0.0%),30 (0.0%),15 (0.0%)

'2. Frecuencia para cohorte oncológica (IR_29301_MORTALIDAD):'

,2019,2020,2021,2022,2023,2024
2,30206 (30.9%),23050 (35.5%),22595 (33.3%),25523 (32.7%),29591 (32.6%),32344 (32.6%)
3,24186 (24.7%),20997 (32.3%),21803 (32.1%),24983 (32.0%),29706 (32.7%),33896 (34.2%)
1,22762 (23.3%),17231 (26.5%),17839 (26.3%),19652 (25.2%),21203 (23.4%),21830 (22.0%)
0,20675 (21.1%),3648 (5.6%),5689 (8.4%),7909 (10.1%),10215 (11.3%),11081 (11.2%)
DESCONOCIDO,0 (0.0%),0 (0.0%),0 (0.0%),2 (0.0%),0 (0.0%),2 (0.0%)

'3. Frecuencia para cohorte control (IR_29301_MORTALIDAD):'

,2019,2020,2021,2022,2023,2024
1,636232 (60.4%),426712 (59.5%),406284 (54.2%),457160 (53.5%),488974 (51.5%),487615 (49.4%)
0,181842 (17.3%),76016 (10.6%),97249 (13.0%),146863 (17.2%),183335 (19.3%),200970 (20.4%)
2,135617 (12.9%),114716 (16.0%),114661 (15.3%),129594 (15.2%),136423 (14.4%),147748 (15.0%)
3,99857 (9.5%),99541 (13.9%),130789 (17.5%),121130 (14.2%),140110 (14.8%),150314 (15.2%)
DESCONOCIDO,21 (0.0%),0 (0.0%),0 (0.0%),21 (0.0%),30 (0.0%),13 (0.0%)

### **25. Hospital de Procedencia (HOSPPROCEDENCIA)**
- **Tipo de variable**: Hospitalaria.
- **Descripción**: Nombre o código del hospital específico desde el cual el paciente fue derivado antes de ingresar.
- **Cardinalidad**: Muy Alta (518 categorías únicas).
- **Veredicto**: **Descartar por densidad insuficiente**. La extracción de frecuencias revela un patrón categórico insostenible: entre el 89% y el 92% de los episodios oncológicos presentan valores nulos en esta variable. Esto indica empíricamente que 9 de cada 10 pacientes ingresan de forma directa, o bien la derivación inter-hospitalaria específica no se registra de manera sistemática en la red. Inyectar 518 columnas *dummy* para explicar un fenómeno que solo ocurre en menos del 10% de la muestra penalizaría al modelo sin aportar valor generalizable. El impacto epidemiológico de las derivaciones ya está asegurado y sintetizado metodológicamente a través de la variable `TIPO_PROCEDENCIA` macro (ej. categoría agrupada "OTROS HOSPITALES DE LA RED").

In [27]:
total, oncologico, control = distribucion_categorica_matriz(carpeta, archivos, mapa_columnas,"HOSPPROCEDENCIA")
mostrar_resultados(total, oncologico, control, "HOSPPROCEDENCIA")

[HOSPPROCEDENCIA] Extrayendo y procesando datos masivos (Una sola pasada)...
✓ Cardinalidad HOSPPROCEDENCIA: 518 categorías únicas
✓ Archivos CSV generados y guardados en las 3 carpetas correspondientes.

'1. Frecuencia para cohorte total (HOSPPROCEDENCIA):'

,2019,2020,2021,2022,2023,2024
NULOS,1025386 (89.1%),676219 (86.5%),699687 (85.7%),810634 (86.9%),899461 (86.5%),993216 (91.5%)
HOSPITAL SAN PABLO (COQUIMBO),18258 (1.6%),12731 (1.6%),14180 (1.7%),15439 (1.7%),17726 (1.7%),17183 (1.6%)
HOSPITAL CLINICO DE MAGALLANES DR. LAUTARO NAVARRO AVARIA,12059 (1.0%),7859 (1.0%),9046 (1.1%),10354 (1.1%),12018 (1.2%),0 (0.0%)
HOSPITAL SAN JOSE (CORONEL),7557 (0.7%),5617 (0.7%),5743 (0.7%),7349 (0.8%),8537 (0.8%),8975 (0.8%)
HOSPITAL CARLOS VAN BUREN (VALPARAISO),5505 (0.5%),2645 (0.3%),2411 (0.3%),2332 (0.2%),2802 (0.3%),3232 (0.3%)
...,...,...,...,...,...,...
CENTRO DE ATENCION INSTITUTO DE SEGURIDAD DEL TRABAJADOR PUNTA ARENAS,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
200417,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
101238,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
SERVICIOS CLINICOS NEUROPSIQUIATRICOS Y GERIATRICOS R Y G LIMITADA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
URODIAL LTDA.,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)

'2. Frecuencia para cohorte oncológica (HOSPPROCEDENCIA):'

,2019,2020,2021,2022,2023,2024
NULOS,89800 (91.8%),58540 (90.2%),61016 (89.8%),70415 (90.2%),81256 (89.6%),91929 (92.7%)
HOSPITAL SAN PABLO (COQUIMBO),1163 (1.2%),925 (1.4%),1129 (1.7%),1276 (1.6%),1534 (1.7%),1512 (1.5%)
HOSPITAL CLINICO DE MAGALLANES DR. LAUTARO NAVARRO AVARIA,877 (0.9%),534 (0.8%),627 (0.9%),804 (1.0%),943 (1.0%),0 (0.0%)
HOSPITAL CARLOS VAN BUREN (VALPARAISO),1476 (1.5%),361 (0.6%),327 (0.5%),328 (0.4%),457 (0.5%),504 (0.5%)
HOSPITAL SAN JOSE (CORONEL),326 (0.3%),283 (0.4%),210 (0.3%),241 (0.3%),356 (0.4%),453 (0.5%)
...,...,...,...,...,...,...
CLINICA AMBULATORIA SANATORIO ALEMAN SAN PEDRO,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
INTERMEDICA DIVISION DIALISIS LTDA. SUCURSAL LONGAVI,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
ONG CORPORACION DE DIALIZADOS Y TRANSPLANTADOS MAYMURU DE ARICA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
NEPHROCARE CHILE S.A. SUCURSAL TALCA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
103269,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)

'3. Frecuencia para cohorte control (HOSPPROCEDENCIA):'

,2019,2020,2021,2022,2023,2024
NULOS,935586 (88.8%),617679 (86.1%),638671 (85.3%),740219 (86.6%),818205 (86.2%),901287 (91.3%)
HOSPITAL SAN PABLO (COQUIMBO),17095 (1.6%),11806 (1.6%),13051 (1.7%),14163 (1.7%),16192 (1.7%),15671 (1.6%)
HOSPITAL CLINICO DE MAGALLANES DR. LAUTARO NAVARRO AVARIA,11182 (1.1%),7325 (1.0%),8419 (1.1%),9550 (1.1%),11075 (1.2%),0 (0.0%)
HOSPITAL SAN JOSE (CORONEL),7231 (0.7%),5334 (0.7%),5533 (0.7%),7108 (0.8%),8181 (0.9%),8522 (0.9%)
HOSPITAL CARLOS VAN BUREN (VALPARAISO),4029 (0.4%),2284 (0.3%),2084 (0.3%),2004 (0.2%),2345 (0.2%),2728 (0.3%)
...,...,...,...,...,...,...
CEMED LIMACHE,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
CENTRO DE DIALISIS CLINIDIAL LA SERENA,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)
101238,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
SERVICIOS CLINICOS NEUROPSIQUIATRICOS Y GERIATRICOS R Y G LIMITADA,0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
URODIAL LTDA.,0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),1 (0.0%),0 (0.0%)